# coding: utf-8

"""
    VRChat API Documentation


    The version of the OpenAPI document: 1.20.8
    Contact: vrchatapi.lpv0t@aries.fyi
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AgeVerificationStatus(str, Enum):
    """
    `verified` is obsolete.  User who have verified and are 18+ can switch to `plus18` status. 
    """

    """
    allowed enum values
    """
    plus18 = '18+'
    hidden = 'hidden'
    verified = 'verified'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AgeVerificationStatus from a JSON string"""
        return cls(json.loads(json_str))


