# coding: utf-8

"""
    VRChat API Documentation


    The version of the OpenAPI document: 1.20.8
    Contact: vrchatapi.lpv0t@aries.fyi
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from collections.abc import Mapping as _Mapping
from pydantic import AliasChoices, BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, cast as _cast
from vrchatapi.models.agreement_code import AgreementCode
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


_OPENAPI_GENERATOR_TO_DICT = "_openapi_generator_to_dict"


def _get_openapi_to_dict(value: Any) -> Any:
    # Reciprocal function references preserve inherited generated methods
    # without reserving model member names. Checking both directions also
    # rejects overrides whose decorators copy function attributes.
    to_dict = getattr(value, "to_dict", None)
    type_to_dict = getattr(type(value), "to_dict", None)
    if (
        not callable(to_dict)
        or getattr(to_dict, "__func__", None) is not type_to_dict
    ):
        return None

    openapi_to_dict = getattr(
        type_to_dict, _OPENAPI_GENERATOR_TO_DICT, None
    )
    if (
        not callable(openapi_to_dict)
        or getattr(
            openapi_to_dict,
            _OPENAPI_GENERATOR_TO_DICT,
            None,
        ) is not type_to_dict
    ):
        return None
    return openapi_to_dict


def _to_legacy_item(value: Any, serialize: bool) -> Any:
    to_dict = getattr(value, "to_dict", None)
    if _get_openapi_to_dict(value) is not None and callable(to_dict):
        return to_dict(serialize=serialize)
    if callable(to_dict):
        return to_dict()
    return value


def _to_legacy_value(value: Any, serialize: bool) -> Any:
    # python-legacy converted only immediate list elements or dictionary values:
    # https://github.com/OpenAPITools/openapi-generator/blob/c84b949df1a9ec04ba75989cb49b45c940c2f694/modules/openapi-generator/src/main/resources/python-legacy/model.mustache#L203-L231
    if isinstance(value, list):
        return [_to_legacy_item(item, serialize) for item in value]
    if isinstance(value, dict):
        return {
            key: _to_legacy_item(item, serialize)
            for key, item in value.items()
        }
    return _to_legacy_item(value, serialize)


def _to_openapi_value(value: Any) -> Any:
    if isinstance(value, list):
        return [_to_openapi_value(item) for item in value]
    if isinstance(value, dict):
        return {key: _to_openapi_value(item) for key, item in value.items()}

    to_openapi_dict = _get_openapi_to_dict(value)
    if to_openapi_dict is not None:
        return to_openapi_dict(value)

    to_dict = getattr(value, "to_dict", None)
    if callable(to_dict):
        return to_dict()
    return value


class AgreementRequest(BaseModel):
    """
    AgreementRequest

    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """ # noqa: E501
    agreement_code: Optional[AgreementCode] = Field(default=None, validation_alias=AliasChoices("agreementCode", "agreement_code"), serialization_alias="agreementCode")
    agreement_fulltext: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("agreementFulltext", "agreement_fulltext"), serialization_alias="agreementFulltext", description="The full text of the agreement (currently `By clicking OK, I certify that I have the necessary rights to upload this content and that it will not infringe on any third-party legal or intellectual property rights.`).", json_schema_extra={"examples": ["By clicking OK, I certify that I have the necessary rights to upload this content and that it will not infringe on any third-party legal or intellectual property rights."]})
    content_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("contentId", "content_id"), serialization_alias="contentId", description="The id of the content being uploaded, such as a WorldID, AvatarID, or PropID.", json_schema_extra={"examples": ["avtr_c38a1615-5bf5-42b4-84eb-a8b6c37cbd11"]})
    version: Optional[StrictInt] = Field(default=None, description="The version of the agreement (currently `1`).", json_schema_extra={"examples": [1]})
    openapi_types: ClassVar[Dict[str, str]] = {
        "agreement_code": "AgreementCode",
        "agreement_fulltext": "str",
        "content_id": "str",
        "version": "int"
    }

    attribute_map: ClassVar[Dict[str, str]] = {
        "agreement_code": "agreementCode",
        "agreement_fulltext": "agreementFulltext",
        "content_id": "contentId",
        "version": "version"
    }
    __properties: ClassVar[List[str]] = ["agreementCode", "agreementFulltext", "contentId", "version"]

    @classmethod
    def __preprocess_input_names(
        cls,
        obj: Any,
        remove_hidden_storage_names: bool = True,
    ) -> Any:
        if not isinstance(obj, _Mapping):
            return obj
        obj = dict(obj)
        if "agreementCode" not in obj and "agreement_code" in obj:
            obj["agreementCode"] = obj["agreement_code"]
        obj.pop("agreement_code", None)
        if "agreementFulltext" not in obj and "agreement_fulltext" in obj:
            obj["agreementFulltext"] = obj["agreement_fulltext"]
        obj.pop("agreement_fulltext", None)
        if "contentId" not in obj and "content_id" in obj:
            obj["contentId"] = obj["content_id"]
        obj.pop("content_id", None)
        return obj

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        extra="forbid",
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For print and pprint"""
        return self.to_str()

    def __eq__(self, other: object) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, AgreementRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other: object) -> bool:
        """Returns true if both objects are not equal"""
        if not isinstance(other, AgreementRequest):
            return True

        return not (self == other)


    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        to_openapi_dict = _get_openapi_to_dict(self)
        if to_openapi_dict is not None:
            return json.dumps(to_jsonable_python(to_openapi_dict(self)))
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgreementRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self, serialize: bool = False) -> Dict[str, Any]:
        """Return all declared model fields using public or wire names."""
        return {
            ("agreementCode" if serialize else "agreement_code"): _to_legacy_value(getattr(self, "agreement_code", None), serialize),
            ("agreementFulltext" if serialize else "agreement_fulltext"): _to_legacy_value(getattr(self, "agreement_fulltext", None), serialize),
            ("contentId" if serialize else "content_id"): _to_legacy_value(getattr(self, "content_id", None), serialize),
            ("version" if serialize else "version"): _to_legacy_value(getattr(self, "version", None), serialize),
        }

    def __openapi_generator_modern_projection(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    setattr(
        to_dict,
        _OPENAPI_GENERATOR_TO_DICT,
        __openapi_generator_modern_projection,
    )
    setattr(
        __openapi_generator_modern_projection,
        _OPENAPI_GENERATOR_TO_DICT,
        to_dict,
    )
    del __openapi_generator_modern_projection

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgreementRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        obj = _cast(
            Dict[str, Any],
            cls.__preprocess_input_names(
                obj,
                remove_hidden_storage_names=True,
            ),
        )

        _obj = cls.model_validate({
            "agreementCode": obj.get("agreementCode") if obj.get("agreementCode") is not None else AgreementCode.CONTENT_DOT_COPYRIGHT_DOT_OWNED,
            "agreementFulltext": obj.get("agreementFulltext"),
            "contentId": obj.get("contentId"),
            "version": obj.get("version")
        })
        return _obj


