# coding: utf-8

"""
    VRChat API Documentation


    The version of the OpenAPI document: 1.21.0
    Contact: vrchatapi.lpv0t@aries.fyi
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from collections.abc import Mapping as _Mapping
from datetime import datetime
from pydantic import AliasChoices, BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, cast as _cast
from vrchatapi.models.beta_user_field import BetaUserField
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


_OPENAPI_GENERATOR_TO_DICT = "_openapi_generator_to_dict"


def _get_openapi_to_dict(value: Any) -> Any:
    # Reciprocal function references preserve inherited generated methods
    # without reserving model member names. Checking both directions also
    # rejects overrides whose decorators copy function attributes.
    to_dict = getattr(value, "to_dict", None)
    type_to_dict = getattr(type(value), "to_dict", None)
    if (
        not callable(to_dict)
        or getattr(to_dict, "__func__", None) is not type_to_dict
    ):
        return None

    openapi_to_dict = getattr(
        type_to_dict, _OPENAPI_GENERATOR_TO_DICT, None
    )
    if (
        not callable(openapi_to_dict)
        or getattr(
            openapi_to_dict,
            _OPENAPI_GENERATOR_TO_DICT,
            None,
        ) is not type_to_dict
    ):
        return None
    return openapi_to_dict


def _to_legacy_item(value: Any, serialize: bool) -> Any:
    to_dict = getattr(value, "to_dict", None)
    if _get_openapi_to_dict(value) is not None and callable(to_dict):
        return to_dict(serialize=serialize)
    if callable(to_dict):
        return to_dict()
    return value


def _to_legacy_value(value: Any, serialize: bool) -> Any:
    # python-legacy converted only immediate list elements or dictionary values:
    # https://github.com/OpenAPITools/openapi-generator/blob/c84b949df1a9ec04ba75989cb49b45c940c2f694/modules/openapi-generator/src/main/resources/python-legacy/model.mustache#L203-L231
    if isinstance(value, list):
        return [_to_legacy_item(item, serialize) for item in value]
    if isinstance(value, dict):
        return {
            key: _to_legacy_item(item, serialize)
            for key, item in value.items()
        }
    return _to_legacy_item(value, serialize)


def _to_openapi_value(value: Any) -> Any:
    if isinstance(value, list):
        return [_to_openapi_value(item) for item in value]
    if isinstance(value, dict):
        return {key: _to_openapi_value(item) for key, item in value.items()}

    to_openapi_dict = _get_openapi_to_dict(value)
    if to_openapi_dict is not None:
        return to_openapi_dict(value)

    to_dict = getattr(value, "to_dict", None)
    if callable(to_dict):
        return to_dict()
    return value


class Beta(BaseModel):
    """
    Beta

    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """ # noqa: E501
    active: Optional[StrictBool] = None
    beta_app_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("betaAppId", "beta_app_id"), serialization_alias="betaAppId")
    beta_group_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("betaGroupId", "beta_group_id"), serialization_alias="betaGroupId")
    beta_name: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("betaName", "beta_name"), serialization_alias="betaName")
    created_at: Optional[datetime] = None
    id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["beta_872e10d7-699d-42cb-9e70-2373a9a044e1"]})
    last_synchronized_at: Optional[datetime] = Field(default=None, validation_alias=AliasChoices("lastSynchronizedAt", "last_synchronized_at"), serialization_alias="lastSynchronizedAt")
    type: Optional[StrictStr] = None
    updated_at: Optional[datetime] = None
    user_fields: Optional[Dict[str, BetaUserField]] = Field(default=None, validation_alias=AliasChoices("userFields", "user_fields"), serialization_alias="userFields", description="The fields a registration must supply, keyed by field name.")
    openapi_types: ClassVar[Dict[str, str]] = {
        "active": "bool",
        "beta_app_id": "str",
        "beta_group_id": "str",
        "beta_name": "str",
        "created_at": "datetime",
        "id": "str",
        "last_synchronized_at": "datetime",
        "type": "str",
        "updated_at": "datetime",
        "user_fields": "Dict[str, BetaUserField]"
    }

    attribute_map: ClassVar[Dict[str, str]] = {
        "active": "active",
        "beta_app_id": "betaAppId",
        "beta_group_id": "betaGroupId",
        "beta_name": "betaName",
        "created_at": "created_at",
        "id": "id",
        "last_synchronized_at": "lastSynchronizedAt",
        "type": "type",
        "updated_at": "updated_at",
        "user_fields": "userFields"
    }
    __properties: ClassVar[List[str]] = ["active", "betaAppId", "betaGroupId", "betaName", "created_at", "id", "lastSynchronizedAt", "type", "updated_at", "userFields"]

    @classmethod
    def __preprocess_input_names(
        cls,
        obj: Any,
        remove_hidden_storage_names: bool = True,
    ) -> Any:
        if not isinstance(obj, _Mapping):
            return obj
        obj = dict(obj)
        if "betaAppId" not in obj and "beta_app_id" in obj:
            obj["betaAppId"] = obj["beta_app_id"]
        obj.pop("beta_app_id", None)
        if "betaGroupId" not in obj and "beta_group_id" in obj:
            obj["betaGroupId"] = obj["beta_group_id"]
        obj.pop("beta_group_id", None)
        if "betaName" not in obj and "beta_name" in obj:
            obj["betaName"] = obj["beta_name"]
        obj.pop("beta_name", None)
        if "lastSynchronizedAt" not in obj and "last_synchronized_at" in obj:
            obj["lastSynchronizedAt"] = obj["last_synchronized_at"]
        obj.pop("last_synchronized_at", None)
        if "userFields" not in obj and "user_fields" in obj:
            obj["userFields"] = obj["user_fields"]
        obj.pop("user_fields", None)
        return obj

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        extra="forbid",
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For print and pprint"""
        return self.to_str()

    def __eq__(self, other: object) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, Beta):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other: object) -> bool:
        """Returns true if both objects are not equal"""
        if not isinstance(other, Beta):
            return True

        return not (self == other)


    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        to_openapi_dict = _get_openapi_to_dict(self)
        if to_openapi_dict is not None:
            return json.dumps(to_jsonable_python(to_openapi_dict(self)))
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Beta from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self, serialize: bool = False) -> Dict[str, Any]:
        """Return all declared model fields using public or wire names."""
        return {
            ("active" if serialize else "active"): _to_legacy_value(getattr(self, "active", None), serialize),
            ("betaAppId" if serialize else "beta_app_id"): _to_legacy_value(getattr(self, "beta_app_id", None), serialize),
            ("betaGroupId" if serialize else "beta_group_id"): _to_legacy_value(getattr(self, "beta_group_id", None), serialize),
            ("betaName" if serialize else "beta_name"): _to_legacy_value(getattr(self, "beta_name", None), serialize),
            ("created_at" if serialize else "created_at"): _to_legacy_value(getattr(self, "created_at", None), serialize),
            ("id" if serialize else "id"): _to_legacy_value(getattr(self, "id", None), serialize),
            ("lastSynchronizedAt" if serialize else "last_synchronized_at"): _to_legacy_value(getattr(self, "last_synchronized_at", None), serialize),
            ("type" if serialize else "type"): _to_legacy_value(getattr(self, "type", None), serialize),
            ("updated_at" if serialize else "updated_at"): _to_legacy_value(getattr(self, "updated_at", None), serialize),
            ("userFields" if serialize else "user_fields"): _to_legacy_value(getattr(self, "user_fields", None), serialize),
        }

    def __openapi_generator_modern_projection(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in user_fields (dict)
        _field_dict = {}
        if self.user_fields:
            for _key_user_fields in self.user_fields:
                if self.user_fields[_key_user_fields]:
                    _field_dict[_key_user_fields] = _to_openapi_value(self.user_fields[_key_user_fields])
            _dict['userFields'] = _field_dict
        return _dict

    setattr(
        to_dict,
        _OPENAPI_GENERATOR_TO_DICT,
        __openapi_generator_modern_projection,
    )
    setattr(
        __openapi_generator_modern_projection,
        _OPENAPI_GENERATOR_TO_DICT,
        to_dict,
    )
    del __openapi_generator_modern_projection

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Beta from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        obj = _cast(
            Dict[str, Any],
            cls.__preprocess_input_names(
                obj,
                remove_hidden_storage_names=True,
            ),
        )

        _obj = cls.model_validate({
            "active": obj.get("active"),
            "betaAppId": obj.get("betaAppId"),
            "betaGroupId": obj.get("betaGroupId"),
            "betaName": obj.get("betaName"),
            "created_at": obj.get("created_at"),
            "id": obj.get("id"),
            "lastSynchronizedAt": obj.get("lastSynchronizedAt"),
            "type": obj.get("type"),
            "updated_at": obj.get("updated_at"),
            "userFields": dict(
                (_k, BetaUserField.from_dict(_v))
                for _k, _v in obj["userFields"].items()
            )
            if obj.get("userFields") is not None
            else None
        })
        return _obj


