# coding: utf-8

"""
    VRChat API Documentation


    The version of the OpenAPI document: 1.20.8
    Contact: vrchatapi.lpv0t@aries.fyi
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from collections.abc import Mapping as _Mapping
from pydantic import AliasChoices, BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, cast as _cast
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


_OPENAPI_GENERATOR_TO_DICT = "_openapi_generator_to_dict"


def _get_openapi_to_dict(value: Any) -> Any:
    # Reciprocal function references preserve inherited generated methods
    # without reserving model member names. Checking both directions also
    # rejects overrides whose decorators copy function attributes.
    to_dict = getattr(value, "to_dict", None)
    type_to_dict = getattr(type(value), "to_dict", None)
    if (
        not callable(to_dict)
        or getattr(to_dict, "__func__", None) is not type_to_dict
    ):
        return None

    openapi_to_dict = getattr(
        type_to_dict, _OPENAPI_GENERATOR_TO_DICT, None
    )
    if (
        not callable(openapi_to_dict)
        or getattr(
            openapi_to_dict,
            _OPENAPI_GENERATOR_TO_DICT,
            None,
        ) is not type_to_dict
    ):
        return None
    return openapi_to_dict


def _to_legacy_item(value: Any, serialize: bool) -> Any:
    to_dict = getattr(value, "to_dict", None)
    if _get_openapi_to_dict(value) is not None and callable(to_dict):
        return to_dict(serialize=serialize)
    if callable(to_dict):
        return to_dict()
    return value


def _to_legacy_value(value: Any, serialize: bool) -> Any:
    # python-legacy converted only immediate list elements or dictionary values:
    # https://github.com/OpenAPITools/openapi-generator/blob/c84b949df1a9ec04ba75989cb49b45c940c2f694/modules/openapi-generator/src/main/resources/python-legacy/model.mustache#L203-L231
    if isinstance(value, list):
        return [_to_legacy_item(item, serialize) for item in value]
    if isinstance(value, dict):
        return {
            key: _to_legacy_item(item, serialize)
            for key, item in value.items()
        }
    return _to_legacy_item(value, serialize)


def _to_openapi_value(value: Any) -> Any:
    if isinstance(value, list):
        return [_to_openapi_value(item) for item in value]
    if isinstance(value, dict):
        return {key: _to_openapi_value(item) for key, item in value.items()}

    to_openapi_dict = _get_openapi_to_dict(value)
    if to_openapi_dict is not None:
        return to_openapi_dict(value)

    to_dict = getattr(value, "to_dict", None)
    if callable(to_dict):
        return to_dict()
    return value


class CreateGroupGalleryRequest(BaseModel):
    """
    CreateGroupGalleryRequest

    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """ # noqa: E501
    description: Optional[Annotated[str, Field(min_length=0, strict=True)]] = Field(default=None, description="Description of the gallery.", json_schema_extra={"examples": ["Example Description"]})
    members_only: Optional[StrictBool] = Field(default=False, validation_alias=AliasChoices("membersOnly", "members_only"), serialization_alias="membersOnly", description="Whether the gallery is members only.", json_schema_extra={"examples": [False]})
    name: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, description="Name of the gallery.", json_schema_extra={"examples": ["Example Gallery"]})
    role_ids_to_auto_approve: Optional[List[StrictStr]] = Field(default=None, validation_alias=AliasChoices("roleIdsToAutoApprove", "role_ids_to_auto_approve"), serialization_alias="roleIdsToAutoApprove", description=" ")
    role_ids_to_manage: Optional[List[StrictStr]] = Field(default=None, validation_alias=AliasChoices("roleIdsToManage", "role_ids_to_manage"), serialization_alias="roleIdsToManage", description=" ")
    role_ids_to_submit: Optional[List[StrictStr]] = Field(default=None, validation_alias=AliasChoices("roleIdsToSubmit", "role_ids_to_submit"), serialization_alias="roleIdsToSubmit", description=" ")
    role_ids_to_view: Optional[List[StrictStr]] = Field(default=None, validation_alias=AliasChoices("roleIdsToView", "role_ids_to_view"), serialization_alias="roleIdsToView", description=" ")
    openapi_types: ClassVar[Dict[str, str]] = {
        "description": "str",
        "members_only": "bool",
        "name": "str",
        "role_ids_to_auto_approve": "List[str]",
        "role_ids_to_manage": "List[str]",
        "role_ids_to_submit": "List[str]",
        "role_ids_to_view": "List[str]"
    }

    attribute_map: ClassVar[Dict[str, str]] = {
        "description": "description",
        "members_only": "membersOnly",
        "name": "name",
        "role_ids_to_auto_approve": "roleIdsToAutoApprove",
        "role_ids_to_manage": "roleIdsToManage",
        "role_ids_to_submit": "roleIdsToSubmit",
        "role_ids_to_view": "roleIdsToView"
    }
    __properties: ClassVar[List[str]] = ["description", "membersOnly", "name", "roleIdsToAutoApprove", "roleIdsToManage", "roleIdsToSubmit", "roleIdsToView"]

    @classmethod
    def __preprocess_input_names(
        cls,
        obj: Any,
        remove_hidden_storage_names: bool = True,
    ) -> Any:
        if not isinstance(obj, _Mapping):
            return obj
        obj = dict(obj)
        if "membersOnly" not in obj and "members_only" in obj:
            obj["membersOnly"] = obj["members_only"]
        obj.pop("members_only", None)
        if "roleIdsToAutoApprove" not in obj and "role_ids_to_auto_approve" in obj:
            obj["roleIdsToAutoApprove"] = obj["role_ids_to_auto_approve"]
        obj.pop("role_ids_to_auto_approve", None)
        if "roleIdsToManage" not in obj and "role_ids_to_manage" in obj:
            obj["roleIdsToManage"] = obj["role_ids_to_manage"]
        obj.pop("role_ids_to_manage", None)
        if "roleIdsToSubmit" not in obj and "role_ids_to_submit" in obj:
            obj["roleIdsToSubmit"] = obj["role_ids_to_submit"]
        obj.pop("role_ids_to_submit", None)
        if "roleIdsToView" not in obj and "role_ids_to_view" in obj:
            obj["roleIdsToView"] = obj["role_ids_to_view"]
        obj.pop("role_ids_to_view", None)
        return obj

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        extra="forbid",
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For print and pprint"""
        return self.to_str()

    def __eq__(self, other: object) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateGroupGalleryRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other: object) -> bool:
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateGroupGalleryRequest):
            return True

        return not (self == other)


    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        to_openapi_dict = _get_openapi_to_dict(self)
        if to_openapi_dict is not None:
            return json.dumps(to_jsonable_python(to_openapi_dict(self)))
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateGroupGalleryRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self, serialize: bool = False) -> Dict[str, Any]:
        """Return all declared model fields using public or wire names."""
        return {
            ("description" if serialize else "description"): _to_legacy_value(getattr(self, "description", None), serialize),
            ("membersOnly" if serialize else "members_only"): _to_legacy_value(getattr(self, "members_only", None), serialize),
            ("name" if serialize else "name"): _to_legacy_value(getattr(self, "name", None), serialize),
            ("roleIdsToAutoApprove" if serialize else "role_ids_to_auto_approve"): _to_legacy_value(getattr(self, "role_ids_to_auto_approve", None), serialize),
            ("roleIdsToManage" if serialize else "role_ids_to_manage"): _to_legacy_value(getattr(self, "role_ids_to_manage", None), serialize),
            ("roleIdsToSubmit" if serialize else "role_ids_to_submit"): _to_legacy_value(getattr(self, "role_ids_to_submit", None), serialize),
            ("roleIdsToView" if serialize else "role_ids_to_view"): _to_legacy_value(getattr(self, "role_ids_to_view", None), serialize),
        }

    def __openapi_generator_modern_projection(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if role_ids_to_auto_approve (nullable) is None
        # and model_fields_set contains the field
        if self.role_ids_to_auto_approve is None and "role_ids_to_auto_approve" in self.model_fields_set:
            _dict['roleIdsToAutoApprove'] = None

        # set to None if role_ids_to_manage (nullable) is None
        # and model_fields_set contains the field
        if self.role_ids_to_manage is None and "role_ids_to_manage" in self.model_fields_set:
            _dict['roleIdsToManage'] = None

        # set to None if role_ids_to_submit (nullable) is None
        # and model_fields_set contains the field
        if self.role_ids_to_submit is None and "role_ids_to_submit" in self.model_fields_set:
            _dict['roleIdsToSubmit'] = None

        # set to None if role_ids_to_view (nullable) is None
        # and model_fields_set contains the field
        if self.role_ids_to_view is None and "role_ids_to_view" in self.model_fields_set:
            _dict['roleIdsToView'] = None

        return _dict

    setattr(
        to_dict,
        _OPENAPI_GENERATOR_TO_DICT,
        __openapi_generator_modern_projection,
    )
    setattr(
        __openapi_generator_modern_projection,
        _OPENAPI_GENERATOR_TO_DICT,
        to_dict,
    )
    del __openapi_generator_modern_projection

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateGroupGalleryRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        obj = _cast(
            Dict[str, Any],
            cls.__preprocess_input_names(
                obj,
                remove_hidden_storage_names=True,
            ),
        )

        _obj = cls.model_validate({
            "description": obj.get("description"),
            "membersOnly": obj.get("membersOnly") if obj.get("membersOnly") is not None else False,
            "name": obj.get("name"),
            "roleIdsToAutoApprove": obj.get("roleIdsToAutoApprove"),
            "roleIdsToManage": obj.get("roleIdsToManage"),
            "roleIdsToSubmit": obj.get("roleIdsToSubmit"),
            "roleIdsToView": obj.get("roleIdsToView")
        })
        return _obj


