# coding: utf-8

"""
    VRChat API Documentation


    The version of the OpenAPI document: 1.21.0
    Contact: vrchatapi.lpv0t@aries.fyi
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from collections.abc import Mapping as _Mapping
from pydantic import AliasChoices, BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, cast as _cast
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


_OPENAPI_GENERATOR_TO_DICT = "_openapi_generator_to_dict"


def _get_openapi_to_dict(value: Any) -> Any:
    # Reciprocal function references preserve inherited generated methods
    # without reserving model member names. Checking both directions also
    # rejects overrides whose decorators copy function attributes.
    to_dict = getattr(value, "to_dict", None)
    type_to_dict = getattr(type(value), "to_dict", None)
    if (
        not callable(to_dict)
        or getattr(to_dict, "__func__", None) is not type_to_dict
    ):
        return None

    openapi_to_dict = getattr(
        type_to_dict, _OPENAPI_GENERATOR_TO_DICT, None
    )
    if (
        not callable(openapi_to_dict)
        or getattr(
            openapi_to_dict,
            _OPENAPI_GENERATOR_TO_DICT,
            None,
        ) is not type_to_dict
    ):
        return None
    return openapi_to_dict


def _to_legacy_item(value: Any, serialize: bool) -> Any:
    to_dict = getattr(value, "to_dict", None)
    if _get_openapi_to_dict(value) is not None and callable(to_dict):
        return to_dict(serialize=serialize)
    if callable(to_dict):
        return to_dict()
    return value


def _to_legacy_value(value: Any, serialize: bool) -> Any:
    # python-legacy converted only immediate list elements or dictionary values:
    # https://github.com/OpenAPITools/openapi-generator/blob/c84b949df1a9ec04ba75989cb49b45c940c2f694/modules/openapi-generator/src/main/resources/python-legacy/model.mustache#L203-L231
    if isinstance(value, list):
        return [_to_legacy_item(item, serialize) for item in value]
    if isinstance(value, dict):
        return {
            key: _to_legacy_item(item, serialize)
            for key, item in value.items()
        }
    return _to_legacy_item(value, serialize)


def _to_openapi_value(value: Any) -> Any:
    if isinstance(value, list):
        return [_to_openapi_value(item) for item in value]
    if isinstance(value, dict):
        return {key: _to_openapi_value(item) for key, item in value.items()}

    to_openapi_dict = _get_openapi_to_dict(value)
    if to_openapi_dict is not None:
        return to_openapi_dict(value)

    to_dict = getattr(value, "to_dict", None)
    if callable(to_dict):
        return to_dict()
    return value


class DynamicContentRow(BaseModel):
    """
    DynamicContentRow

    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """ # noqa: E501
    any_style: Optional[List[StrictStr]] = Field(default=None, validation_alias=AliasChoices("anyStyle", "any_style"), serialization_alias="anyStyle")
    any_tag: Optional[List[StrictStr]] = Field(default=None, validation_alias=AliasChoices("anyTag", "any_tag"), serialization_alias="anyTag")
    avatar_specific: Optional[StrictBool] = Field(default=None, validation_alias=AliasChoices("avatarSpecific", "avatar_specific"), serialization_alias="avatarSpecific")
    banners_tag: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("bannersTag", "banners_tag"), serialization_alias="bannersTag")
    categories: Optional[List[StrictStr]] = None
    featured_results: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("featuredResults", "featured_results"), serialization_alias="featuredResults")
    group_pool: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("groupPool", "group_pool"), serialization_alias="groupPool", json_schema_extra={"examples": ["mine"]})
    index: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    marketplace: Optional[StrictStr] = None
    max_price: Optional[StrictInt] = Field(default=None, validation_alias=AliasChoices("maxPrice", "max_price"), serialization_alias="maxPrice")
    min_occupants: Optional[StrictInt] = Field(default=None, validation_alias=AliasChoices("minOccupants", "min_occupants"), serialization_alias="minOccupants")
    min_price: Optional[StrictInt] = Field(default=None, validation_alias=AliasChoices("minPrice", "min_price"), serialization_alias="minPrice")
    minimum_interest_count: Optional[StrictInt] = Field(default=None, validation_alias=AliasChoices("minimumInterestCount", "minimum_interest_count"), serialization_alias="minimumInterestCount")
    minimum_remaining_minutes: Optional[StrictInt] = Field(default=None, validation_alias=AliasChoices("minimumRemainingMinutes", "minimum_remaining_minutes"), serialization_alias="minimumRemainingMinutes")
    mode: Optional[StrictStr] = None
    n: Optional[StrictInt] = None
    name: Optional[Annotated[str, Field(min_length=1, strict=True)]] = None
    non_featured_results: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("nonFeaturedResults", "non_featured_results"), serialization_alias="nonFeaturedResults")
    notag: Optional[List[StrictStr]] = None
    params: Optional[Dict[str, Any]] = None
    personalized_results: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("personalizedResults", "personalized_results"), serialization_alias="personalizedResults", json_schema_extra={"examples": ["include"]})
    platform: Optional[StrictStr] = Field(default=None, description="This is normally `android`, `ios`, `standalonewindows`, `web`, or the empty value ``, but also supposedly can be any random Unity version such as `2019.2.4-801-Release` or `2019.2.2-772-Release` or even `unknownplatform`.", json_schema_extra={"examples": ["standalonewindows"]})
    region: Optional[StrictStr] = None
    scope: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["all"]})
    short_name: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("shortName", "short_name"), serialization_alias="shortName")
    sort_heading: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, validation_alias=AliasChoices("sortHeading", "sort_heading"), serialization_alias="sortHeading")
    sort_order: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, validation_alias=AliasChoices("sortOrder", "sort_order"), serialization_alias="sortOrder")
    sort_ownership: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, validation_alias=AliasChoices("sortOwnership", "sort_ownership"), serialization_alias="sortOwnership")
    style: Optional[StrictStr] = None
    tag: Optional[StrictStr] = Field(default=None, description="Tag to filter content for this row. Not a `Tag`: that type forbids the empty string, which this field uses for a row that is not tag-filtered.", json_schema_extra={"examples": ["admin_spotlight_pc"]})
    tags: Optional[List[Annotated[str, Field(min_length=1, strict=True)]]] = None
    type: Optional[StrictStr] = Field(default=None, description="Type is not present if it is a world.", json_schema_extra={"examples": ["avatar"]})
    upcoming_offset_minutes: Optional[StrictInt] = Field(default=None, validation_alias=AliasChoices("upcomingOffsetMinutes", "upcoming_offset_minutes"), serialization_alias="upcomingOffsetMinutes", json_schema_extra={"examples": [10080]})
    world_pool: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("worldPool", "world_pool"), serialization_alias="worldPool", json_schema_extra={"examples": ["trending"]})
    openapi_types: ClassVar[Dict[str, str]] = {
        "any_style": "List[str]",
        "any_tag": "List[str]",
        "avatar_specific": "bool",
        "banners_tag": "str",
        "categories": "List[str]",
        "featured_results": "str",
        "group_pool": "str",
        "index": "int",
        "marketplace": "str",
        "max_price": "int",
        "min_occupants": "int",
        "min_price": "int",
        "minimum_interest_count": "int",
        "minimum_remaining_minutes": "int",
        "mode": "str",
        "n": "int",
        "name": "str",
        "non_featured_results": "str",
        "notag": "List[str]",
        "params": "Dict[str, object]",
        "personalized_results": "str",
        "platform": "str",
        "region": "str",
        "scope": "str",
        "short_name": "str",
        "sort_heading": "str",
        "sort_order": "str",
        "sort_ownership": "str",
        "style": "str",
        "tag": "str",
        "tags": "List[str]",
        "type": "str",
        "upcoming_offset_minutes": "int",
        "world_pool": "str"
    }

    attribute_map: ClassVar[Dict[str, str]] = {
        "any_style": "anyStyle",
        "any_tag": "anyTag",
        "avatar_specific": "avatarSpecific",
        "banners_tag": "bannersTag",
        "categories": "categories",
        "featured_results": "featuredResults",
        "group_pool": "groupPool",
        "index": "index",
        "marketplace": "marketplace",
        "max_price": "maxPrice",
        "min_occupants": "minOccupants",
        "min_price": "minPrice",
        "minimum_interest_count": "minimumInterestCount",
        "minimum_remaining_minutes": "minimumRemainingMinutes",
        "mode": "mode",
        "n": "n",
        "name": "name",
        "non_featured_results": "nonFeaturedResults",
        "notag": "notag",
        "params": "params",
        "personalized_results": "personalizedResults",
        "platform": "platform",
        "region": "region",
        "scope": "scope",
        "short_name": "shortName",
        "sort_heading": "sortHeading",
        "sort_order": "sortOrder",
        "sort_ownership": "sortOwnership",
        "style": "style",
        "tag": "tag",
        "tags": "tags",
        "type": "type",
        "upcoming_offset_minutes": "upcomingOffsetMinutes",
        "world_pool": "worldPool"
    }
    __properties: ClassVar[List[str]] = ["anyStyle", "anyTag", "avatarSpecific", "bannersTag", "categories", "featuredResults", "groupPool", "index", "marketplace", "maxPrice", "minOccupants", "minPrice", "minimumInterestCount", "minimumRemainingMinutes", "mode", "n", "name", "nonFeaturedResults", "notag", "params", "personalizedResults", "platform", "region", "scope", "shortName", "sortHeading", "sortOrder", "sortOwnership", "style", "tag", "tags", "type", "upcomingOffsetMinutes", "worldPool"]

    @classmethod
    def __preprocess_input_names(
        cls,
        obj: Any,
        remove_hidden_storage_names: bool = True,
    ) -> Any:
        if not isinstance(obj, _Mapping):
            return obj
        obj = dict(obj)
        if "anyStyle" not in obj and "any_style" in obj:
            obj["anyStyle"] = obj["any_style"]
        obj.pop("any_style", None)
        if "anyTag" not in obj and "any_tag" in obj:
            obj["anyTag"] = obj["any_tag"]
        obj.pop("any_tag", None)
        if "avatarSpecific" not in obj and "avatar_specific" in obj:
            obj["avatarSpecific"] = obj["avatar_specific"]
        obj.pop("avatar_specific", None)
        if "bannersTag" not in obj and "banners_tag" in obj:
            obj["bannersTag"] = obj["banners_tag"]
        obj.pop("banners_tag", None)
        if "featuredResults" not in obj and "featured_results" in obj:
            obj["featuredResults"] = obj["featured_results"]
        obj.pop("featured_results", None)
        if "groupPool" not in obj and "group_pool" in obj:
            obj["groupPool"] = obj["group_pool"]
        obj.pop("group_pool", None)
        if "maxPrice" not in obj and "max_price" in obj:
            obj["maxPrice"] = obj["max_price"]
        obj.pop("max_price", None)
        if "minOccupants" not in obj and "min_occupants" in obj:
            obj["minOccupants"] = obj["min_occupants"]
        obj.pop("min_occupants", None)
        if "minPrice" not in obj and "min_price" in obj:
            obj["minPrice"] = obj["min_price"]
        obj.pop("min_price", None)
        if "minimumInterestCount" not in obj and "minimum_interest_count" in obj:
            obj["minimumInterestCount"] = obj["minimum_interest_count"]
        obj.pop("minimum_interest_count", None)
        if "minimumRemainingMinutes" not in obj and "minimum_remaining_minutes" in obj:
            obj["minimumRemainingMinutes"] = obj["minimum_remaining_minutes"]
        obj.pop("minimum_remaining_minutes", None)
        if "nonFeaturedResults" not in obj and "non_featured_results" in obj:
            obj["nonFeaturedResults"] = obj["non_featured_results"]
        obj.pop("non_featured_results", None)
        if "personalizedResults" not in obj and "personalized_results" in obj:
            obj["personalizedResults"] = obj["personalized_results"]
        obj.pop("personalized_results", None)
        if "shortName" not in obj and "short_name" in obj:
            obj["shortName"] = obj["short_name"]
        obj.pop("short_name", None)
        if "sortHeading" not in obj and "sort_heading" in obj:
            obj["sortHeading"] = obj["sort_heading"]
        obj.pop("sort_heading", None)
        if "sortOrder" not in obj and "sort_order" in obj:
            obj["sortOrder"] = obj["sort_order"]
        obj.pop("sort_order", None)
        if "sortOwnership" not in obj and "sort_ownership" in obj:
            obj["sortOwnership"] = obj["sort_ownership"]
        obj.pop("sort_ownership", None)
        if "upcomingOffsetMinutes" not in obj and "upcoming_offset_minutes" in obj:
            obj["upcomingOffsetMinutes"] = obj["upcoming_offset_minutes"]
        obj.pop("upcoming_offset_minutes", None)
        if "worldPool" not in obj and "world_pool" in obj:
            obj["worldPool"] = obj["world_pool"]
        obj.pop("world_pool", None)
        return obj

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        extra="forbid",
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For print and pprint"""
        return self.to_str()

    def __eq__(self, other: object) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, DynamicContentRow):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other: object) -> bool:
        """Returns true if both objects are not equal"""
        if not isinstance(other, DynamicContentRow):
            return True

        return not (self == other)


    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        to_openapi_dict = _get_openapi_to_dict(self)
        if to_openapi_dict is not None:
            return json.dumps(to_jsonable_python(to_openapi_dict(self)))
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DynamicContentRow from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self, serialize: bool = False) -> Dict[str, Any]:
        """Return all declared model fields using public or wire names."""
        return {
            ("anyStyle" if serialize else "any_style"): _to_legacy_value(getattr(self, "any_style", None), serialize),
            ("anyTag" if serialize else "any_tag"): _to_legacy_value(getattr(self, "any_tag", None), serialize),
            ("avatarSpecific" if serialize else "avatar_specific"): _to_legacy_value(getattr(self, "avatar_specific", None), serialize),
            ("bannersTag" if serialize else "banners_tag"): _to_legacy_value(getattr(self, "banners_tag", None), serialize),
            ("categories" if serialize else "categories"): _to_legacy_value(getattr(self, "categories", None), serialize),
            ("featuredResults" if serialize else "featured_results"): _to_legacy_value(getattr(self, "featured_results", None), serialize),
            ("groupPool" if serialize else "group_pool"): _to_legacy_value(getattr(self, "group_pool", None), serialize),
            ("index" if serialize else "index"): _to_legacy_value(getattr(self, "index", None), serialize),
            ("marketplace" if serialize else "marketplace"): _to_legacy_value(getattr(self, "marketplace", None), serialize),
            ("maxPrice" if serialize else "max_price"): _to_legacy_value(getattr(self, "max_price", None), serialize),
            ("minOccupants" if serialize else "min_occupants"): _to_legacy_value(getattr(self, "min_occupants", None), serialize),
            ("minPrice" if serialize else "min_price"): _to_legacy_value(getattr(self, "min_price", None), serialize),
            ("minimumInterestCount" if serialize else "minimum_interest_count"): _to_legacy_value(getattr(self, "minimum_interest_count", None), serialize),
            ("minimumRemainingMinutes" if serialize else "minimum_remaining_minutes"): _to_legacy_value(getattr(self, "minimum_remaining_minutes", None), serialize),
            ("mode" if serialize else "mode"): _to_legacy_value(getattr(self, "mode", None), serialize),
            ("n" if serialize else "n"): _to_legacy_value(getattr(self, "n", None), serialize),
            ("name" if serialize else "name"): _to_legacy_value(getattr(self, "name", None), serialize),
            ("nonFeaturedResults" if serialize else "non_featured_results"): _to_legacy_value(getattr(self, "non_featured_results", None), serialize),
            ("notag" if serialize else "notag"): _to_legacy_value(getattr(self, "notag", None), serialize),
            ("params" if serialize else "params"): _to_legacy_value(getattr(self, "params", None), serialize),
            ("personalizedResults" if serialize else "personalized_results"): _to_legacy_value(getattr(self, "personalized_results", None), serialize),
            ("platform" if serialize else "platform"): _to_legacy_value(getattr(self, "platform", None), serialize),
            ("region" if serialize else "region"): _to_legacy_value(getattr(self, "region", None), serialize),
            ("scope" if serialize else "scope"): _to_legacy_value(getattr(self, "scope", None), serialize),
            ("shortName" if serialize else "short_name"): _to_legacy_value(getattr(self, "short_name", None), serialize),
            ("sortHeading" if serialize else "sort_heading"): _to_legacy_value(getattr(self, "sort_heading", None), serialize),
            ("sortOrder" if serialize else "sort_order"): _to_legacy_value(getattr(self, "sort_order", None), serialize),
            ("sortOwnership" if serialize else "sort_ownership"): _to_legacy_value(getattr(self, "sort_ownership", None), serialize),
            ("style" if serialize else "style"): _to_legacy_value(getattr(self, "style", None), serialize),
            ("tag" if serialize else "tag"): _to_legacy_value(getattr(self, "tag", None), serialize),
            ("tags" if serialize else "tags"): _to_legacy_value(getattr(self, "tags", None), serialize),
            ("type" if serialize else "type"): _to_legacy_value(getattr(self, "type", None), serialize),
            ("upcomingOffsetMinutes" if serialize else "upcoming_offset_minutes"): _to_legacy_value(getattr(self, "upcoming_offset_minutes", None), serialize),
            ("worldPool" if serialize else "world_pool"): _to_legacy_value(getattr(self, "world_pool", None), serialize),
        }

    def __openapi_generator_modern_projection(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if any_style (nullable) is None
        # and model_fields_set contains the field
        if self.any_style is None and "any_style" in self.model_fields_set:
            _dict['anyStyle'] = None

        # set to None if any_tag (nullable) is None
        # and model_fields_set contains the field
        if self.any_tag is None and "any_tag" in self.model_fields_set:
            _dict['anyTag'] = None

        # set to None if notag (nullable) is None
        # and model_fields_set contains the field
        if self.notag is None and "notag" in self.model_fields_set:
            _dict['notag'] = None

        # set to None if region (nullable) is None
        # and model_fields_set contains the field
        if self.region is None and "region" in self.model_fields_set:
            _dict['region'] = None

        # set to None if short_name (nullable) is None
        # and model_fields_set contains the field
        if self.short_name is None and "short_name" in self.model_fields_set:
            _dict['shortName'] = None

        # set to None if style (nullable) is None
        # and model_fields_set contains the field
        if self.style is None and "style" in self.model_fields_set:
            _dict['style'] = None

        # set to None if tag (nullable) is None
        # and model_fields_set contains the field
        if self.tag is None and "tag" in self.model_fields_set:
            _dict['tag'] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict['tags'] = None

        return _dict

    setattr(
        to_dict,
        _OPENAPI_GENERATOR_TO_DICT,
        __openapi_generator_modern_projection,
    )
    setattr(
        __openapi_generator_modern_projection,
        _OPENAPI_GENERATOR_TO_DICT,
        to_dict,
    )
    del __openapi_generator_modern_projection

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DynamicContentRow from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        obj = _cast(
            Dict[str, Any],
            cls.__preprocess_input_names(
                obj,
                remove_hidden_storage_names=True,
            ),
        )

        _obj = cls.model_validate({
            "anyStyle": obj.get("anyStyle"),
            "anyTag": obj.get("anyTag"),
            "avatarSpecific": obj.get("avatarSpecific"),
            "bannersTag": obj.get("bannersTag"),
            "categories": obj.get("categories"),
            "featuredResults": obj.get("featuredResults"),
            "groupPool": obj.get("groupPool"),
            "index": obj.get("index"),
            "marketplace": obj.get("marketplace"),
            "maxPrice": obj.get("maxPrice"),
            "minOccupants": obj.get("minOccupants"),
            "minPrice": obj.get("minPrice"),
            "minimumInterestCount": obj.get("minimumInterestCount"),
            "minimumRemainingMinutes": obj.get("minimumRemainingMinutes"),
            "mode": obj.get("mode"),
            "n": obj.get("n"),
            "name": obj.get("name"),
            "nonFeaturedResults": obj.get("nonFeaturedResults"),
            "notag": obj.get("notag"),
            "params": obj.get("params"),
            "personalizedResults": obj.get("personalizedResults"),
            "platform": obj.get("platform"),
            "region": obj.get("region"),
            "scope": obj.get("scope"),
            "shortName": obj.get("shortName"),
            "sortHeading": obj.get("sortHeading"),
            "sortOrder": obj.get("sortOrder"),
            "sortOwnership": obj.get("sortOwnership"),
            "style": obj.get("style"),
            "tag": obj.get("tag"),
            "tags": obj.get("tags"),
            "type": obj.get("type"),
            "upcomingOffsetMinutes": obj.get("upcomingOffsetMinutes"),
            "worldPool": obj.get("worldPool")
        })
        return _obj


