# coding: utf-8

"""
    VRChat API Documentation


    The version of the OpenAPI document: 1.20.8
    Contact: vrchatapi.lpv0t@aries.fyi
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from collections.abc import Mapping as _Mapping
from pydantic import AliasChoices, BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, cast as _cast
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


_OPENAPI_GENERATOR_TO_DICT = "_openapi_generator_to_dict"


def _get_openapi_to_dict(value: Any) -> Any:
    # Reciprocal function references preserve inherited generated methods
    # without reserving model member names. Checking both directions also
    # rejects overrides whose decorators copy function attributes.
    to_dict = getattr(value, "to_dict", None)
    type_to_dict = getattr(type(value), "to_dict", None)
    if (
        not callable(to_dict)
        or getattr(to_dict, "__func__", None) is not type_to_dict
    ):
        return None

    openapi_to_dict = getattr(
        type_to_dict, _OPENAPI_GENERATOR_TO_DICT, None
    )
    if (
        not callable(openapi_to_dict)
        or getattr(
            openapi_to_dict,
            _OPENAPI_GENERATOR_TO_DICT,
            None,
        ) is not type_to_dict
    ):
        return None
    return openapi_to_dict


def _to_legacy_item(value: Any, serialize: bool) -> Any:
    to_dict = getattr(value, "to_dict", None)
    if _get_openapi_to_dict(value) is not None and callable(to_dict):
        return to_dict(serialize=serialize)
    if callable(to_dict):
        return to_dict()
    return value


def _to_legacy_value(value: Any, serialize: bool) -> Any:
    # python-legacy converted only immediate list elements or dictionary values:
    # https://github.com/OpenAPITools/openapi-generator/blob/c84b949df1a9ec04ba75989cb49b45c940c2f694/modules/openapi-generator/src/main/resources/python-legacy/model.mustache#L203-L231
    if isinstance(value, list):
        return [_to_legacy_item(item, serialize) for item in value]
    if isinstance(value, dict):
        return {
            key: _to_legacy_item(item, serialize)
            for key, item in value.items()
        }
    return _to_legacy_item(value, serialize)


def _to_openapi_value(value: Any) -> Any:
    if isinstance(value, list):
        return [_to_openapi_value(item) for item in value]
    if isinstance(value, dict):
        return {key: _to_openapi_value(item) for key, item in value.items()}

    to_openapi_dict = _get_openapi_to_dict(value)
    if to_openapi_dict is not None:
        return to_openapi_dict(value)

    to_dict = getattr(value, "to_dict", None)
    if callable(to_dict):
        return to_dict()
    return value


class Feedback(BaseModel):
    """
    Feedback

    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """ # noqa: E501
    commenter_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("commenterId", "commenter_id"), serialization_alias="commenterId", description="A users unique ID, usually in the form of `usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469`. Legacy players can have old IDs in the form of `8JoV9XEdpo`. The ID can never be changed.", json_schema_extra={"examples": ["usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469"]})
    commenter_name: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("commenterName", "commenter_name"), serialization_alias="commenterName")
    content_author_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("contentAuthorId", "content_author_id"), serialization_alias="contentAuthorId", description="A users unique ID, usually in the form of `usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469`. Legacy players can have old IDs in the form of `8JoV9XEdpo`. The ID can never be changed.", json_schema_extra={"examples": ["usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469"]})
    content_author_name: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("contentAuthorName", "content_author_name"), serialization_alias="contentAuthorName")
    content_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("contentId", "content_id"), serialization_alias="contentId")
    content_name: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("contentName", "content_name"), serialization_alias="contentName")
    content_type: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("contentType", "content_type"), serialization_alias="contentType")
    content_version: Optional[StrictInt] = Field(default=None, validation_alias=AliasChoices("contentVersion", "content_version"), serialization_alias="contentVersion")
    description: Optional[StrictStr] = None
    id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["feedback_8cffb23a-f961-444e-b496-0196d1c90adb"]})
    reason: Optional[StrictStr] = None
    tags: Optional[List[Annotated[str, Field(min_length=1, strict=True)]]] = None
    type: Optional[StrictStr] = None
    openapi_types: ClassVar[Dict[str, str]] = {
        "commenter_id": "str",
        "commenter_name": "str",
        "content_author_id": "str",
        "content_author_name": "str",
        "content_id": "str",
        "content_name": "str",
        "content_type": "str",
        "content_version": "int",
        "description": "str",
        "id": "str",
        "reason": "str",
        "tags": "List[str]",
        "type": "str"
    }

    attribute_map: ClassVar[Dict[str, str]] = {
        "commenter_id": "commenterId",
        "commenter_name": "commenterName",
        "content_author_id": "contentAuthorId",
        "content_author_name": "contentAuthorName",
        "content_id": "contentId",
        "content_name": "contentName",
        "content_type": "contentType",
        "content_version": "contentVersion",
        "description": "description",
        "id": "id",
        "reason": "reason",
        "tags": "tags",
        "type": "type"
    }
    __properties: ClassVar[List[str]] = ["commenterId", "commenterName", "contentAuthorId", "contentAuthorName", "contentId", "contentName", "contentType", "contentVersion", "description", "id", "reason", "tags", "type"]

    @classmethod
    def __preprocess_input_names(
        cls,
        obj: Any,
        remove_hidden_storage_names: bool = True,
    ) -> Any:
        if not isinstance(obj, _Mapping):
            return obj
        obj = dict(obj)
        if "commenterId" not in obj and "commenter_id" in obj:
            obj["commenterId"] = obj["commenter_id"]
        obj.pop("commenter_id", None)
        if "commenterName" not in obj and "commenter_name" in obj:
            obj["commenterName"] = obj["commenter_name"]
        obj.pop("commenter_name", None)
        if "contentAuthorId" not in obj and "content_author_id" in obj:
            obj["contentAuthorId"] = obj["content_author_id"]
        obj.pop("content_author_id", None)
        if "contentAuthorName" not in obj and "content_author_name" in obj:
            obj["contentAuthorName"] = obj["content_author_name"]
        obj.pop("content_author_name", None)
        if "contentId" not in obj and "content_id" in obj:
            obj["contentId"] = obj["content_id"]
        obj.pop("content_id", None)
        if "contentName" not in obj and "content_name" in obj:
            obj["contentName"] = obj["content_name"]
        obj.pop("content_name", None)
        if "contentType" not in obj and "content_type" in obj:
            obj["contentType"] = obj["content_type"]
        obj.pop("content_type", None)
        if "contentVersion" not in obj and "content_version" in obj:
            obj["contentVersion"] = obj["content_version"]
        obj.pop("content_version", None)
        return obj

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        extra="forbid",
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For print and pprint"""
        return self.to_str()

    def __eq__(self, other: object) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, Feedback):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other: object) -> bool:
        """Returns true if both objects are not equal"""
        if not isinstance(other, Feedback):
            return True

        return not (self == other)


    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        to_openapi_dict = _get_openapi_to_dict(self)
        if to_openapi_dict is not None:
            return json.dumps(to_jsonable_python(to_openapi_dict(self)))
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Feedback from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self, serialize: bool = False) -> Dict[str, Any]:
        """Return all declared model fields using public or wire names."""
        return {
            ("commenterId" if serialize else "commenter_id"): _to_legacy_value(getattr(self, "commenter_id", None), serialize),
            ("commenterName" if serialize else "commenter_name"): _to_legacy_value(getattr(self, "commenter_name", None), serialize),
            ("contentAuthorId" if serialize else "content_author_id"): _to_legacy_value(getattr(self, "content_author_id", None), serialize),
            ("contentAuthorName" if serialize else "content_author_name"): _to_legacy_value(getattr(self, "content_author_name", None), serialize),
            ("contentId" if serialize else "content_id"): _to_legacy_value(getattr(self, "content_id", None), serialize),
            ("contentName" if serialize else "content_name"): _to_legacy_value(getattr(self, "content_name", None), serialize),
            ("contentType" if serialize else "content_type"): _to_legacy_value(getattr(self, "content_type", None), serialize),
            ("contentVersion" if serialize else "content_version"): _to_legacy_value(getattr(self, "content_version", None), serialize),
            ("description" if serialize else "description"): _to_legacy_value(getattr(self, "description", None), serialize),
            ("id" if serialize else "id"): _to_legacy_value(getattr(self, "id", None), serialize),
            ("reason" if serialize else "reason"): _to_legacy_value(getattr(self, "reason", None), serialize),
            ("tags" if serialize else "tags"): _to_legacy_value(getattr(self, "tags", None), serialize),
            ("type" if serialize else "type"): _to_legacy_value(getattr(self, "type", None), serialize),
        }

    def __openapi_generator_modern_projection(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if content_author_name (nullable) is None
        # and model_fields_set contains the field
        if self.content_author_name is None and "content_author_name" in self.model_fields_set:
            _dict['contentAuthorName'] = None

        # set to None if content_version (nullable) is None
        # and model_fields_set contains the field
        if self.content_version is None and "content_version" in self.model_fields_set:
            _dict['contentVersion'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        return _dict

    setattr(
        to_dict,
        _OPENAPI_GENERATOR_TO_DICT,
        __openapi_generator_modern_projection,
    )
    setattr(
        __openapi_generator_modern_projection,
        _OPENAPI_GENERATOR_TO_DICT,
        to_dict,
    )
    del __openapi_generator_modern_projection

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Feedback from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        obj = _cast(
            Dict[str, Any],
            cls.__preprocess_input_names(
                obj,
                remove_hidden_storage_names=True,
            ),
        )

        _obj = cls.model_validate({
            "commenterId": obj.get("commenterId"),
            "commenterName": obj.get("commenterName"),
            "contentAuthorId": obj.get("contentAuthorId"),
            "contentAuthorName": obj.get("contentAuthorName"),
            "contentId": obj.get("contentId"),
            "contentName": obj.get("contentName"),
            "contentType": obj.get("contentType"),
            "contentVersion": obj.get("contentVersion"),
            "description": obj.get("description"),
            "id": obj.get("id"),
            "reason": obj.get("reason"),
            "tags": obj.get("tags"),
            "type": obj.get("type")
        })
        return _obj


