# coding: utf-8

"""
    VRChat API Documentation


    The version of the OpenAPI document: 1.20.8
    Contact: vrchatapi.lpv0t@aries.fyi
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from collections.abc import Mapping as _Mapping
from datetime import datetime
from pydantic import AliasChoices, BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, cast as _cast
from vrchatapi.models.file_analysis_avatar_stats import FileAnalysisAvatarStats
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


_OPENAPI_GENERATOR_TO_DICT = "_openapi_generator_to_dict"


def _get_openapi_to_dict(value: Any) -> Any:
    # Reciprocal function references preserve inherited generated methods
    # without reserving model member names. Checking both directions also
    # rejects overrides whose decorators copy function attributes.
    to_dict = getattr(value, "to_dict", None)
    type_to_dict = getattr(type(value), "to_dict", None)
    if (
        not callable(to_dict)
        or getattr(to_dict, "__func__", None) is not type_to_dict
    ):
        return None

    openapi_to_dict = getattr(
        type_to_dict, _OPENAPI_GENERATOR_TO_DICT, None
    )
    if (
        not callable(openapi_to_dict)
        or getattr(
            openapi_to_dict,
            _OPENAPI_GENERATOR_TO_DICT,
            None,
        ) is not type_to_dict
    ):
        return None
    return openapi_to_dict


def _to_legacy_item(value: Any, serialize: bool) -> Any:
    to_dict = getattr(value, "to_dict", None)
    if _get_openapi_to_dict(value) is not None and callable(to_dict):
        return to_dict(serialize=serialize)
    if callable(to_dict):
        return to_dict()
    return value


def _to_legacy_value(value: Any, serialize: bool) -> Any:
    # python-legacy converted only immediate list elements or dictionary values:
    # https://github.com/OpenAPITools/openapi-generator/blob/c84b949df1a9ec04ba75989cb49b45c940c2f694/modules/openapi-generator/src/main/resources/python-legacy/model.mustache#L203-L231
    if isinstance(value, list):
        return [_to_legacy_item(item, serialize) for item in value]
    if isinstance(value, dict):
        return {
            key: _to_legacy_item(item, serialize)
            for key, item in value.items()
        }
    return _to_legacy_item(value, serialize)


def _to_openapi_value(value: Any) -> Any:
    if isinstance(value, list):
        return [_to_openapi_value(item) for item in value]
    if isinstance(value, dict):
        return {key: _to_openapi_value(item) for key, item in value.items()}

    to_openapi_dict = _get_openapi_to_dict(value)
    if to_openapi_dict is not None:
        return to_openapi_dict(value)

    to_dict = getattr(value, "to_dict", None)
    if callable(to_dict):
        return to_dict()
    return value


class FileAnalysis(BaseModel):
    """
    FileAnalysis

    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """ # noqa: E501
    avatar_stats: Optional[FileAnalysisAvatarStats] = Field(default=None, validation_alias=AliasChoices("avatarStats", "avatar_stats"), serialization_alias="avatarStats")
    created_at: Optional[datetime] = None
    encryption_key: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("encryptionKey", "encryption_key"), serialization_alias="encryptionKey")
    file_size: Optional[StrictInt] = Field(default=None, validation_alias=AliasChoices("fileSize", "file_size"), serialization_alias="fileSize")
    performance_rating: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("performanceRating", "performance_rating"), serialization_alias="performanceRating")
    success: Optional[StrictBool] = None
    uncompressed_size: Optional[StrictInt] = Field(default=None, validation_alias=AliasChoices("uncompressedSize", "uncompressed_size"), serialization_alias="uncompressedSize")
    openapi_types: ClassVar[Dict[str, str]] = {
        "avatar_stats": "FileAnalysisAvatarStats",
        "created_at": "datetime",
        "encryption_key": "str",
        "file_size": "int",
        "performance_rating": "str",
        "success": "bool",
        "uncompressed_size": "int"
    }

    attribute_map: ClassVar[Dict[str, str]] = {
        "avatar_stats": "avatarStats",
        "created_at": "created_at",
        "encryption_key": "encryptionKey",
        "file_size": "fileSize",
        "performance_rating": "performanceRating",
        "success": "success",
        "uncompressed_size": "uncompressedSize"
    }
    __properties: ClassVar[List[str]] = ["avatarStats", "created_at", "encryptionKey", "fileSize", "performanceRating", "success", "uncompressedSize"]

    @classmethod
    def __preprocess_input_names(
        cls,
        obj: Any,
        remove_hidden_storage_names: bool = True,
    ) -> Any:
        if not isinstance(obj, _Mapping):
            return obj
        obj = dict(obj)
        if "avatarStats" not in obj and "avatar_stats" in obj:
            obj["avatarStats"] = obj["avatar_stats"]
        obj.pop("avatar_stats", None)
        if "encryptionKey" not in obj and "encryption_key" in obj:
            obj["encryptionKey"] = obj["encryption_key"]
        obj.pop("encryption_key", None)
        if "fileSize" not in obj and "file_size" in obj:
            obj["fileSize"] = obj["file_size"]
        obj.pop("file_size", None)
        if "performanceRating" not in obj and "performance_rating" in obj:
            obj["performanceRating"] = obj["performance_rating"]
        obj.pop("performance_rating", None)
        if "uncompressedSize" not in obj and "uncompressed_size" in obj:
            obj["uncompressedSize"] = obj["uncompressed_size"]
        obj.pop("uncompressed_size", None)
        return obj

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        extra="forbid",
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For print and pprint"""
        return self.to_str()

    def __eq__(self, other: object) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, FileAnalysis):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other: object) -> bool:
        """Returns true if both objects are not equal"""
        if not isinstance(other, FileAnalysis):
            return True

        return not (self == other)


    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        to_openapi_dict = _get_openapi_to_dict(self)
        if to_openapi_dict is not None:
            return json.dumps(to_jsonable_python(to_openapi_dict(self)))
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FileAnalysis from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self, serialize: bool = False) -> Dict[str, Any]:
        """Return all declared model fields using public or wire names."""
        return {
            ("avatarStats" if serialize else "avatar_stats"): _to_legacy_value(getattr(self, "avatar_stats", None), serialize),
            ("created_at" if serialize else "created_at"): _to_legacy_value(getattr(self, "created_at", None), serialize),
            ("encryptionKey" if serialize else "encryption_key"): _to_legacy_value(getattr(self, "encryption_key", None), serialize),
            ("fileSize" if serialize else "file_size"): _to_legacy_value(getattr(self, "file_size", None), serialize),
            ("performanceRating" if serialize else "performance_rating"): _to_legacy_value(getattr(self, "performance_rating", None), serialize),
            ("success" if serialize else "success"): _to_legacy_value(getattr(self, "success", None), serialize),
            ("uncompressedSize" if serialize else "uncompressed_size"): _to_legacy_value(getattr(self, "uncompressed_size", None), serialize),
        }

    def __openapi_generator_modern_projection(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of avatar_stats
        if self.avatar_stats:
            _dict['avatarStats'] = _to_openapi_value(self.avatar_stats)
        return _dict

    setattr(
        to_dict,
        _OPENAPI_GENERATOR_TO_DICT,
        __openapi_generator_modern_projection,
    )
    setattr(
        __openapi_generator_modern_projection,
        _OPENAPI_GENERATOR_TO_DICT,
        to_dict,
    )
    del __openapi_generator_modern_projection

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FileAnalysis from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        obj = _cast(
            Dict[str, Any],
            cls.__preprocess_input_names(
                obj,
                remove_hidden_storage_names=True,
            ),
        )

        _obj = cls.model_validate({
            "avatarStats": FileAnalysisAvatarStats.from_dict(obj["avatarStats"]) if obj.get("avatarStats") is not None else None,
            "created_at": obj.get("created_at"),
            "encryptionKey": obj.get("encryptionKey"),
            "fileSize": obj.get("fileSize"),
            "performanceRating": obj.get("performanceRating"),
            "success": obj.get("success"),
            "uncompressedSize": obj.get("uncompressedSize")
        })
        return _obj


