# coding: utf-8

"""
    VRChat API Documentation


    The version of the OpenAPI document: 1.20.8
    Contact: vrchatapi.lpv0t@aries.fyi
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from collections.abc import Mapping as _Mapping
from datetime import datetime
from pydantic import AliasChoices, BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, cast as _cast
from typing_extensions import Annotated
from vrchatapi.models.group_access_type import GroupAccessType
from vrchatapi.models.instance_content_settings import InstanceContentSettings
from vrchatapi.models.instance_platforms import InstancePlatforms
from vrchatapi.models.instance_region import InstanceRegion
from vrchatapi.models.instance_type import InstanceType
from vrchatapi.models.limited_user_instance import LimitedUserInstance
from vrchatapi.models.region import Region
from vrchatapi.models.world import World
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


_OPENAPI_GENERATOR_TO_DICT = "_openapi_generator_to_dict"


def _get_openapi_to_dict(value: Any) -> Any:
    # Reciprocal function references preserve inherited generated methods
    # without reserving model member names. Checking both directions also
    # rejects overrides whose decorators copy function attributes.
    to_dict = getattr(value, "to_dict", None)
    type_to_dict = getattr(type(value), "to_dict", None)
    if (
        not callable(to_dict)
        or getattr(to_dict, "__func__", None) is not type_to_dict
    ):
        return None

    openapi_to_dict = getattr(
        type_to_dict, _OPENAPI_GENERATOR_TO_DICT, None
    )
    if (
        not callable(openapi_to_dict)
        or getattr(
            openapi_to_dict,
            _OPENAPI_GENERATOR_TO_DICT,
            None,
        ) is not type_to_dict
    ):
        return None
    return openapi_to_dict


def _to_legacy_item(value: Any, serialize: bool) -> Any:
    to_dict = getattr(value, "to_dict", None)
    if _get_openapi_to_dict(value) is not None and callable(to_dict):
        return to_dict(serialize=serialize)
    if callable(to_dict):
        return to_dict()
    return value


def _to_legacy_value(value: Any, serialize: bool) -> Any:
    # python-legacy converted only immediate list elements or dictionary values:
    # https://github.com/OpenAPITools/openapi-generator/blob/c84b949df1a9ec04ba75989cb49b45c940c2f694/modules/openapi-generator/src/main/resources/python-legacy/model.mustache#L203-L231
    if isinstance(value, list):
        return [_to_legacy_item(item, serialize) for item in value]
    if isinstance(value, dict):
        return {
            key: _to_legacy_item(item, serialize)
            for key, item in value.items()
        }
    return _to_legacy_item(value, serialize)


def _to_openapi_value(value: Any) -> Any:
    if isinstance(value, list):
        return [_to_openapi_value(item) for item in value]
    if isinstance(value, dict):
        return {key: _to_openapi_value(item) for key, item in value.items()}

    to_openapi_dict = _get_openapi_to_dict(value)
    if to_openapi_dict is not None:
        return to_openapi_dict(value)

    to_dict = getattr(value, "to_dict", None)
    if callable(to_dict):
        return to_dict()
    return value


class Instance(BaseModel):
    """
    * `hidden` field is only present if InstanceType is `hidden` aka \"Friends+\", and is instance creator. * `friends` field is only present if InstanceType is `friends` aka \"Friends\", and is instance creator. * `private` field is only present if InstanceType is `private` aka \"Invite\" or \"Invite+\", and is instance creator.

    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """ # noqa: E501
    active: Optional[StrictBool] = Field(default=True, json_schema_extra={"examples": [True]})
    age_gate: Optional[StrictBool] = Field(default=None, validation_alias=AliasChoices("ageGate", "age_gate"), serialization_alias="ageGate")
    calendar_entry_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("calendarEntryId", "calendar_entry_id"), serialization_alias="calendarEntryId")
    can_request_invite: Optional[StrictBool] = Field(default=True, validation_alias=AliasChoices("canRequestInvite", "can_request_invite"), serialization_alias="canRequestInvite", json_schema_extra={"examples": [True]})
    capacity: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, json_schema_extra={"examples": [8]})
    client_number: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, validation_alias=AliasChoices("clientNumber", "client_number"), serialization_alias="clientNumber", description="Always returns \"unknown\".")
    closed_at: Optional[datetime] = Field(default=None, validation_alias=AliasChoices("closedAt", "closed_at"), serialization_alias="closedAt")
    content_settings: Optional[InstanceContentSettings] = Field(default=None, validation_alias=AliasChoices("contentSettings", "content_settings"), serialization_alias="contentSettings")
    creator_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("creatorId", "creator_id"), serialization_alias="creatorId", description="A users unique ID, usually in the form of `usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469`. Legacy players can have old IDs in the form of `8JoV9XEdpo`. The ID can never be changed.", json_schema_extra={"examples": ["usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469"]})
    display_name: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("displayName", "display_name"), serialization_alias="displayName")
    friends: Optional[StrictStr] = Field(default=None, description="A users unique ID, usually in the form of `usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469`. Legacy players can have old IDs in the form of `8JoV9XEdpo`. The ID can never be changed.", json_schema_extra={"examples": ["usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469"]})
    full: Optional[StrictBool] = None
    game_server_version: Optional[StrictInt] = Field(default=None, validation_alias=AliasChoices("gameServerVersion", "game_server_version"), serialization_alias="gameServerVersion")
    group_access_type: Optional[GroupAccessType] = Field(default=GroupAccessType.MEMBERS, validation_alias=AliasChoices("groupAccessType", "group_access_type"), serialization_alias="groupAccessType")
    hard_close: Optional[StrictBool] = Field(default=None, validation_alias=AliasChoices("hardClose", "hard_close"), serialization_alias="hardClose")
    has_capacity_for_you: Optional[StrictBool] = Field(default=None, validation_alias=AliasChoices("hasCapacityForYou", "has_capacity_for_you"), serialization_alias="hasCapacityForYou")
    hidden: Optional[StrictStr] = Field(default=None, description="A users unique ID, usually in the form of `usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469`. Legacy players can have old IDs in the form of `8JoV9XEdpo`. The ID can never be changed.", json_schema_extra={"examples": ["usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469"]})
    id: Optional[StrictStr] = Field(default=None, description="InstanceID can be \"offline\" on User profiles if you are not friends with that user and \"private\" if you are friends and user is in private instance.", json_schema_extra={"examples": ["12345~hidden(usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469)~region(eu)~nonce(27e8414a-59a0-4f3d-af1f-f27557eb49a2)"]})
    instance_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("instanceId", "instance_id"), serialization_alias="instanceId", description="InstanceID can be \"offline\" on User profiles if you are not friends with that user and \"private\" if you are friends and user is in private instance.", json_schema_extra={"examples": ["12345~hidden(usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469)~region(eu)~nonce(27e8414a-59a0-4f3d-af1f-f27557eb49a2)"]})
    instance_persistence_enabled: Optional[StrictBool] = Field(default=None, validation_alias=AliasChoices("instancePersistenceEnabled", "instance_persistence_enabled"), serialization_alias="instancePersistenceEnabled")
    location: Optional[StrictStr] = Field(default=None, description="Represents a unique location, consisting of a world identifier and an instance identifier, or \"offline\" if the user is not on your friends list.", json_schema_extra={"examples": ["wrld_4432ea9b-729c-46e3-8eaf-846aa0a37fdd:12345~hidden(usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469)~region(eu)~nonce(27e8414a-59a0-4f3d-af1f-f27557eb49a2)"]})
    n_users: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, json_schema_extra={"examples": [6]})
    name: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, json_schema_extra={"examples": ["12345"]})
    nonce: Optional[StrictStr] = None
    owner_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("ownerId", "owner_id"), serialization_alias="ownerId", description="A groupId if the instance type is \"group\", null if instance type is public, or a userId otherwise", json_schema_extra={"examples": ["usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469"]})
    permanent: Optional[StrictBool] = None
    photon_region: Optional[Region] = Field(default=None, validation_alias=AliasChoices("photonRegion", "photon_region"), serialization_alias="photonRegion")
    platforms: Optional[InstancePlatforms] = None
    player_persistence_enabled: Optional[StrictBool] = Field(default=None, validation_alias=AliasChoices("playerPersistenceEnabled", "player_persistence_enabled"), serialization_alias="playerPersistenceEnabled")
    private: Optional[StrictStr] = Field(default=None, description="A users unique ID, usually in the form of `usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469`. Legacy players can have old IDs in the form of `8JoV9XEdpo`. The ID can never be changed.", json_schema_extra={"examples": ["usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469"]})
    queue_enabled: Optional[StrictBool] = Field(default=None, validation_alias=AliasChoices("queueEnabled", "queue_enabled"), serialization_alias="queueEnabled")
    queue_size: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, validation_alias=AliasChoices("queueSize", "queue_size"), serialization_alias="queueSize", json_schema_extra={"examples": [6]})
    recommended_capacity: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, validation_alias=AliasChoices("recommendedCapacity", "recommended_capacity"), serialization_alias="recommendedCapacity", json_schema_extra={"examples": [6]})
    region: Optional[InstanceRegion] = None
    role_restricted: Optional[StrictBool] = Field(default=None, validation_alias=AliasChoices("roleRestricted", "role_restricted"), serialization_alias="roleRestricted")
    secure_name: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, validation_alias=AliasChoices("secureName", "secure_name"), serialization_alias="secureName", json_schema_extra={"examples": ["7eavhhng"]})
    short_name: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, validation_alias=AliasChoices("shortName", "short_name"), serialization_alias="shortName", json_schema_extra={"examples": ["02u7yz8j"]})
    strict: Optional[StrictBool] = None
    tags: Optional[List[Annotated[str, Field(min_length=1, strict=True)]]] = Field(default=None, description="The tags array on Instances usually contain the language tags of the people in the instance. ", json_schema_extra={"examples": [["language_eng", "language_jpn", "show_social_rank"]]})
    type: Optional[InstanceType] = None
    user_count: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, validation_alias=AliasChoices("userCount", "user_count"), serialization_alias="userCount", json_schema_extra={"examples": [6]})
    users: Optional[List[LimitedUserInstance]] = Field(default=None, description="The users field is present on instances created by the requesting user.")
    world: Optional[World] = None
    world_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("worldId", "world_id"), serialization_alias="worldId", description="WorldID be \"offline\" on User profiles if you are not friends with that user.", json_schema_extra={"examples": ["wrld_4432ea9b-729c-46e3-8eaf-846aa0a37fdd"]})
    openapi_types: ClassVar[Dict[str, str]] = {
        "active": "bool",
        "age_gate": "bool",
        "calendar_entry_id": "str",
        "can_request_invite": "bool",
        "capacity": "int",
        "client_number": "str",
        "closed_at": "datetime",
        "content_settings": "InstanceContentSettings",
        "creator_id": "str",
        "display_name": "str",
        "friends": "str",
        "full": "bool",
        "game_server_version": "int",
        "group_access_type": "GroupAccessType",
        "hard_close": "bool",
        "has_capacity_for_you": "bool",
        "hidden": "str",
        "id": "str",
        "instance_id": "str",
        "instance_persistence_enabled": "bool",
        "location": "str",
        "n_users": "int",
        "name": "str",
        "nonce": "str",
        "owner_id": "str",
        "permanent": "bool",
        "photon_region": "Region",
        "platforms": "InstancePlatforms",
        "player_persistence_enabled": "bool",
        "private": "str",
        "queue_enabled": "bool",
        "queue_size": "int",
        "recommended_capacity": "int",
        "region": "InstanceRegion",
        "role_restricted": "bool",
        "secure_name": "str",
        "short_name": "str",
        "strict": "bool",
        "tags": "List[str]",
        "type": "InstanceType",
        "user_count": "int",
        "users": "List[LimitedUserInstance]",
        "world": "World",
        "world_id": "str"
    }

    attribute_map: ClassVar[Dict[str, str]] = {
        "active": "active",
        "age_gate": "ageGate",
        "calendar_entry_id": "calendarEntryId",
        "can_request_invite": "canRequestInvite",
        "capacity": "capacity",
        "client_number": "clientNumber",
        "closed_at": "closedAt",
        "content_settings": "contentSettings",
        "creator_id": "creatorId",
        "display_name": "displayName",
        "friends": "friends",
        "full": "full",
        "game_server_version": "gameServerVersion",
        "group_access_type": "groupAccessType",
        "hard_close": "hardClose",
        "has_capacity_for_you": "hasCapacityForYou",
        "hidden": "hidden",
        "id": "id",
        "instance_id": "instanceId",
        "instance_persistence_enabled": "instancePersistenceEnabled",
        "location": "location",
        "n_users": "n_users",
        "name": "name",
        "nonce": "nonce",
        "owner_id": "ownerId",
        "permanent": "permanent",
        "photon_region": "photonRegion",
        "platforms": "platforms",
        "player_persistence_enabled": "playerPersistenceEnabled",
        "private": "private",
        "queue_enabled": "queueEnabled",
        "queue_size": "queueSize",
        "recommended_capacity": "recommendedCapacity",
        "region": "region",
        "role_restricted": "roleRestricted",
        "secure_name": "secureName",
        "short_name": "shortName",
        "strict": "strict",
        "tags": "tags",
        "type": "type",
        "user_count": "userCount",
        "users": "users",
        "world": "world",
        "world_id": "worldId"
    }
    __properties: ClassVar[List[str]] = ["active", "ageGate", "calendarEntryId", "canRequestInvite", "capacity", "clientNumber", "closedAt", "contentSettings", "creatorId", "displayName", "friends", "full", "gameServerVersion", "groupAccessType", "hardClose", "hasCapacityForYou", "hidden", "id", "instanceId", "instancePersistenceEnabled", "location", "n_users", "name", "nonce", "ownerId", "permanent", "photonRegion", "platforms", "playerPersistenceEnabled", "private", "queueEnabled", "queueSize", "recommendedCapacity", "region", "roleRestricted", "secureName", "shortName", "strict", "tags", "type", "userCount", "users", "world", "worldId"]

    @classmethod
    def __preprocess_input_names(
        cls,
        obj: Any,
        remove_hidden_storage_names: bool = True,
    ) -> Any:
        if not isinstance(obj, _Mapping):
            return obj
        obj = dict(obj)
        if "ageGate" not in obj and "age_gate" in obj:
            obj["ageGate"] = obj["age_gate"]
        obj.pop("age_gate", None)
        if "calendarEntryId" not in obj and "calendar_entry_id" in obj:
            obj["calendarEntryId"] = obj["calendar_entry_id"]
        obj.pop("calendar_entry_id", None)
        if "canRequestInvite" not in obj and "can_request_invite" in obj:
            obj["canRequestInvite"] = obj["can_request_invite"]
        obj.pop("can_request_invite", None)
        if "clientNumber" not in obj and "client_number" in obj:
            obj["clientNumber"] = obj["client_number"]
        obj.pop("client_number", None)
        if "closedAt" not in obj and "closed_at" in obj:
            obj["closedAt"] = obj["closed_at"]
        obj.pop("closed_at", None)
        if "contentSettings" not in obj and "content_settings" in obj:
            obj["contentSettings"] = obj["content_settings"]
        obj.pop("content_settings", None)
        if "creatorId" not in obj and "creator_id" in obj:
            obj["creatorId"] = obj["creator_id"]
        obj.pop("creator_id", None)
        if "displayName" not in obj and "display_name" in obj:
            obj["displayName"] = obj["display_name"]
        obj.pop("display_name", None)
        if "gameServerVersion" not in obj and "game_server_version" in obj:
            obj["gameServerVersion"] = obj["game_server_version"]
        obj.pop("game_server_version", None)
        if "groupAccessType" not in obj and "group_access_type" in obj:
            obj["groupAccessType"] = obj["group_access_type"]
        obj.pop("group_access_type", None)
        if "hardClose" not in obj and "hard_close" in obj:
            obj["hardClose"] = obj["hard_close"]
        obj.pop("hard_close", None)
        if "hasCapacityForYou" not in obj and "has_capacity_for_you" in obj:
            obj["hasCapacityForYou"] = obj["has_capacity_for_you"]
        obj.pop("has_capacity_for_you", None)
        if "instanceId" not in obj and "instance_id" in obj:
            obj["instanceId"] = obj["instance_id"]
        obj.pop("instance_id", None)
        if "instancePersistenceEnabled" not in obj and "instance_persistence_enabled" in obj:
            obj["instancePersistenceEnabled"] = obj["instance_persistence_enabled"]
        obj.pop("instance_persistence_enabled", None)
        if "ownerId" not in obj and "owner_id" in obj:
            obj["ownerId"] = obj["owner_id"]
        obj.pop("owner_id", None)
        if "photonRegion" not in obj and "photon_region" in obj:
            obj["photonRegion"] = obj["photon_region"]
        obj.pop("photon_region", None)
        if "playerPersistenceEnabled" not in obj and "player_persistence_enabled" in obj:
            obj["playerPersistenceEnabled"] = obj["player_persistence_enabled"]
        obj.pop("player_persistence_enabled", None)
        if "queueEnabled" not in obj and "queue_enabled" in obj:
            obj["queueEnabled"] = obj["queue_enabled"]
        obj.pop("queue_enabled", None)
        if "queueSize" not in obj and "queue_size" in obj:
            obj["queueSize"] = obj["queue_size"]
        obj.pop("queue_size", None)
        if "recommendedCapacity" not in obj and "recommended_capacity" in obj:
            obj["recommendedCapacity"] = obj["recommended_capacity"]
        obj.pop("recommended_capacity", None)
        if "roleRestricted" not in obj and "role_restricted" in obj:
            obj["roleRestricted"] = obj["role_restricted"]
        obj.pop("role_restricted", None)
        if "secureName" not in obj and "secure_name" in obj:
            obj["secureName"] = obj["secure_name"]
        obj.pop("secure_name", None)
        if "shortName" not in obj and "short_name" in obj:
            obj["shortName"] = obj["short_name"]
        obj.pop("short_name", None)
        if "userCount" not in obj and "user_count" in obj:
            obj["userCount"] = obj["user_count"]
        obj.pop("user_count", None)
        if "worldId" not in obj and "world_id" in obj:
            obj["worldId"] = obj["world_id"]
        obj.pop("world_id", None)
        return obj

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        extra="forbid",
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For print and pprint"""
        return self.to_str()

    def __eq__(self, other: object) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, Instance):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other: object) -> bool:
        """Returns true if both objects are not equal"""
        if not isinstance(other, Instance):
            return True

        return not (self == other)


    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        to_openapi_dict = _get_openapi_to_dict(self)
        if to_openapi_dict is not None:
            return json.dumps(to_jsonable_python(to_openapi_dict(self)))
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Instance from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self, serialize: bool = False) -> Dict[str, Any]:
        """Return all declared model fields using public or wire names."""
        return {
            ("active" if serialize else "active"): _to_legacy_value(getattr(self, "active", None), serialize),
            ("ageGate" if serialize else "age_gate"): _to_legacy_value(getattr(self, "age_gate", None), serialize),
            ("calendarEntryId" if serialize else "calendar_entry_id"): _to_legacy_value(getattr(self, "calendar_entry_id", None), serialize),
            ("canRequestInvite" if serialize else "can_request_invite"): _to_legacy_value(getattr(self, "can_request_invite", None), serialize),
            ("capacity" if serialize else "capacity"): _to_legacy_value(getattr(self, "capacity", None), serialize),
            ("clientNumber" if serialize else "client_number"): _to_legacy_value(getattr(self, "client_number", None), serialize),
            ("closedAt" if serialize else "closed_at"): _to_legacy_value(getattr(self, "closed_at", None), serialize),
            ("contentSettings" if serialize else "content_settings"): _to_legacy_value(getattr(self, "content_settings", None), serialize),
            ("creatorId" if serialize else "creator_id"): _to_legacy_value(getattr(self, "creator_id", None), serialize),
            ("displayName" if serialize else "display_name"): _to_legacy_value(getattr(self, "display_name", None), serialize),
            ("friends" if serialize else "friends"): _to_legacy_value(getattr(self, "friends", None), serialize),
            ("full" if serialize else "full"): _to_legacy_value(getattr(self, "full", None), serialize),
            ("gameServerVersion" if serialize else "game_server_version"): _to_legacy_value(getattr(self, "game_server_version", None), serialize),
            ("groupAccessType" if serialize else "group_access_type"): _to_legacy_value(getattr(self, "group_access_type", None), serialize),
            ("hardClose" if serialize else "hard_close"): _to_legacy_value(getattr(self, "hard_close", None), serialize),
            ("hasCapacityForYou" if serialize else "has_capacity_for_you"): _to_legacy_value(getattr(self, "has_capacity_for_you", None), serialize),
            ("hidden" if serialize else "hidden"): _to_legacy_value(getattr(self, "hidden", None), serialize),
            ("id" if serialize else "id"): _to_legacy_value(getattr(self, "id", None), serialize),
            ("instanceId" if serialize else "instance_id"): _to_legacy_value(getattr(self, "instance_id", None), serialize),
            ("instancePersistenceEnabled" if serialize else "instance_persistence_enabled"): _to_legacy_value(getattr(self, "instance_persistence_enabled", None), serialize),
            ("location" if serialize else "location"): _to_legacy_value(getattr(self, "location", None), serialize),
            ("n_users" if serialize else "n_users"): _to_legacy_value(getattr(self, "n_users", None), serialize),
            ("name" if serialize else "name"): _to_legacy_value(getattr(self, "name", None), serialize),
            ("nonce" if serialize else "nonce"): _to_legacy_value(getattr(self, "nonce", None), serialize),
            ("ownerId" if serialize else "owner_id"): _to_legacy_value(getattr(self, "owner_id", None), serialize),
            ("permanent" if serialize else "permanent"): _to_legacy_value(getattr(self, "permanent", None), serialize),
            ("photonRegion" if serialize else "photon_region"): _to_legacy_value(getattr(self, "photon_region", None), serialize),
            ("platforms" if serialize else "platforms"): _to_legacy_value(getattr(self, "platforms", None), serialize),
            ("playerPersistenceEnabled" if serialize else "player_persistence_enabled"): _to_legacy_value(getattr(self, "player_persistence_enabled", None), serialize),
            ("private" if serialize else "private"): _to_legacy_value(getattr(self, "private", None), serialize),
            ("queueEnabled" if serialize else "queue_enabled"): _to_legacy_value(getattr(self, "queue_enabled", None), serialize),
            ("queueSize" if serialize else "queue_size"): _to_legacy_value(getattr(self, "queue_size", None), serialize),
            ("recommendedCapacity" if serialize else "recommended_capacity"): _to_legacy_value(getattr(self, "recommended_capacity", None), serialize),
            ("region" if serialize else "region"): _to_legacy_value(getattr(self, "region", None), serialize),
            ("roleRestricted" if serialize else "role_restricted"): _to_legacy_value(getattr(self, "role_restricted", None), serialize),
            ("secureName" if serialize else "secure_name"): _to_legacy_value(getattr(self, "secure_name", None), serialize),
            ("shortName" if serialize else "short_name"): _to_legacy_value(getattr(self, "short_name", None), serialize),
            ("strict" if serialize else "strict"): _to_legacy_value(getattr(self, "strict", None), serialize),
            ("tags" if serialize else "tags"): _to_legacy_value(getattr(self, "tags", None), serialize),
            ("type" if serialize else "type"): _to_legacy_value(getattr(self, "type", None), serialize),
            ("userCount" if serialize else "user_count"): _to_legacy_value(getattr(self, "user_count", None), serialize),
            ("users" if serialize else "users"): _to_legacy_value(getattr(self, "users", None), serialize),
            ("world" if serialize else "world"): _to_legacy_value(getattr(self, "world", None), serialize),
            ("worldId" if serialize else "world_id"): _to_legacy_value(getattr(self, "world_id", None), serialize),
        }

    def __openapi_generator_modern_projection(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of content_settings
        if self.content_settings:
            _dict['contentSettings'] = _to_openapi_value(self.content_settings)
        # override the default output from pydantic by calling `to_dict()` of platforms
        if self.platforms:
            _dict['platforms'] = _to_openapi_value(self.platforms)
        # override the default output from pydantic by calling `to_dict()` of each item in users (list)
        _items = []
        if self.users:
            for _item_users in self.users:
                if _item_users:
                    _items.append(_to_openapi_value(_item_users))
            _dict['users'] = _items
        # override the default output from pydantic by calling `to_dict()` of world
        if self.world:
            _dict['world'] = _to_openapi_value(self.world)
        # set to None if age_gate (nullable) is None
        # and model_fields_set contains the field
        if self.age_gate is None and "age_gate" in self.model_fields_set:
            _dict['ageGate'] = None

        # set to None if calendar_entry_id (nullable) is None
        # and model_fields_set contains the field
        if self.calendar_entry_id is None and "calendar_entry_id" in self.model_fields_set:
            _dict['calendarEntryId'] = None

        # set to None if closed_at (nullable) is None
        # and model_fields_set contains the field
        if self.closed_at is None and "closed_at" in self.model_fields_set:
            _dict['closedAt'] = None

        # set to None if display_name (nullable) is None
        # and model_fields_set contains the field
        if self.display_name is None and "display_name" in self.model_fields_set:
            _dict['displayName'] = None

        # set to None if game_server_version (nullable) is None
        # and model_fields_set contains the field
        if self.game_server_version is None and "game_server_version" in self.model_fields_set:
            _dict['gameServerVersion'] = None

        # set to None if hard_close (nullable) is None
        # and model_fields_set contains the field
        if self.hard_close is None and "hard_close" in self.model_fields_set:
            _dict['hardClose'] = None

        # set to None if instance_persistence_enabled (nullable) is None
        # and model_fields_set contains the field
        if self.instance_persistence_enabled is None and "instance_persistence_enabled" in self.model_fields_set:
            _dict['instancePersistenceEnabled'] = None

        # set to None if owner_id (nullable) is None
        # and model_fields_set contains the field
        if self.owner_id is None and "owner_id" in self.model_fields_set:
            _dict['ownerId'] = None

        # set to None if player_persistence_enabled (nullable) is None
        # and model_fields_set contains the field
        if self.player_persistence_enabled is None and "player_persistence_enabled" in self.model_fields_set:
            _dict['playerPersistenceEnabled'] = None

        # set to None if short_name (nullable) is None
        # and model_fields_set contains the field
        if self.short_name is None and "short_name" in self.model_fields_set:
            _dict['shortName'] = None

        return _dict

    setattr(
        to_dict,
        _OPENAPI_GENERATOR_TO_DICT,
        __openapi_generator_modern_projection,
    )
    setattr(
        __openapi_generator_modern_projection,
        _OPENAPI_GENERATOR_TO_DICT,
        to_dict,
    )
    del __openapi_generator_modern_projection

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Instance from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        obj = _cast(
            Dict[str, Any],
            cls.__preprocess_input_names(
                obj,
                remove_hidden_storage_names=True,
            ),
        )

        _obj = cls.model_validate({
            "active": obj.get("active") if obj.get("active") is not None else True,
            "ageGate": obj.get("ageGate"),
            "calendarEntryId": obj.get("calendarEntryId"),
            "canRequestInvite": obj.get("canRequestInvite") if obj.get("canRequestInvite") is not None else True,
            "capacity": obj.get("capacity"),
            "clientNumber": obj.get("clientNumber"),
            "closedAt": obj.get("closedAt"),
            "contentSettings": InstanceContentSettings.from_dict(obj["contentSettings"]) if obj.get("contentSettings") is not None else None,
            "creatorId": obj.get("creatorId"),
            "displayName": obj.get("displayName"),
            "friends": obj.get("friends"),
            "full": obj.get("full") if obj.get("full") is not None else False,
            "gameServerVersion": obj.get("gameServerVersion"),
            "groupAccessType": obj.get("groupAccessType") if obj.get("groupAccessType") is not None else GroupAccessType.MEMBERS,
            "hardClose": obj.get("hardClose"),
            "hasCapacityForYou": obj.get("hasCapacityForYou"),
            "hidden": obj.get("hidden"),
            "id": obj.get("id"),
            "instanceId": obj.get("instanceId"),
            "instancePersistenceEnabled": obj.get("instancePersistenceEnabled"),
            "location": obj.get("location"),
            "n_users": obj.get("n_users"),
            "name": obj.get("name"),
            "nonce": obj.get("nonce"),
            "ownerId": obj.get("ownerId"),
            "permanent": obj.get("permanent") if obj.get("permanent") is not None else False,
            "photonRegion": obj.get("photonRegion") if obj.get("photonRegion") is not None else Region.US,
            "platforms": InstancePlatforms.from_dict(obj["platforms"]) if obj.get("platforms") is not None else None,
            "playerPersistenceEnabled": obj.get("playerPersistenceEnabled"),
            "private": obj.get("private"),
            "queueEnabled": obj.get("queueEnabled"),
            "queueSize": obj.get("queueSize"),
            "recommendedCapacity": obj.get("recommendedCapacity"),
            "region": obj.get("region") if obj.get("region") is not None else InstanceRegion.US,
            "roleRestricted": obj.get("roleRestricted"),
            "secureName": obj.get("secureName"),
            "shortName": obj.get("shortName"),
            "strict": obj.get("strict"),
            "tags": obj.get("tags"),
            "type": obj.get("type"),
            "userCount": obj.get("userCount"),
            "users": [LimitedUserInstance.from_dict(_item) for _item in obj["users"]] if obj.get("users") is not None else None,
            "world": World.from_dict(obj["world"]) if obj.get("world") is not None else None,
            "worldId": obj.get("worldId")
        })
        return _obj


