# coding: utf-8

"""
    VRChat API Documentation


    The version of the OpenAPI document: 1.20.8
    Contact: vrchatapi.lpv0t@aries.fyi
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from collections.abc import Mapping as _Mapping
from datetime import datetime
from pydantic import AliasChoices, BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, cast as _cast
from typing_extensions import Annotated
from vrchatapi.models.invite_message_type import InviteMessageType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


_OPENAPI_GENERATOR_TO_DICT = "_openapi_generator_to_dict"


def _get_openapi_to_dict(value: Any) -> Any:
    # Reciprocal function references preserve inherited generated methods
    # without reserving model member names. Checking both directions also
    # rejects overrides whose decorators copy function attributes.
    to_dict = getattr(value, "to_dict", None)
    type_to_dict = getattr(type(value), "to_dict", None)
    if (
        not callable(to_dict)
        or getattr(to_dict, "__func__", None) is not type_to_dict
    ):
        return None

    openapi_to_dict = getattr(
        type_to_dict, _OPENAPI_GENERATOR_TO_DICT, None
    )
    if (
        not callable(openapi_to_dict)
        or getattr(
            openapi_to_dict,
            _OPENAPI_GENERATOR_TO_DICT,
            None,
        ) is not type_to_dict
    ):
        return None
    return openapi_to_dict


def _to_legacy_item(value: Any, serialize: bool) -> Any:
    to_dict = getattr(value, "to_dict", None)
    if _get_openapi_to_dict(value) is not None and callable(to_dict):
        return to_dict(serialize=serialize)
    if callable(to_dict):
        return to_dict()
    return value


def _to_legacy_value(value: Any, serialize: bool) -> Any:
    # python-legacy converted only immediate list elements or dictionary values:
    # https://github.com/OpenAPITools/openapi-generator/blob/c84b949df1a9ec04ba75989cb49b45c940c2f694/modules/openapi-generator/src/main/resources/python-legacy/model.mustache#L203-L231
    if isinstance(value, list):
        return [_to_legacy_item(item, serialize) for item in value]
    if isinstance(value, dict):
        return {
            key: _to_legacy_item(item, serialize)
            for key, item in value.items()
        }
    return _to_legacy_item(value, serialize)


def _to_openapi_value(value: Any) -> Any:
    if isinstance(value, list):
        return [_to_openapi_value(item) for item in value]
    if isinstance(value, dict):
        return {key: _to_openapi_value(item) for key, item in value.items()}

    to_openapi_dict = _get_openapi_to_dict(value)
    if to_openapi_dict is not None:
        return to_openapi_dict(value)

    to_dict = getattr(value, "to_dict", None)
    if callable(to_dict):
        return to_dict()
    return value


class InviteMessage(BaseModel):
    """
    

    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """ # noqa: E501
    can_be_updated: Optional[StrictBool] = Field(default=None, validation_alias=AliasChoices("canBeUpdated", "can_be_updated"), serialization_alias="canBeUpdated")
    id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["invm_24a1c14d-5e24-48e5-90e3-c3f712420ffa"]})
    message: Optional[Annotated[str, Field(min_length=1, strict=True)]] = None
    message_type: Optional[InviteMessageType] = Field(default=None, validation_alias=AliasChoices("messageType", "message_type"), serialization_alias="messageType")
    remaining_cooldown_minutes: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, validation_alias=AliasChoices("remainingCooldownMinutes", "remaining_cooldown_minutes"), serialization_alias="remainingCooldownMinutes", description="Changes to 60 when updated, although probably server-side configurable.")
    slot: Optional[Annotated[int, Field(le=11, strict=True, ge=0)]] = None
    updated_at: Optional[datetime] = Field(default=None, validation_alias=AliasChoices("updatedAt", "updated_at"), serialization_alias="updatedAt")
    openapi_types: ClassVar[Dict[str, str]] = {
        "can_be_updated": "bool",
        "id": "str",
        "message": "str",
        "message_type": "InviteMessageType",
        "remaining_cooldown_minutes": "int",
        "slot": "int",
        "updated_at": "datetime"
    }

    attribute_map: ClassVar[Dict[str, str]] = {
        "can_be_updated": "canBeUpdated",
        "id": "id",
        "message": "message",
        "message_type": "messageType",
        "remaining_cooldown_minutes": "remainingCooldownMinutes",
        "slot": "slot",
        "updated_at": "updatedAt"
    }
    __properties: ClassVar[List[str]] = ["canBeUpdated", "id", "message", "messageType", "remainingCooldownMinutes", "slot", "updatedAt"]

    @classmethod
    def __preprocess_input_names(
        cls,
        obj: Any,
        remove_hidden_storage_names: bool = True,
    ) -> Any:
        if not isinstance(obj, _Mapping):
            return obj
        obj = dict(obj)
        if "canBeUpdated" not in obj and "can_be_updated" in obj:
            obj["canBeUpdated"] = obj["can_be_updated"]
        obj.pop("can_be_updated", None)
        if "messageType" not in obj and "message_type" in obj:
            obj["messageType"] = obj["message_type"]
        obj.pop("message_type", None)
        if "remainingCooldownMinutes" not in obj and "remaining_cooldown_minutes" in obj:
            obj["remainingCooldownMinutes"] = obj["remaining_cooldown_minutes"]
        obj.pop("remaining_cooldown_minutes", None)
        if "updatedAt" not in obj and "updated_at" in obj:
            obj["updatedAt"] = obj["updated_at"]
        obj.pop("updated_at", None)
        return obj

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        extra="forbid",
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For print and pprint"""
        return self.to_str()

    def __eq__(self, other: object) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, InviteMessage):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other: object) -> bool:
        """Returns true if both objects are not equal"""
        if not isinstance(other, InviteMessage):
            return True

        return not (self == other)


    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        to_openapi_dict = _get_openapi_to_dict(self)
        if to_openapi_dict is not None:
            return json.dumps(to_jsonable_python(to_openapi_dict(self)))
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InviteMessage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self, serialize: bool = False) -> Dict[str, Any]:
        """Return all declared model fields using public or wire names."""
        return {
            ("canBeUpdated" if serialize else "can_be_updated"): _to_legacy_value(getattr(self, "can_be_updated", None), serialize),
            ("id" if serialize else "id"): _to_legacy_value(getattr(self, "id", None), serialize),
            ("message" if serialize else "message"): _to_legacy_value(getattr(self, "message", None), serialize),
            ("messageType" if serialize else "message_type"): _to_legacy_value(getattr(self, "message_type", None), serialize),
            ("remainingCooldownMinutes" if serialize else "remaining_cooldown_minutes"): _to_legacy_value(getattr(self, "remaining_cooldown_minutes", None), serialize),
            ("slot" if serialize else "slot"): _to_legacy_value(getattr(self, "slot", None), serialize),
            ("updatedAt" if serialize else "updated_at"): _to_legacy_value(getattr(self, "updated_at", None), serialize),
        }

    def __openapi_generator_modern_projection(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    setattr(
        to_dict,
        _OPENAPI_GENERATOR_TO_DICT,
        __openapi_generator_modern_projection,
    )
    setattr(
        __openapi_generator_modern_projection,
        _OPENAPI_GENERATOR_TO_DICT,
        to_dict,
    )
    del __openapi_generator_modern_projection

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InviteMessage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        obj = _cast(
            Dict[str, Any],
            cls.__preprocess_input_names(
                obj,
                remove_hidden_storage_names=True,
            ),
        )

        _obj = cls.model_validate({
            "canBeUpdated": obj.get("canBeUpdated") if obj.get("canBeUpdated") is not None else True,
            "id": obj.get("id"),
            "message": obj.get("message"),
            "messageType": obj.get("messageType") if obj.get("messageType") is not None else InviteMessageType.MESSAGE,
            "remainingCooldownMinutes": obj.get("remainingCooldownMinutes") if obj.get("remainingCooldownMinutes") is not None else 0,
            "slot": obj.get("slot"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


