# coding: utf-8

"""
    VRChat API Documentation


    The version of the OpenAPI document: 1.20.8
    Contact: vrchatapi.lpv0t@aries.fyi
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from collections.abc import Mapping as _Mapping
from datetime import datetime
from pydantic import AliasChoices, BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, cast as _cast
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


_OPENAPI_GENERATOR_TO_DICT = "_openapi_generator_to_dict"


def _get_openapi_to_dict(value: Any) -> Any:
    # Reciprocal function references preserve inherited generated methods
    # without reserving model member names. Checking both directions also
    # rejects overrides whose decorators copy function attributes.
    to_dict = getattr(value, "to_dict", None)
    type_to_dict = getattr(type(value), "to_dict", None)
    if (
        not callable(to_dict)
        or getattr(to_dict, "__func__", None) is not type_to_dict
    ):
        return None

    openapi_to_dict = getattr(
        type_to_dict, _OPENAPI_GENERATOR_TO_DICT, None
    )
    if (
        not callable(openapi_to_dict)
        or getattr(
            openapi_to_dict,
            _OPENAPI_GENERATOR_TO_DICT,
            None,
        ) is not type_to_dict
    ):
        return None
    return openapi_to_dict


def _to_legacy_item(value: Any, serialize: bool) -> Any:
    to_dict = getattr(value, "to_dict", None)
    if _get_openapi_to_dict(value) is not None and callable(to_dict):
        return to_dict(serialize=serialize)
    if callable(to_dict):
        return to_dict()
    return value


def _to_legacy_value(value: Any, serialize: bool) -> Any:
    # python-legacy converted only immediate list elements or dictionary values:
    # https://github.com/OpenAPITools/openapi-generator/blob/c84b949df1a9ec04ba75989cb49b45c940c2f694/modules/openapi-generator/src/main/resources/python-legacy/model.mustache#L203-L231
    if isinstance(value, list):
        return [_to_legacy_item(item, serialize) for item in value]
    if isinstance(value, dict):
        return {
            key: _to_legacy_item(item, serialize)
            for key, item in value.items()
        }
    return _to_legacy_item(value, serialize)


def _to_openapi_value(value: Any) -> Any:
    if isinstance(value, list):
        return [_to_openapi_value(item) for item in value]
    if isinstance(value, dict):
        return {key: _to_openapi_value(item) for key, item in value.items()}

    to_openapi_dict = _get_openapi_to_dict(value)
    if to_openapi_dict is not None:
        return to_openapi_dict(value)

    to_dict = getattr(value, "to_dict", None)
    if callable(to_dict):
        return to_dict()
    return value


class JamSubmission(BaseModel):
    """
    

    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """ # noqa: E501
    content_id: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, validation_alias=AliasChoices("contentId", "content_id"), serialization_alias="contentId", description="Either world ID or avatar ID")
    created_at: Optional[datetime] = None
    description: Optional[StrictStr] = None
    id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["jsub_f01f44fa-89fa-443c-ab4c-7fed9245970f"]})
    jam_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("jamId", "jam_id"), serialization_alias="jamId", json_schema_extra={"examples": ["jam_0b7e3f6d-4647-4648-b2a1-1431e76906d9"]})
    rating_score: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, validation_alias=AliasChoices("ratingScore", "rating_score"), serialization_alias="ratingScore")
    submitter_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("submitterId", "submitter_id"), serialization_alias="submitterId", description="A users unique ID, usually in the form of `usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469`. Legacy players can have old IDs in the form of `8JoV9XEdpo`. The ID can never be changed.", json_schema_extra={"examples": ["usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469"]})
    openapi_types: ClassVar[Dict[str, str]] = {
        "content_id": "str",
        "created_at": "datetime",
        "description": "str",
        "id": "str",
        "jam_id": "str",
        "rating_score": "int",
        "submitter_id": "str"
    }

    attribute_map: ClassVar[Dict[str, str]] = {
        "content_id": "contentId",
        "created_at": "created_at",
        "description": "description",
        "id": "id",
        "jam_id": "jamId",
        "rating_score": "ratingScore",
        "submitter_id": "submitterId"
    }
    __properties: ClassVar[List[str]] = ["contentId", "created_at", "description", "id", "jamId", "ratingScore", "submitterId"]

    @classmethod
    def __preprocess_input_names(
        cls,
        obj: Any,
        remove_hidden_storage_names: bool = True,
    ) -> Any:
        if not isinstance(obj, _Mapping):
            return obj
        obj = dict(obj)
        if "contentId" not in obj and "content_id" in obj:
            obj["contentId"] = obj["content_id"]
        obj.pop("content_id", None)
        if "jamId" not in obj and "jam_id" in obj:
            obj["jamId"] = obj["jam_id"]
        obj.pop("jam_id", None)
        if "ratingScore" not in obj and "rating_score" in obj:
            obj["ratingScore"] = obj["rating_score"]
        obj.pop("rating_score", None)
        if "submitterId" not in obj and "submitter_id" in obj:
            obj["submitterId"] = obj["submitter_id"]
        obj.pop("submitter_id", None)
        return obj

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        extra="forbid",
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For print and pprint"""
        return self.to_str()

    def __eq__(self, other: object) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, JamSubmission):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other: object) -> bool:
        """Returns true if both objects are not equal"""
        if not isinstance(other, JamSubmission):
            return True

        return not (self == other)


    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        to_openapi_dict = _get_openapi_to_dict(self)
        if to_openapi_dict is not None:
            return json.dumps(to_jsonable_python(to_openapi_dict(self)))
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JamSubmission from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self, serialize: bool = False) -> Dict[str, Any]:
        """Return all declared model fields using public or wire names."""
        return {
            ("contentId" if serialize else "content_id"): _to_legacy_value(getattr(self, "content_id", None), serialize),
            ("created_at" if serialize else "created_at"): _to_legacy_value(getattr(self, "created_at", None), serialize),
            ("description" if serialize else "description"): _to_legacy_value(getattr(self, "description", None), serialize),
            ("id" if serialize else "id"): _to_legacy_value(getattr(self, "id", None), serialize),
            ("jamId" if serialize else "jam_id"): _to_legacy_value(getattr(self, "jam_id", None), serialize),
            ("ratingScore" if serialize else "rating_score"): _to_legacy_value(getattr(self, "rating_score", None), serialize),
            ("submitterId" if serialize else "submitter_id"): _to_legacy_value(getattr(self, "submitter_id", None), serialize),
        }

    def __openapi_generator_modern_projection(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    setattr(
        to_dict,
        _OPENAPI_GENERATOR_TO_DICT,
        __openapi_generator_modern_projection,
    )
    setattr(
        __openapi_generator_modern_projection,
        _OPENAPI_GENERATOR_TO_DICT,
        to_dict,
    )
    del __openapi_generator_modern_projection

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JamSubmission from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        obj = _cast(
            Dict[str, Any],
            cls.__preprocess_input_names(
                obj,
                remove_hidden_storage_names=True,
            ),
        )

        _obj = cls.model_validate({
            "contentId": obj.get("contentId"),
            "created_at": obj.get("created_at"),
            "description": obj.get("description"),
            "id": obj.get("id"),
            "jamId": obj.get("jamId"),
            "ratingScore": obj.get("ratingScore"),
            "submitterId": obj.get("submitterId")
        })
        return _obj


