# coding: utf-8

"""
    VRChat API Documentation


    The version of the OpenAPI document: 1.20.8
    Contact: vrchatapi.lpv0t@aries.fyi
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from collections.abc import Mapping as _Mapping
from pydantic import AliasChoices, BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, cast as _cast
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


_OPENAPI_GENERATOR_TO_DICT = "_openapi_generator_to_dict"


def _get_openapi_to_dict(value: Any) -> Any:
    # Reciprocal function references preserve inherited generated methods
    # without reserving model member names. Checking both directions also
    # rejects overrides whose decorators copy function attributes.
    to_dict = getattr(value, "to_dict", None)
    type_to_dict = getattr(type(value), "to_dict", None)
    if (
        not callable(to_dict)
        or getattr(to_dict, "__func__", None) is not type_to_dict
    ):
        return None

    openapi_to_dict = getattr(
        type_to_dict, _OPENAPI_GENERATOR_TO_DICT, None
    )
    if (
        not callable(openapi_to_dict)
        or getattr(
            openapi_to_dict,
            _OPENAPI_GENERATOR_TO_DICT,
            None,
        ) is not type_to_dict
    ):
        return None
    return openapi_to_dict


def _to_legacy_item(value: Any, serialize: bool) -> Any:
    to_dict = getattr(value, "to_dict", None)
    if _get_openapi_to_dict(value) is not None and callable(to_dict):
        return to_dict(serialize=serialize)
    if callable(to_dict):
        return to_dict()
    return value


def _to_legacy_value(value: Any, serialize: bool) -> Any:
    # python-legacy converted only immediate list elements or dictionary values:
    # https://github.com/OpenAPITools/openapi-generator/blob/c84b949df1a9ec04ba75989cb49b45c940c2f694/modules/openapi-generator/src/main/resources/python-legacy/model.mustache#L203-L231
    if isinstance(value, list):
        return [_to_legacy_item(item, serialize) for item in value]
    if isinstance(value, dict):
        return {
            key: _to_legacy_item(item, serialize)
            for key, item in value.items()
        }
    return _to_legacy_item(value, serialize)


def _to_openapi_value(value: Any) -> Any:
    if isinstance(value, list):
        return [_to_openapi_value(item) for item in value]
    if isinstance(value, dict):
        return {key: _to_openapi_value(item) for key, item in value.items()}

    to_openapi_dict = _get_openapi_to_dict(value)
    if to_openapi_dict is not None:
        return to_openapi_dict(value)

    to_dict = getattr(value, "to_dict", None)
    if callable(to_dict):
        return to_dict()
    return value


class ModerationReport(BaseModel):
    """
    ModerationReport

    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """ # noqa: E501
    category: Optional[StrictStr] = Field(default=None, description="Valid values are the keys of the object `$.reportOptions[type]` from `GET /config`. Descriptions of these are found at `$.reportCategories[type]`.", json_schema_extra={"examples": ["behavior"]})
    content_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("contentId", "content_id"), serialization_alias="contentId", json_schema_extra={"examples": ["usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469"]})
    content_name: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("contentName", "content_name"), serialization_alias="contentName")
    content_thumbnail_image_url: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("contentThumbnailImageUrl", "content_thumbnail_image_url"), serialization_alias="contentThumbnailImageUrl")
    description: Optional[StrictStr] = Field(default=None, description="The subjective reason for the report", json_schema_extra={"examples": ["iz bulli"]})
    evidence_required: Optional[StrictBool] = Field(default=None, validation_alias=AliasChoices("evidenceRequired", "evidence_required"), serialization_alias="evidenceRequired")
    id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["modReport_a09eb23c-2c62-4ea9-b885-6198f23c5313"]})
    reason: Optional[StrictStr] = Field(default=None, description="Valid values are the strings in the array `$.reportOptions[type][category]` from `GET /config`. Descriptions of these are found at `$.reportReasons[type]`.")
    support_required: Optional[StrictBool] = Field(default=None, validation_alias=AliasChoices("supportRequired", "support_required"), serialization_alias="supportRequired")
    type: Optional[StrictStr] = Field(default=None, description="Valid values are the keys of the object `$.reportOptions` from `GET /config`.", json_schema_extra={"examples": ["user"]})
    openapi_types: ClassVar[Dict[str, str]] = {
        "category": "str",
        "content_id": "str",
        "content_name": "str",
        "content_thumbnail_image_url": "str",
        "description": "str",
        "evidence_required": "bool",
        "id": "str",
        "reason": "str",
        "support_required": "bool",
        "type": "str"
    }

    attribute_map: ClassVar[Dict[str, str]] = {
        "category": "category",
        "content_id": "contentId",
        "content_name": "contentName",
        "content_thumbnail_image_url": "contentThumbnailImageUrl",
        "description": "description",
        "evidence_required": "evidenceRequired",
        "id": "id",
        "reason": "reason",
        "support_required": "supportRequired",
        "type": "type"
    }
    __properties: ClassVar[List[str]] = ["category", "contentId", "contentName", "contentThumbnailImageUrl", "description", "evidenceRequired", "id", "reason", "supportRequired", "type"]

    @classmethod
    def __preprocess_input_names(
        cls,
        obj: Any,
        remove_hidden_storage_names: bool = True,
    ) -> Any:
        if not isinstance(obj, _Mapping):
            return obj
        obj = dict(obj)
        if "contentId" not in obj and "content_id" in obj:
            obj["contentId"] = obj["content_id"]
        obj.pop("content_id", None)
        if "contentName" not in obj and "content_name" in obj:
            obj["contentName"] = obj["content_name"]
        obj.pop("content_name", None)
        if "contentThumbnailImageUrl" not in obj and "content_thumbnail_image_url" in obj:
            obj["contentThumbnailImageUrl"] = obj["content_thumbnail_image_url"]
        obj.pop("content_thumbnail_image_url", None)
        if "evidenceRequired" not in obj and "evidence_required" in obj:
            obj["evidenceRequired"] = obj["evidence_required"]
        obj.pop("evidence_required", None)
        if "supportRequired" not in obj and "support_required" in obj:
            obj["supportRequired"] = obj["support_required"]
        obj.pop("support_required", None)
        return obj

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        extra="forbid",
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For print and pprint"""
        return self.to_str()

    def __eq__(self, other: object) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, ModerationReport):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other: object) -> bool:
        """Returns true if both objects are not equal"""
        if not isinstance(other, ModerationReport):
            return True

        return not (self == other)


    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        to_openapi_dict = _get_openapi_to_dict(self)
        if to_openapi_dict is not None:
            return json.dumps(to_jsonable_python(to_openapi_dict(self)))
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModerationReport from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self, serialize: bool = False) -> Dict[str, Any]:
        """Return all declared model fields using public or wire names."""
        return {
            ("category" if serialize else "category"): _to_legacy_value(getattr(self, "category", None), serialize),
            ("contentId" if serialize else "content_id"): _to_legacy_value(getattr(self, "content_id", None), serialize),
            ("contentName" if serialize else "content_name"): _to_legacy_value(getattr(self, "content_name", None), serialize),
            ("contentThumbnailImageUrl" if serialize else "content_thumbnail_image_url"): _to_legacy_value(getattr(self, "content_thumbnail_image_url", None), serialize),
            ("description" if serialize else "description"): _to_legacy_value(getattr(self, "description", None), serialize),
            ("evidenceRequired" if serialize else "evidence_required"): _to_legacy_value(getattr(self, "evidence_required", None), serialize),
            ("id" if serialize else "id"): _to_legacy_value(getattr(self, "id", None), serialize),
            ("reason" if serialize else "reason"): _to_legacy_value(getattr(self, "reason", None), serialize),
            ("supportRequired" if serialize else "support_required"): _to_legacy_value(getattr(self, "support_required", None), serialize),
            ("type" if serialize else "type"): _to_legacy_value(getattr(self, "type", None), serialize),
        }

    def __openapi_generator_modern_projection(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if content_thumbnail_image_url (nullable) is None
        # and model_fields_set contains the field
        if self.content_thumbnail_image_url is None and "content_thumbnail_image_url" in self.model_fields_set:
            _dict['contentThumbnailImageUrl'] = None

        return _dict

    setattr(
        to_dict,
        _OPENAPI_GENERATOR_TO_DICT,
        __openapi_generator_modern_projection,
    )
    setattr(
        __openapi_generator_modern_projection,
        _OPENAPI_GENERATOR_TO_DICT,
        to_dict,
    )
    del __openapi_generator_modern_projection

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModerationReport from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        obj = _cast(
            Dict[str, Any],
            cls.__preprocess_input_names(
                obj,
                remove_hidden_storage_names=True,
            ),
        )

        _obj = cls.model_validate({
            "category": obj.get("category"),
            "contentId": obj.get("contentId"),
            "contentName": obj.get("contentName"),
            "contentThumbnailImageUrl": obj.get("contentThumbnailImageUrl"),
            "description": obj.get("description"),
            "evidenceRequired": obj.get("evidenceRequired"),
            "id": obj.get("id"),
            "reason": obj.get("reason"),
            "supportRequired": obj.get("supportRequired"),
            "type": obj.get("type")
        })
        return _obj


