# coding: utf-8

"""
    VRChat API Documentation


    The version of the OpenAPI document: 1.20.8
    Contact: vrchatapi.lpv0t@aries.fyi
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from collections.abc import Mapping as _Mapping
from datetime import datetime
from pydantic import AliasChoices, BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, cast as _cast
from vrchatapi.models.notification_v2_details_boop import NotificationV2DetailsBoop
from vrchatapi.models.notification_v2_response import NotificationV2Response
from vrchatapi.models.notification_v2_type import NotificationV2Type
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


_OPENAPI_GENERATOR_TO_DICT = "_openapi_generator_to_dict"


def _get_openapi_to_dict(value: Any) -> Any:
    # Reciprocal function references preserve inherited generated methods
    # without reserving model member names. Checking both directions also
    # rejects overrides whose decorators copy function attributes.
    to_dict = getattr(value, "to_dict", None)
    type_to_dict = getattr(type(value), "to_dict", None)
    if (
        not callable(to_dict)
        or getattr(to_dict, "__func__", None) is not type_to_dict
    ):
        return None

    openapi_to_dict = getattr(
        type_to_dict, _OPENAPI_GENERATOR_TO_DICT, None
    )
    if (
        not callable(openapi_to_dict)
        or getattr(
            openapi_to_dict,
            _OPENAPI_GENERATOR_TO_DICT,
            None,
        ) is not type_to_dict
    ):
        return None
    return openapi_to_dict


def _to_legacy_item(value: Any, serialize: bool) -> Any:
    to_dict = getattr(value, "to_dict", None)
    if _get_openapi_to_dict(value) is not None and callable(to_dict):
        return to_dict(serialize=serialize)
    if callable(to_dict):
        return to_dict()
    return value


def _to_legacy_value(value: Any, serialize: bool) -> Any:
    # python-legacy converted only immediate list elements or dictionary values:
    # https://github.com/OpenAPITools/openapi-generator/blob/c84b949df1a9ec04ba75989cb49b45c940c2f694/modules/openapi-generator/src/main/resources/python-legacy/model.mustache#L203-L231
    if isinstance(value, list):
        return [_to_legacy_item(item, serialize) for item in value]
    if isinstance(value, dict):
        return {
            key: _to_legacy_item(item, serialize)
            for key, item in value.items()
        }
    return _to_legacy_item(value, serialize)


def _to_openapi_value(value: Any) -> Any:
    if isinstance(value, list):
        return [_to_openapi_value(item) for item in value]
    if isinstance(value, dict):
        return {key: _to_openapi_value(item) for key, item in value.items()}

    to_openapi_dict = _get_openapi_to_dict(value)
    if to_openapi_dict is not None:
        return to_openapi_dict(value)

    to_dict = getattr(value, "to_dict", None)
    if callable(to_dict):
        return to_dict()
    return value


class NotificationV2(BaseModel):
    """
    

    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """ # noqa: E501
    can_delete: Optional[StrictBool] = Field(default=None, validation_alias=AliasChoices("canDelete", "can_delete"), serialization_alias="canDelete")
    category: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["Event:\n  value: event\nGroup:\n  value: social.group\n"]})
    created_at: Optional[datetime] = Field(default=None, validation_alias=AliasChoices("createdAt", "created_at"), serialization_alias="createdAt")
    data: Optional[Dict[str, StrictStr]] = None
    details: Optional[NotificationV2DetailsBoop] = None
    expires_at: Optional[datetime] = Field(default=None, validation_alias=AliasChoices("expiresAt", "expires_at"), serialization_alias="expiresAt")
    expiry_after_seen: Optional[StrictInt] = Field(default=None, validation_alias=AliasChoices("expiryAfterSeen", "expiry_after_seen"), serialization_alias="expiryAfterSeen")
    id: Optional[StrictStr] = None
    ignore_dnd: Optional[StrictBool] = Field(default=None, validation_alias=AliasChoices("ignoreDND", "ignore_dnd"), serialization_alias="ignoreDND")
    image_url: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("imageUrl", "image_url"), serialization_alias="imageUrl")
    is_system: Optional[StrictBool] = Field(default=None, validation_alias=AliasChoices("isSystem", "is_system"), serialization_alias="isSystem")
    link: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["event:grp_00000000-0000-0000-0000-000000000000,cal_00000000-0000-0000-0000-000000000000"]})
    link_text: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("linkText", "link_text"), serialization_alias="linkText")
    link_text_key: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("linkTextKey", "link_text_key"), serialization_alias="linkTextKey")
    message: Optional[StrictStr] = None
    message_key: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("messageKey", "message_key"), serialization_alias="messageKey")
    receiver_user_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("receiverUserId", "receiver_user_id"), serialization_alias="receiverUserId", description="A users unique ID, usually in the form of `usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469`. Legacy players can have old IDs in the form of `8JoV9XEdpo`. The ID can never be changed.", json_schema_extra={"examples": ["usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469"]})
    related_notifications_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("relatedNotificationsId", "related_notifications_id"), serialization_alias="relatedNotificationsId", json_schema_extra={"examples": ["cal_00000000-0000-0000-0000-000000000000"]})
    require_seen: Optional[StrictBool] = Field(default=None, validation_alias=AliasChoices("requireSeen", "require_seen"), serialization_alias="requireSeen")
    responses: Optional[List[NotificationV2Response]] = None
    seen: Optional[StrictBool] = None
    sender_user_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("senderUserId", "sender_user_id"), serialization_alias="senderUserId", description="A users unique ID, usually in the form of `usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469`. Legacy players can have old IDs in the form of `8JoV9XEdpo`. The ID can never be changed.", json_schema_extra={"examples": ["usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469"]})
    sender_username: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("senderUsername", "sender_username"), serialization_alias="senderUsername")
    title: Optional[StrictStr] = None
    title_key: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("titleKey", "title_key"), serialization_alias="titleKey")
    type: Optional[NotificationV2Type] = None
    updated_at: Optional[datetime] = Field(default=None, validation_alias=AliasChoices("updatedAt", "updated_at"), serialization_alias="updatedAt")
    version: Optional[StrictInt] = None
    openapi_types: ClassVar[Dict[str, str]] = {
        "can_delete": "bool",
        "category": "str",
        "created_at": "datetime",
        "data": "Dict[str, str]",
        "details": "NotificationV2DetailsBoop",
        "expires_at": "datetime",
        "expiry_after_seen": "int",
        "id": "str",
        "ignore_dnd": "bool",
        "image_url": "str",
        "is_system": "bool",
        "link": "str",
        "link_text": "str",
        "link_text_key": "str",
        "message": "str",
        "message_key": "str",
        "receiver_user_id": "str",
        "related_notifications_id": "str",
        "require_seen": "bool",
        "responses": "List[NotificationV2Response]",
        "seen": "bool",
        "sender_user_id": "str",
        "sender_username": "str",
        "title": "str",
        "title_key": "str",
        "type": "NotificationV2Type",
        "updated_at": "datetime",
        "version": "int"
    }

    attribute_map: ClassVar[Dict[str, str]] = {
        "can_delete": "canDelete",
        "category": "category",
        "created_at": "createdAt",
        "data": "data",
        "details": "details",
        "expires_at": "expiresAt",
        "expiry_after_seen": "expiryAfterSeen",
        "id": "id",
        "ignore_dnd": "ignoreDND",
        "image_url": "imageUrl",
        "is_system": "isSystem",
        "link": "link",
        "link_text": "linkText",
        "link_text_key": "linkTextKey",
        "message": "message",
        "message_key": "messageKey",
        "receiver_user_id": "receiverUserId",
        "related_notifications_id": "relatedNotificationsId",
        "require_seen": "requireSeen",
        "responses": "responses",
        "seen": "seen",
        "sender_user_id": "senderUserId",
        "sender_username": "senderUsername",
        "title": "title",
        "title_key": "titleKey",
        "type": "type",
        "updated_at": "updatedAt",
        "version": "version"
    }
    __properties: ClassVar[List[str]] = ["canDelete", "category", "createdAt", "data", "details", "expiresAt", "expiryAfterSeen", "id", "ignoreDND", "imageUrl", "isSystem", "link", "linkText", "linkTextKey", "message", "messageKey", "receiverUserId", "relatedNotificationsId", "requireSeen", "responses", "seen", "senderUserId", "senderUsername", "title", "titleKey", "type", "updatedAt", "version"]

    @classmethod
    def __preprocess_input_names(
        cls,
        obj: Any,
        remove_hidden_storage_names: bool = True,
    ) -> Any:
        if not isinstance(obj, _Mapping):
            return obj
        obj = dict(obj)
        if "canDelete" not in obj and "can_delete" in obj:
            obj["canDelete"] = obj["can_delete"]
        obj.pop("can_delete", None)
        if "createdAt" not in obj and "created_at" in obj:
            obj["createdAt"] = obj["created_at"]
        obj.pop("created_at", None)
        if "expiresAt" not in obj and "expires_at" in obj:
            obj["expiresAt"] = obj["expires_at"]
        obj.pop("expires_at", None)
        if "expiryAfterSeen" not in obj and "expiry_after_seen" in obj:
            obj["expiryAfterSeen"] = obj["expiry_after_seen"]
        obj.pop("expiry_after_seen", None)
        if "ignoreDND" not in obj and "ignore_dnd" in obj:
            obj["ignoreDND"] = obj["ignore_dnd"]
        obj.pop("ignore_dnd", None)
        if "imageUrl" not in obj and "image_url" in obj:
            obj["imageUrl"] = obj["image_url"]
        obj.pop("image_url", None)
        if "isSystem" not in obj and "is_system" in obj:
            obj["isSystem"] = obj["is_system"]
        obj.pop("is_system", None)
        if "linkText" not in obj and "link_text" in obj:
            obj["linkText"] = obj["link_text"]
        obj.pop("link_text", None)
        if "linkTextKey" not in obj and "link_text_key" in obj:
            obj["linkTextKey"] = obj["link_text_key"]
        obj.pop("link_text_key", None)
        if "messageKey" not in obj and "message_key" in obj:
            obj["messageKey"] = obj["message_key"]
        obj.pop("message_key", None)
        if "receiverUserId" not in obj and "receiver_user_id" in obj:
            obj["receiverUserId"] = obj["receiver_user_id"]
        obj.pop("receiver_user_id", None)
        if "relatedNotificationsId" not in obj and "related_notifications_id" in obj:
            obj["relatedNotificationsId"] = obj["related_notifications_id"]
        obj.pop("related_notifications_id", None)
        if "requireSeen" not in obj and "require_seen" in obj:
            obj["requireSeen"] = obj["require_seen"]
        obj.pop("require_seen", None)
        if "senderUserId" not in obj and "sender_user_id" in obj:
            obj["senderUserId"] = obj["sender_user_id"]
        obj.pop("sender_user_id", None)
        if "senderUsername" not in obj and "sender_username" in obj:
            obj["senderUsername"] = obj["sender_username"]
        obj.pop("sender_username", None)
        if "titleKey" not in obj and "title_key" in obj:
            obj["titleKey"] = obj["title_key"]
        obj.pop("title_key", None)
        if "updatedAt" not in obj and "updated_at" in obj:
            obj["updatedAt"] = obj["updated_at"]
        obj.pop("updated_at", None)
        return obj

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        extra="forbid",
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For print and pprint"""
        return self.to_str()

    def __eq__(self, other: object) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, NotificationV2):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other: object) -> bool:
        """Returns true if both objects are not equal"""
        if not isinstance(other, NotificationV2):
            return True

        return not (self == other)


    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        to_openapi_dict = _get_openapi_to_dict(self)
        if to_openapi_dict is not None:
            return json.dumps(to_jsonable_python(to_openapi_dict(self)))
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NotificationV2 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self, serialize: bool = False) -> Dict[str, Any]:
        """Return all declared model fields using public or wire names."""
        return {
            ("canDelete" if serialize else "can_delete"): _to_legacy_value(getattr(self, "can_delete", None), serialize),
            ("category" if serialize else "category"): _to_legacy_value(getattr(self, "category", None), serialize),
            ("createdAt" if serialize else "created_at"): _to_legacy_value(getattr(self, "created_at", None), serialize),
            ("data" if serialize else "data"): _to_legacy_value(getattr(self, "data", None), serialize),
            ("details" if serialize else "details"): _to_legacy_value(getattr(self, "details", None), serialize),
            ("expiresAt" if serialize else "expires_at"): _to_legacy_value(getattr(self, "expires_at", None), serialize),
            ("expiryAfterSeen" if serialize else "expiry_after_seen"): _to_legacy_value(getattr(self, "expiry_after_seen", None), serialize),
            ("id" if serialize else "id"): _to_legacy_value(getattr(self, "id", None), serialize),
            ("ignoreDND" if serialize else "ignore_dnd"): _to_legacy_value(getattr(self, "ignore_dnd", None), serialize),
            ("imageUrl" if serialize else "image_url"): _to_legacy_value(getattr(self, "image_url", None), serialize),
            ("isSystem" if serialize else "is_system"): _to_legacy_value(getattr(self, "is_system", None), serialize),
            ("link" if serialize else "link"): _to_legacy_value(getattr(self, "link", None), serialize),
            ("linkText" if serialize else "link_text"): _to_legacy_value(getattr(self, "link_text", None), serialize),
            ("linkTextKey" if serialize else "link_text_key"): _to_legacy_value(getattr(self, "link_text_key", None), serialize),
            ("message" if serialize else "message"): _to_legacy_value(getattr(self, "message", None), serialize),
            ("messageKey" if serialize else "message_key"): _to_legacy_value(getattr(self, "message_key", None), serialize),
            ("receiverUserId" if serialize else "receiver_user_id"): _to_legacy_value(getattr(self, "receiver_user_id", None), serialize),
            ("relatedNotificationsId" if serialize else "related_notifications_id"): _to_legacy_value(getattr(self, "related_notifications_id", None), serialize),
            ("requireSeen" if serialize else "require_seen"): _to_legacy_value(getattr(self, "require_seen", None), serialize),
            ("responses" if serialize else "responses"): _to_legacy_value(getattr(self, "responses", None), serialize),
            ("seen" if serialize else "seen"): _to_legacy_value(getattr(self, "seen", None), serialize),
            ("senderUserId" if serialize else "sender_user_id"): _to_legacy_value(getattr(self, "sender_user_id", None), serialize),
            ("senderUsername" if serialize else "sender_username"): _to_legacy_value(getattr(self, "sender_username", None), serialize),
            ("title" if serialize else "title"): _to_legacy_value(getattr(self, "title", None), serialize),
            ("titleKey" if serialize else "title_key"): _to_legacy_value(getattr(self, "title_key", None), serialize),
            ("type" if serialize else "type"): _to_legacy_value(getattr(self, "type", None), serialize),
            ("updatedAt" if serialize else "updated_at"): _to_legacy_value(getattr(self, "updated_at", None), serialize),
            ("version" if serialize else "version"): _to_legacy_value(getattr(self, "version", None), serialize),
        }

    def __openapi_generator_modern_projection(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of details
        if self.details:
            _dict['details'] = _to_openapi_value(self.details)
        # override the default output from pydantic by calling `to_dict()` of each item in responses (list)
        _items = []
        if self.responses:
            for _item_responses in self.responses:
                if _item_responses:
                    _items.append(_to_openapi_value(_item_responses))
            _dict['responses'] = _items
        # set to None if expiry_after_seen (nullable) is None
        # and model_fields_set contains the field
        if self.expiry_after_seen is None and "expiry_after_seen" in self.model_fields_set:
            _dict['expiryAfterSeen'] = None

        # set to None if image_url (nullable) is None
        # and model_fields_set contains the field
        if self.image_url is None and "image_url" in self.model_fields_set:
            _dict['imageUrl'] = None

        # set to None if link_text_key (nullable) is None
        # and model_fields_set contains the field
        if self.link_text_key is None and "link_text_key" in self.model_fields_set:
            _dict['linkTextKey'] = None

        # set to None if message_key (nullable) is None
        # and model_fields_set contains the field
        if self.message_key is None and "message_key" in self.model_fields_set:
            _dict['messageKey'] = None

        # set to None if related_notifications_id (nullable) is None
        # and model_fields_set contains the field
        if self.related_notifications_id is None and "related_notifications_id" in self.model_fields_set:
            _dict['relatedNotificationsId'] = None

        # set to None if sender_username (nullable) is None
        # and model_fields_set contains the field
        if self.sender_username is None and "sender_username" in self.model_fields_set:
            _dict['senderUsername'] = None

        # set to None if title_key (nullable) is None
        # and model_fields_set contains the field
        if self.title_key is None and "title_key" in self.model_fields_set:
            _dict['titleKey'] = None

        return _dict

    setattr(
        to_dict,
        _OPENAPI_GENERATOR_TO_DICT,
        __openapi_generator_modern_projection,
    )
    setattr(
        __openapi_generator_modern_projection,
        _OPENAPI_GENERATOR_TO_DICT,
        to_dict,
    )
    del __openapi_generator_modern_projection

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NotificationV2 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        obj = _cast(
            Dict[str, Any],
            cls.__preprocess_input_names(
                obj,
                remove_hidden_storage_names=True,
            ),
        )

        _obj = cls.model_validate({
            "canDelete": obj.get("canDelete"),
            "category": obj.get("category"),
            "createdAt": obj.get("createdAt"),
            "data": obj.get("data"),
            "details": NotificationV2DetailsBoop.from_dict(obj["details"]) if obj.get("details") is not None else None,
            "expiresAt": obj.get("expiresAt"),
            "expiryAfterSeen": obj.get("expiryAfterSeen"),
            "id": obj.get("id"),
            "ignoreDND": obj.get("ignoreDND"),
            "imageUrl": obj.get("imageUrl"),
            "isSystem": obj.get("isSystem"),
            "link": obj.get("link"),
            "linkText": obj.get("linkText"),
            "linkTextKey": obj.get("linkTextKey"),
            "message": obj.get("message"),
            "messageKey": obj.get("messageKey"),
            "receiverUserId": obj.get("receiverUserId"),
            "relatedNotificationsId": obj.get("relatedNotificationsId"),
            "requireSeen": obj.get("requireSeen"),
            "responses": [NotificationV2Response.from_dict(_item) for _item in obj["responses"]] if obj.get("responses") is not None else None,
            "seen": obj.get("seen"),
            "senderUserId": obj.get("senderUserId"),
            "senderUsername": obj.get("senderUsername"),
            "title": obj.get("title"),
            "titleKey": obj.get("titleKey"),
            "type": obj.get("type") if obj.get("type") is not None else NotificationV2Type.GROUP_DOT_ANNOUNCEMENT,
            "updatedAt": obj.get("updatedAt"),
            "version": obj.get("version") if obj.get("version") is not None else 2
        })
        return _obj


