# coding: utf-8

"""
    VRChat API Documentation


    The version of the OpenAPI document: 1.20.8
    Contact: vrchatapi.lpv0t@aries.fyi
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from collections.abc import Mapping as _Mapping
from datetime import datetime
from pydantic import AliasChoices, BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, cast as _cast
from vrchatapi.models.product_listing_type import ProductListingType
from vrchatapi.models.product_purchase_product import ProductPurchaseProduct
from vrchatapi.models.product_purchase_purchase_context import ProductPurchasePurchaseContext
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


_OPENAPI_GENERATOR_TO_DICT = "_openapi_generator_to_dict"


def _get_openapi_to_dict(value: Any) -> Any:
    # Reciprocal function references preserve inherited generated methods
    # without reserving model member names. Checking both directions also
    # rejects overrides whose decorators copy function attributes.
    to_dict = getattr(value, "to_dict", None)
    type_to_dict = getattr(type(value), "to_dict", None)
    if (
        not callable(to_dict)
        or getattr(to_dict, "__func__", None) is not type_to_dict
    ):
        return None

    openapi_to_dict = getattr(
        type_to_dict, _OPENAPI_GENERATOR_TO_DICT, None
    )
    if (
        not callable(openapi_to_dict)
        or getattr(
            openapi_to_dict,
            _OPENAPI_GENERATOR_TO_DICT,
            None,
        ) is not type_to_dict
    ):
        return None
    return openapi_to_dict


def _to_legacy_item(value: Any, serialize: bool) -> Any:
    to_dict = getattr(value, "to_dict", None)
    if _get_openapi_to_dict(value) is not None and callable(to_dict):
        return to_dict(serialize=serialize)
    if callable(to_dict):
        return to_dict()
    return value


def _to_legacy_value(value: Any, serialize: bool) -> Any:
    # python-legacy converted only immediate list elements or dictionary values:
    # https://github.com/OpenAPITools/openapi-generator/blob/c84b949df1a9ec04ba75989cb49b45c940c2f694/modules/openapi-generator/src/main/resources/python-legacy/model.mustache#L203-L231
    if isinstance(value, list):
        return [_to_legacy_item(item, serialize) for item in value]
    if isinstance(value, dict):
        return {
            key: _to_legacy_item(item, serialize)
            for key, item in value.items()
        }
    return _to_legacy_item(value, serialize)


def _to_openapi_value(value: Any) -> Any:
    if isinstance(value, list):
        return [_to_openapi_value(item) for item in value]
    if isinstance(value, dict):
        return {key: _to_openapi_value(item) for key, item in value.items()}

    to_openapi_dict = _get_openapi_to_dict(value)
    if to_openapi_dict is not None:
        return to_openapi_dict(value)

    to_dict = getattr(value, "to_dict", None)
    if callable(to_dict):
        return to_dict()
    return value


class ProductPurchase(BaseModel):
    """
    ProductPurchase

    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """ # noqa: E501
    buyer_display_name: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("buyerDisplayName", "buyer_display_name"), serialization_alias="buyerDisplayName")
    buyer_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("buyerId", "buyer_id"), serialization_alias="buyerId", description="A users unique ID, usually in the form of `usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469`. Legacy players can have old IDs in the form of `8JoV9XEdpo`. The ID can never be changed.", json_schema_extra={"examples": ["usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469"]})
    first_party: Optional[StrictBool] = Field(default=None, validation_alias=AliasChoices("firstParty", "first_party"), serialization_alias="firstParty")
    is_buyer: Optional[StrictBool] = Field(default=None, validation_alias=AliasChoices("isBuyer", "is_buyer"), serialization_alias="isBuyer")
    is_gift: Optional[StrictBool] = Field(default=None, validation_alias=AliasChoices("isGift", "is_gift"), serialization_alias="isGift")
    is_receiver: Optional[StrictBool] = Field(default=None, validation_alias=AliasChoices("isReceiver", "is_receiver"), serialization_alias="isReceiver")
    is_seller: Optional[StrictBool] = Field(default=None, validation_alias=AliasChoices("isSeller", "is_seller"), serialization_alias="isSeller")
    ledger_transaction_id: Optional[StrictInt] = Field(default=None, validation_alias=AliasChoices("ledgerTransactionId", "ledger_transaction_id"), serialization_alias="ledgerTransactionId")
    listing_currently_available: Optional[StrictBool] = Field(default=None, validation_alias=AliasChoices("listingCurrentlyAvailable", "listing_currently_available"), serialization_alias="listingCurrentlyAvailable")
    listing_description: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("listingDescription", "listing_description"), serialization_alias="listingDescription")
    listing_display_name: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("listingDisplayName", "listing_display_name"), serialization_alias="listingDisplayName")
    listing_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("listingId", "listing_id"), serialization_alias="listingId", json_schema_extra={"examples": ["prod_bfbc2315-247a-44d7-bfea-5237f8d56cb4"]})
    listing_image_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("listingImageId", "listing_image_id"), serialization_alias="listingImageId", json_schema_extra={"examples": ["file_ce35d830-e20a-4df0-a6d4-5aaef4508044"]})
    listing_subtitle: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("listingSubtitle", "listing_subtitle"), serialization_alias="listingSubtitle")
    listing_type: Optional[ProductListingType] = Field(default=None, validation_alias=AliasChoices("listingType", "listing_type"), serialization_alias="listingType")
    products: Optional[List[ProductPurchaseProduct]] = None
    purchase_active: Optional[StrictBool] = Field(default=None, validation_alias=AliasChoices("purchaseActive", "purchase_active"), serialization_alias="purchaseActive")
    purchase_context: Optional[ProductPurchasePurchaseContext] = Field(default=None, validation_alias=AliasChoices("purchaseContext", "purchase_context"), serialization_alias="purchaseContext")
    purchase_current_status: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("purchaseCurrentStatus", "purchase_current_status"), serialization_alias="purchaseCurrentStatus")
    purchase_date: Optional[datetime] = Field(default=None, validation_alias=AliasChoices("purchaseDate", "purchase_date"), serialization_alias="purchaseDate")
    purchase_duration: Optional[StrictInt] = Field(default=None, validation_alias=AliasChoices("purchaseDuration", "purchase_duration"), serialization_alias="purchaseDuration")
    purchase_duration_type: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("purchaseDurationType", "purchase_duration_type"), serialization_alias="purchaseDurationType")
    purchase_end_date: Optional[datetime] = Field(default=None, validation_alias=AliasChoices("purchaseEndDate", "purchase_end_date"), serialization_alias="purchaseEndDate")
    purchase_fee: Optional[StrictInt] = Field(default=None, validation_alias=AliasChoices("purchaseFee", "purchase_fee"), serialization_alias="purchaseFee")
    purchase_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("purchaseId", "purchase_id"), serialization_alias="purchaseId", json_schema_extra={"examples": ["pur_f0446b91-e0f7-403e-8932-609d5057898c"]})
    purchase_latest: Optional[StrictBool] = Field(default=None, validation_alias=AliasChoices("purchaseLatest", "purchase_latest"), serialization_alias="purchaseLatest")
    purchase_price: Optional[StrictInt] = Field(default=None, validation_alias=AliasChoices("purchasePrice", "purchase_price"), serialization_alias="purchasePrice")
    purchase_quantity: Optional[StrictInt] = Field(default=None, validation_alias=AliasChoices("purchaseQuantity", "purchase_quantity"), serialization_alias="purchaseQuantity")
    purchase_start_date: Optional[datetime] = Field(default=None, validation_alias=AliasChoices("purchaseStartDate", "purchase_start_date"), serialization_alias="purchaseStartDate")
    purchase_token: Optional[Dict[str, Any]] = Field(default=None, validation_alias=AliasChoices("purchaseToken", "purchase_token"), serialization_alias="purchaseToken")
    purchase_type: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("purchaseType", "purchase_type"), serialization_alias="purchaseType")
    purchase_unit_price: Optional[StrictInt] = Field(default=None, validation_alias=AliasChoices("purchaseUnitPrice", "purchase_unit_price"), serialization_alias="purchaseUnitPrice")
    purchase_value: Optional[StrictInt] = Field(default=None, validation_alias=AliasChoices("purchaseValue", "purchase_value"), serialization_alias="purchaseValue")
    receiver_display_name: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("receiverDisplayName", "receiver_display_name"), serialization_alias="receiverDisplayName")
    receiver_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("receiverId", "receiver_id"), serialization_alias="receiverId", description="A users unique ID, usually in the form of `usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469`. Legacy players can have old IDs in the form of `8JoV9XEdpo`. The ID can never be changed.", json_schema_extra={"examples": ["usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469"]})
    recurrable: Optional[StrictBool] = None
    refundable: Optional[StrictBool] = None
    seller_display_name: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("sellerDisplayName", "seller_display_name"), serialization_alias="sellerDisplayName")
    seller_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("sellerId", "seller_id"), serialization_alias="sellerId", description="A users unique ID, usually in the form of `usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469`. Legacy players can have old IDs in the form of `8JoV9XEdpo`. The ID can never be changed.", json_schema_extra={"examples": ["usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469"]})
    stackable: Optional[StrictBool] = None
    will_recur: Optional[StrictBool] = Field(default=None, validation_alias=AliasChoices("willRecur", "will_recur"), serialization_alias="willRecur")
    openapi_types: ClassVar[Dict[str, str]] = {
        "buyer_display_name": "str",
        "buyer_id": "str",
        "first_party": "bool",
        "is_buyer": "bool",
        "is_gift": "bool",
        "is_receiver": "bool",
        "is_seller": "bool",
        "ledger_transaction_id": "int",
        "listing_currently_available": "bool",
        "listing_description": "str",
        "listing_display_name": "str",
        "listing_id": "str",
        "listing_image_id": "str",
        "listing_subtitle": "str",
        "listing_type": "ProductListingType",
        "products": "List[ProductPurchaseProduct]",
        "purchase_active": "bool",
        "purchase_context": "ProductPurchasePurchaseContext",
        "purchase_current_status": "str",
        "purchase_date": "datetime",
        "purchase_duration": "int",
        "purchase_duration_type": "str",
        "purchase_end_date": "datetime",
        "purchase_fee": "int",
        "purchase_id": "str",
        "purchase_latest": "bool",
        "purchase_price": "int",
        "purchase_quantity": "int",
        "purchase_start_date": "datetime",
        "purchase_token": "object",
        "purchase_type": "str",
        "purchase_unit_price": "int",
        "purchase_value": "int",
        "receiver_display_name": "str",
        "receiver_id": "str",
        "recurrable": "bool",
        "refundable": "bool",
        "seller_display_name": "str",
        "seller_id": "str",
        "stackable": "bool",
        "will_recur": "bool"
    }

    attribute_map: ClassVar[Dict[str, str]] = {
        "buyer_display_name": "buyerDisplayName",
        "buyer_id": "buyerId",
        "first_party": "firstParty",
        "is_buyer": "isBuyer",
        "is_gift": "isGift",
        "is_receiver": "isReceiver",
        "is_seller": "isSeller",
        "ledger_transaction_id": "ledgerTransactionId",
        "listing_currently_available": "listingCurrentlyAvailable",
        "listing_description": "listingDescription",
        "listing_display_name": "listingDisplayName",
        "listing_id": "listingId",
        "listing_image_id": "listingImageId",
        "listing_subtitle": "listingSubtitle",
        "listing_type": "listingType",
        "products": "products",
        "purchase_active": "purchaseActive",
        "purchase_context": "purchaseContext",
        "purchase_current_status": "purchaseCurrentStatus",
        "purchase_date": "purchaseDate",
        "purchase_duration": "purchaseDuration",
        "purchase_duration_type": "purchaseDurationType",
        "purchase_end_date": "purchaseEndDate",
        "purchase_fee": "purchaseFee",
        "purchase_id": "purchaseId",
        "purchase_latest": "purchaseLatest",
        "purchase_price": "purchasePrice",
        "purchase_quantity": "purchaseQuantity",
        "purchase_start_date": "purchaseStartDate",
        "purchase_token": "purchaseToken",
        "purchase_type": "purchaseType",
        "purchase_unit_price": "purchaseUnitPrice",
        "purchase_value": "purchaseValue",
        "receiver_display_name": "receiverDisplayName",
        "receiver_id": "receiverId",
        "recurrable": "recurrable",
        "refundable": "refundable",
        "seller_display_name": "sellerDisplayName",
        "seller_id": "sellerId",
        "stackable": "stackable",
        "will_recur": "willRecur"
    }
    __properties: ClassVar[List[str]] = ["buyerDisplayName", "buyerId", "firstParty", "isBuyer", "isGift", "isReceiver", "isSeller", "ledgerTransactionId", "listingCurrentlyAvailable", "listingDescription", "listingDisplayName", "listingId", "listingImageId", "listingSubtitle", "listingType", "products", "purchaseActive", "purchaseContext", "purchaseCurrentStatus", "purchaseDate", "purchaseDuration", "purchaseDurationType", "purchaseEndDate", "purchaseFee", "purchaseId", "purchaseLatest", "purchasePrice", "purchaseQuantity", "purchaseStartDate", "purchaseToken", "purchaseType", "purchaseUnitPrice", "purchaseValue", "receiverDisplayName", "receiverId", "recurrable", "refundable", "sellerDisplayName", "sellerId", "stackable", "willRecur"]

    @classmethod
    def __preprocess_input_names(
        cls,
        obj: Any,
        remove_hidden_storage_names: bool = True,
    ) -> Any:
        if not isinstance(obj, _Mapping):
            return obj
        obj = dict(obj)
        if "buyerDisplayName" not in obj and "buyer_display_name" in obj:
            obj["buyerDisplayName"] = obj["buyer_display_name"]
        obj.pop("buyer_display_name", None)
        if "buyerId" not in obj and "buyer_id" in obj:
            obj["buyerId"] = obj["buyer_id"]
        obj.pop("buyer_id", None)
        if "firstParty" not in obj and "first_party" in obj:
            obj["firstParty"] = obj["first_party"]
        obj.pop("first_party", None)
        if "isBuyer" not in obj and "is_buyer" in obj:
            obj["isBuyer"] = obj["is_buyer"]
        obj.pop("is_buyer", None)
        if "isGift" not in obj and "is_gift" in obj:
            obj["isGift"] = obj["is_gift"]
        obj.pop("is_gift", None)
        if "isReceiver" not in obj and "is_receiver" in obj:
            obj["isReceiver"] = obj["is_receiver"]
        obj.pop("is_receiver", None)
        if "isSeller" not in obj and "is_seller" in obj:
            obj["isSeller"] = obj["is_seller"]
        obj.pop("is_seller", None)
        if "ledgerTransactionId" not in obj and "ledger_transaction_id" in obj:
            obj["ledgerTransactionId"] = obj["ledger_transaction_id"]
        obj.pop("ledger_transaction_id", None)
        if "listingCurrentlyAvailable" not in obj and "listing_currently_available" in obj:
            obj["listingCurrentlyAvailable"] = obj["listing_currently_available"]
        obj.pop("listing_currently_available", None)
        if "listingDescription" not in obj and "listing_description" in obj:
            obj["listingDescription"] = obj["listing_description"]
        obj.pop("listing_description", None)
        if "listingDisplayName" not in obj and "listing_display_name" in obj:
            obj["listingDisplayName"] = obj["listing_display_name"]
        obj.pop("listing_display_name", None)
        if "listingId" not in obj and "listing_id" in obj:
            obj["listingId"] = obj["listing_id"]
        obj.pop("listing_id", None)
        if "listingImageId" not in obj and "listing_image_id" in obj:
            obj["listingImageId"] = obj["listing_image_id"]
        obj.pop("listing_image_id", None)
        if "listingSubtitle" not in obj and "listing_subtitle" in obj:
            obj["listingSubtitle"] = obj["listing_subtitle"]
        obj.pop("listing_subtitle", None)
        if "listingType" not in obj and "listing_type" in obj:
            obj["listingType"] = obj["listing_type"]
        obj.pop("listing_type", None)
        if "purchaseActive" not in obj and "purchase_active" in obj:
            obj["purchaseActive"] = obj["purchase_active"]
        obj.pop("purchase_active", None)
        if "purchaseContext" not in obj and "purchase_context" in obj:
            obj["purchaseContext"] = obj["purchase_context"]
        obj.pop("purchase_context", None)
        if "purchaseCurrentStatus" not in obj and "purchase_current_status" in obj:
            obj["purchaseCurrentStatus"] = obj["purchase_current_status"]
        obj.pop("purchase_current_status", None)
        if "purchaseDate" not in obj and "purchase_date" in obj:
            obj["purchaseDate"] = obj["purchase_date"]
        obj.pop("purchase_date", None)
        if "purchaseDuration" not in obj and "purchase_duration" in obj:
            obj["purchaseDuration"] = obj["purchase_duration"]
        obj.pop("purchase_duration", None)
        if "purchaseDurationType" not in obj and "purchase_duration_type" in obj:
            obj["purchaseDurationType"] = obj["purchase_duration_type"]
        obj.pop("purchase_duration_type", None)
        if "purchaseEndDate" not in obj and "purchase_end_date" in obj:
            obj["purchaseEndDate"] = obj["purchase_end_date"]
        obj.pop("purchase_end_date", None)
        if "purchaseFee" not in obj and "purchase_fee" in obj:
            obj["purchaseFee"] = obj["purchase_fee"]
        obj.pop("purchase_fee", None)
        if "purchaseId" not in obj and "purchase_id" in obj:
            obj["purchaseId"] = obj["purchase_id"]
        obj.pop("purchase_id", None)
        if "purchaseLatest" not in obj and "purchase_latest" in obj:
            obj["purchaseLatest"] = obj["purchase_latest"]
        obj.pop("purchase_latest", None)
        if "purchasePrice" not in obj and "purchase_price" in obj:
            obj["purchasePrice"] = obj["purchase_price"]
        obj.pop("purchase_price", None)
        if "purchaseQuantity" not in obj and "purchase_quantity" in obj:
            obj["purchaseQuantity"] = obj["purchase_quantity"]
        obj.pop("purchase_quantity", None)
        if "purchaseStartDate" not in obj and "purchase_start_date" in obj:
            obj["purchaseStartDate"] = obj["purchase_start_date"]
        obj.pop("purchase_start_date", None)
        if "purchaseToken" not in obj and "purchase_token" in obj:
            obj["purchaseToken"] = obj["purchase_token"]
        obj.pop("purchase_token", None)
        if "purchaseType" not in obj and "purchase_type" in obj:
            obj["purchaseType"] = obj["purchase_type"]
        obj.pop("purchase_type", None)
        if "purchaseUnitPrice" not in obj and "purchase_unit_price" in obj:
            obj["purchaseUnitPrice"] = obj["purchase_unit_price"]
        obj.pop("purchase_unit_price", None)
        if "purchaseValue" not in obj and "purchase_value" in obj:
            obj["purchaseValue"] = obj["purchase_value"]
        obj.pop("purchase_value", None)
        if "receiverDisplayName" not in obj and "receiver_display_name" in obj:
            obj["receiverDisplayName"] = obj["receiver_display_name"]
        obj.pop("receiver_display_name", None)
        if "receiverId" not in obj and "receiver_id" in obj:
            obj["receiverId"] = obj["receiver_id"]
        obj.pop("receiver_id", None)
        if "sellerDisplayName" not in obj and "seller_display_name" in obj:
            obj["sellerDisplayName"] = obj["seller_display_name"]
        obj.pop("seller_display_name", None)
        if "sellerId" not in obj and "seller_id" in obj:
            obj["sellerId"] = obj["seller_id"]
        obj.pop("seller_id", None)
        if "willRecur" not in obj and "will_recur" in obj:
            obj["willRecur"] = obj["will_recur"]
        obj.pop("will_recur", None)
        return obj

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        extra="forbid",
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For print and pprint"""
        return self.to_str()

    def __eq__(self, other: object) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, ProductPurchase):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other: object) -> bool:
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProductPurchase):
            return True

        return not (self == other)


    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        to_openapi_dict = _get_openapi_to_dict(self)
        if to_openapi_dict is not None:
            return json.dumps(to_jsonable_python(to_openapi_dict(self)))
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProductPurchase from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self, serialize: bool = False) -> Dict[str, Any]:
        """Return all declared model fields using public or wire names."""
        return {
            ("buyerDisplayName" if serialize else "buyer_display_name"): _to_legacy_value(getattr(self, "buyer_display_name", None), serialize),
            ("buyerId" if serialize else "buyer_id"): _to_legacy_value(getattr(self, "buyer_id", None), serialize),
            ("firstParty" if serialize else "first_party"): _to_legacy_value(getattr(self, "first_party", None), serialize),
            ("isBuyer" if serialize else "is_buyer"): _to_legacy_value(getattr(self, "is_buyer", None), serialize),
            ("isGift" if serialize else "is_gift"): _to_legacy_value(getattr(self, "is_gift", None), serialize),
            ("isReceiver" if serialize else "is_receiver"): _to_legacy_value(getattr(self, "is_receiver", None), serialize),
            ("isSeller" if serialize else "is_seller"): _to_legacy_value(getattr(self, "is_seller", None), serialize),
            ("ledgerTransactionId" if serialize else "ledger_transaction_id"): _to_legacy_value(getattr(self, "ledger_transaction_id", None), serialize),
            ("listingCurrentlyAvailable" if serialize else "listing_currently_available"): _to_legacy_value(getattr(self, "listing_currently_available", None), serialize),
            ("listingDescription" if serialize else "listing_description"): _to_legacy_value(getattr(self, "listing_description", None), serialize),
            ("listingDisplayName" if serialize else "listing_display_name"): _to_legacy_value(getattr(self, "listing_display_name", None), serialize),
            ("listingId" if serialize else "listing_id"): _to_legacy_value(getattr(self, "listing_id", None), serialize),
            ("listingImageId" if serialize else "listing_image_id"): _to_legacy_value(getattr(self, "listing_image_id", None), serialize),
            ("listingSubtitle" if serialize else "listing_subtitle"): _to_legacy_value(getattr(self, "listing_subtitle", None), serialize),
            ("listingType" if serialize else "listing_type"): _to_legacy_value(getattr(self, "listing_type", None), serialize),
            ("products" if serialize else "products"): _to_legacy_value(getattr(self, "products", None), serialize),
            ("purchaseActive" if serialize else "purchase_active"): _to_legacy_value(getattr(self, "purchase_active", None), serialize),
            ("purchaseContext" if serialize else "purchase_context"): _to_legacy_value(getattr(self, "purchase_context", None), serialize),
            ("purchaseCurrentStatus" if serialize else "purchase_current_status"): _to_legacy_value(getattr(self, "purchase_current_status", None), serialize),
            ("purchaseDate" if serialize else "purchase_date"): _to_legacy_value(getattr(self, "purchase_date", None), serialize),
            ("purchaseDuration" if serialize else "purchase_duration"): _to_legacy_value(getattr(self, "purchase_duration", None), serialize),
            ("purchaseDurationType" if serialize else "purchase_duration_type"): _to_legacy_value(getattr(self, "purchase_duration_type", None), serialize),
            ("purchaseEndDate" if serialize else "purchase_end_date"): _to_legacy_value(getattr(self, "purchase_end_date", None), serialize),
            ("purchaseFee" if serialize else "purchase_fee"): _to_legacy_value(getattr(self, "purchase_fee", None), serialize),
            ("purchaseId" if serialize else "purchase_id"): _to_legacy_value(getattr(self, "purchase_id", None), serialize),
            ("purchaseLatest" if serialize else "purchase_latest"): _to_legacy_value(getattr(self, "purchase_latest", None), serialize),
            ("purchasePrice" if serialize else "purchase_price"): _to_legacy_value(getattr(self, "purchase_price", None), serialize),
            ("purchaseQuantity" if serialize else "purchase_quantity"): _to_legacy_value(getattr(self, "purchase_quantity", None), serialize),
            ("purchaseStartDate" if serialize else "purchase_start_date"): _to_legacy_value(getattr(self, "purchase_start_date", None), serialize),
            ("purchaseToken" if serialize else "purchase_token"): _to_legacy_value(getattr(self, "purchase_token", None), serialize),
            ("purchaseType" if serialize else "purchase_type"): _to_legacy_value(getattr(self, "purchase_type", None), serialize),
            ("purchaseUnitPrice" if serialize else "purchase_unit_price"): _to_legacy_value(getattr(self, "purchase_unit_price", None), serialize),
            ("purchaseValue" if serialize else "purchase_value"): _to_legacy_value(getattr(self, "purchase_value", None), serialize),
            ("receiverDisplayName" if serialize else "receiver_display_name"): _to_legacy_value(getattr(self, "receiver_display_name", None), serialize),
            ("receiverId" if serialize else "receiver_id"): _to_legacy_value(getattr(self, "receiver_id", None), serialize),
            ("recurrable" if serialize else "recurrable"): _to_legacy_value(getattr(self, "recurrable", None), serialize),
            ("refundable" if serialize else "refundable"): _to_legacy_value(getattr(self, "refundable", None), serialize),
            ("sellerDisplayName" if serialize else "seller_display_name"): _to_legacy_value(getattr(self, "seller_display_name", None), serialize),
            ("sellerId" if serialize else "seller_id"): _to_legacy_value(getattr(self, "seller_id", None), serialize),
            ("stackable" if serialize else "stackable"): _to_legacy_value(getattr(self, "stackable", None), serialize),
            ("willRecur" if serialize else "will_recur"): _to_legacy_value(getattr(self, "will_recur", None), serialize),
        }

    def __openapi_generator_modern_projection(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in products (list)
        _items = []
        if self.products:
            for _item_products in self.products:
                if _item_products:
                    _items.append(_to_openapi_value(_item_products))
            _dict['products'] = _items
        # override the default output from pydantic by calling `to_dict()` of purchase_context
        if self.purchase_context:
            _dict['purchaseContext'] = _to_openapi_value(self.purchase_context)
        # set to None if purchase_end_date (nullable) is None
        # and model_fields_set contains the field
        if self.purchase_end_date is None and "purchase_end_date" in self.model_fields_set:
            _dict['purchaseEndDate'] = None

        # set to None if purchase_start_date (nullable) is None
        # and model_fields_set contains the field
        if self.purchase_start_date is None and "purchase_start_date" in self.model_fields_set:
            _dict['purchaseStartDate'] = None

        # set to None if purchase_token (nullable) is None
        # and model_fields_set contains the field
        if self.purchase_token is None and "purchase_token" in self.model_fields_set:
            _dict['purchaseToken'] = None

        return _dict

    setattr(
        to_dict,
        _OPENAPI_GENERATOR_TO_DICT,
        __openapi_generator_modern_projection,
    )
    setattr(
        __openapi_generator_modern_projection,
        _OPENAPI_GENERATOR_TO_DICT,
        to_dict,
    )
    del __openapi_generator_modern_projection

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProductPurchase from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        obj = _cast(
            Dict[str, Any],
            cls.__preprocess_input_names(
                obj,
                remove_hidden_storage_names=True,
            ),
        )

        _obj = cls.model_validate({
            "buyerDisplayName": obj.get("buyerDisplayName"),
            "buyerId": obj.get("buyerId"),
            "firstParty": obj.get("firstParty"),
            "isBuyer": obj.get("isBuyer"),
            "isGift": obj.get("isGift"),
            "isReceiver": obj.get("isReceiver"),
            "isSeller": obj.get("isSeller"),
            "ledgerTransactionId": obj.get("ledgerTransactionId"),
            "listingCurrentlyAvailable": obj.get("listingCurrentlyAvailable"),
            "listingDescription": obj.get("listingDescription"),
            "listingDisplayName": obj.get("listingDisplayName"),
            "listingId": obj.get("listingId"),
            "listingImageId": obj.get("listingImageId"),
            "listingSubtitle": obj.get("listingSubtitle"),
            "listingType": obj.get("listingType") if obj.get("listingType") is not None else ProductListingType.SUBSCRIPTION,
            "products": [ProductPurchaseProduct.from_dict(_item) for _item in obj["products"]] if obj.get("products") is not None else None,
            "purchaseActive": obj.get("purchaseActive"),
            "purchaseContext": ProductPurchasePurchaseContext.from_dict(obj["purchaseContext"]) if obj.get("purchaseContext") is not None else None,
            "purchaseCurrentStatus": obj.get("purchaseCurrentStatus"),
            "purchaseDate": obj.get("purchaseDate"),
            "purchaseDuration": obj.get("purchaseDuration"),
            "purchaseDurationType": obj.get("purchaseDurationType"),
            "purchaseEndDate": obj.get("purchaseEndDate"),
            "purchaseFee": obj.get("purchaseFee"),
            "purchaseId": obj.get("purchaseId"),
            "purchaseLatest": obj.get("purchaseLatest"),
            "purchasePrice": obj.get("purchasePrice"),
            "purchaseQuantity": obj.get("purchaseQuantity"),
            "purchaseStartDate": obj.get("purchaseStartDate"),
            "purchaseToken": obj.get("purchaseToken"),
            "purchaseType": obj.get("purchaseType"),
            "purchaseUnitPrice": obj.get("purchaseUnitPrice"),
            "purchaseValue": obj.get("purchaseValue"),
            "receiverDisplayName": obj.get("receiverDisplayName"),
            "receiverId": obj.get("receiverId"),
            "recurrable": obj.get("recurrable"),
            "refundable": obj.get("refundable"),
            "sellerDisplayName": obj.get("sellerDisplayName"),
            "sellerId": obj.get("sellerId"),
            "stackable": obj.get("stackable"),
            "willRecur": obj.get("willRecur")
        })
        return _obj


