# coding: utf-8

"""
    VRChat API Documentation


    The version of the OpenAPI document: 1.20.8
    Contact: vrchatapi.lpv0t@aries.fyi
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from collections.abc import Mapping as _Mapping
from pydantic import AliasChoices, BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, cast as _cast
from typing_extensions import Annotated
from vrchatapi.models.purchase_context_data import PurchaseContextData
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


_OPENAPI_GENERATOR_TO_DICT = "_openapi_generator_to_dict"


def _get_openapi_to_dict(value: Any) -> Any:
    # Reciprocal function references preserve inherited generated methods
    # without reserving model member names. Checking both directions also
    # rejects overrides whose decorators copy function attributes.
    to_dict = getattr(value, "to_dict", None)
    type_to_dict = getattr(type(value), "to_dict", None)
    if (
        not callable(to_dict)
        or getattr(to_dict, "__func__", None) is not type_to_dict
    ):
        return None

    openapi_to_dict = getattr(
        type_to_dict, _OPENAPI_GENERATOR_TO_DICT, None
    )
    if (
        not callable(openapi_to_dict)
        or getattr(
            openapi_to_dict,
            _OPENAPI_GENERATOR_TO_DICT,
            None,
        ) is not type_to_dict
    ):
        return None
    return openapi_to_dict


def _to_legacy_item(value: Any, serialize: bool) -> Any:
    to_dict = getattr(value, "to_dict", None)
    if _get_openapi_to_dict(value) is not None and callable(to_dict):
        return to_dict(serialize=serialize)
    if callable(to_dict):
        return to_dict()
    return value


def _to_legacy_value(value: Any, serialize: bool) -> Any:
    # python-legacy converted only immediate list elements or dictionary values:
    # https://github.com/OpenAPITools/openapi-generator/blob/c84b949df1a9ec04ba75989cb49b45c940c2f694/modules/openapi-generator/src/main/resources/python-legacy/model.mustache#L203-L231
    if isinstance(value, list):
        return [_to_legacy_item(item, serialize) for item in value]
    if isinstance(value, dict):
        return {
            key: _to_legacy_item(item, serialize)
            for key, item in value.items()
        }
    return _to_legacy_item(value, serialize)


def _to_openapi_value(value: Any) -> Any:
    if isinstance(value, list):
        return [_to_openapi_value(item) for item in value]
    if isinstance(value, dict):
        return {key: _to_openapi_value(item) for key, item in value.items()}

    to_openapi_dict = _get_openapi_to_dict(value)
    if to_openapi_dict is not None:
        return to_openapi_dict(value)

    to_dict = getattr(value, "to_dict", None)
    if callable(to_dict):
        return to_dict()
    return value


class PurchaseProductListingRequest(BaseModel):
    """
    PurchaseProductListingRequest

    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """ # noqa: E501
    context_data: Optional[PurchaseContextData] = Field(default=None, validation_alias=AliasChoices("contextData", "context_data"), serialization_alias="contextData")
    listing_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("listingId", "listing_id"), serialization_alias="listingId", json_schema_extra={"examples": ["prod_bfbc2315-247a-44d7-bfea-5237f8d56cb4"]})
    listing_variant_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("listingVariantId", "listing_variant_id"), serialization_alias="listingVariantId", json_schema_extra={"examples": ["listvar_e8658b56-1662-436c-935a-afcf6a7d4fed"]})
    quantity: Optional[Annotated[int, Field(le=99, strict=True, ge=1)]] = None
    receiver_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("receiverId", "receiver_id"), serialization_alias="receiverId", description="A users unique ID, usually in the form of `usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469`. Legacy players can have old IDs in the form of `8JoV9XEdpo`. The ID can never be changed.", json_schema_extra={"examples": ["usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469"]})
    stackable: Optional[StrictBool] = None
    total_price: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, validation_alias=AliasChoices("totalPrice", "total_price"), serialization_alias="totalPrice")
    openapi_types: ClassVar[Dict[str, str]] = {
        "context_data": "PurchaseContextData",
        "listing_id": "str",
        "listing_variant_id": "str",
        "quantity": "int",
        "receiver_id": "str",
        "stackable": "bool",
        "total_price": "int"
    }

    attribute_map: ClassVar[Dict[str, str]] = {
        "context_data": "contextData",
        "listing_id": "listingId",
        "listing_variant_id": "listingVariantId",
        "quantity": "quantity",
        "receiver_id": "receiverId",
        "stackable": "stackable",
        "total_price": "totalPrice"
    }
    __properties: ClassVar[List[str]] = ["contextData", "listingId", "listingVariantId", "quantity", "receiverId", "stackable", "totalPrice"]

    @classmethod
    def __preprocess_input_names(
        cls,
        obj: Any,
        remove_hidden_storage_names: bool = True,
    ) -> Any:
        if not isinstance(obj, _Mapping):
            return obj
        obj = dict(obj)
        if "contextData" not in obj and "context_data" in obj:
            obj["contextData"] = obj["context_data"]
        obj.pop("context_data", None)
        if "listingId" not in obj and "listing_id" in obj:
            obj["listingId"] = obj["listing_id"]
        obj.pop("listing_id", None)
        if "listingVariantId" not in obj and "listing_variant_id" in obj:
            obj["listingVariantId"] = obj["listing_variant_id"]
        obj.pop("listing_variant_id", None)
        if "receiverId" not in obj and "receiver_id" in obj:
            obj["receiverId"] = obj["receiver_id"]
        obj.pop("receiver_id", None)
        if "totalPrice" not in obj and "total_price" in obj:
            obj["totalPrice"] = obj["total_price"]
        obj.pop("total_price", None)
        return obj

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        extra="forbid",
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For print and pprint"""
        return self.to_str()

    def __eq__(self, other: object) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, PurchaseProductListingRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other: object) -> bool:
        """Returns true if both objects are not equal"""
        if not isinstance(other, PurchaseProductListingRequest):
            return True

        return not (self == other)


    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        to_openapi_dict = _get_openapi_to_dict(self)
        if to_openapi_dict is not None:
            return json.dumps(to_jsonable_python(to_openapi_dict(self)))
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PurchaseProductListingRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self, serialize: bool = False) -> Dict[str, Any]:
        """Return all declared model fields using public or wire names."""
        return {
            ("contextData" if serialize else "context_data"): _to_legacy_value(getattr(self, "context_data", None), serialize),
            ("listingId" if serialize else "listing_id"): _to_legacy_value(getattr(self, "listing_id", None), serialize),
            ("listingVariantId" if serialize else "listing_variant_id"): _to_legacy_value(getattr(self, "listing_variant_id", None), serialize),
            ("quantity" if serialize else "quantity"): _to_legacy_value(getattr(self, "quantity", None), serialize),
            ("receiverId" if serialize else "receiver_id"): _to_legacy_value(getattr(self, "receiver_id", None), serialize),
            ("stackable" if serialize else "stackable"): _to_legacy_value(getattr(self, "stackable", None), serialize),
            ("totalPrice" if serialize else "total_price"): _to_legacy_value(getattr(self, "total_price", None), serialize),
        }

    def __openapi_generator_modern_projection(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of context_data
        if self.context_data:
            _dict['contextData'] = _to_openapi_value(self.context_data)
        return _dict

    setattr(
        to_dict,
        _OPENAPI_GENERATOR_TO_DICT,
        __openapi_generator_modern_projection,
    )
    setattr(
        __openapi_generator_modern_projection,
        _OPENAPI_GENERATOR_TO_DICT,
        to_dict,
    )
    del __openapi_generator_modern_projection

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PurchaseProductListingRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        obj = _cast(
            Dict[str, Any],
            cls.__preprocess_input_names(
                obj,
                remove_hidden_storage_names=True,
            ),
        )

        _obj = cls.model_validate({
            "contextData": PurchaseContextData.from_dict(obj["contextData"]) if obj.get("contextData") is not None else None,
            "listingId": obj.get("listingId"),
            "listingVariantId": obj.get("listingVariantId"),
            "quantity": obj.get("quantity") if obj.get("quantity") is not None else 1,
            "receiverId": obj.get("receiverId"),
            "stackable": obj.get("stackable"),
            "totalPrice": obj.get("totalPrice")
        })
        return _obj


