# coding: utf-8

"""
    VRChat API Documentation


    The version of the OpenAPI document: 1.20.8
    Contact: vrchatapi.lpv0t@aries.fyi
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from collections.abc import Mapping as _Mapping
from datetime import datetime
from pydantic import AliasChoices, BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, cast as _cast
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


_OPENAPI_GENERATOR_TO_DICT = "_openapi_generator_to_dict"


def _get_openapi_to_dict(value: Any) -> Any:
    # Reciprocal function references preserve inherited generated methods
    # without reserving model member names. Checking both directions also
    # rejects overrides whose decorators copy function attributes.
    to_dict = getattr(value, "to_dict", None)
    type_to_dict = getattr(type(value), "to_dict", None)
    if (
        not callable(to_dict)
        or getattr(to_dict, "__func__", None) is not type_to_dict
    ):
        return None

    openapi_to_dict = getattr(
        type_to_dict, _OPENAPI_GENERATOR_TO_DICT, None
    )
    if (
        not callable(openapi_to_dict)
        or getattr(
            openapi_to_dict,
            _OPENAPI_GENERATOR_TO_DICT,
            None,
        ) is not type_to_dict
    ):
        return None
    return openapi_to_dict


def _to_legacy_item(value: Any, serialize: bool) -> Any:
    to_dict = getattr(value, "to_dict", None)
    if _get_openapi_to_dict(value) is not None and callable(to_dict):
        return to_dict(serialize=serialize)
    if callable(to_dict):
        return to_dict()
    return value


def _to_legacy_value(value: Any, serialize: bool) -> Any:
    # python-legacy converted only immediate list elements or dictionary values:
    # https://github.com/OpenAPITools/openapi-generator/blob/c84b949df1a9ec04ba75989cb49b45c940c2f694/modules/openapi-generator/src/main/resources/python-legacy/model.mustache#L203-L231
    if isinstance(value, list):
        return [_to_legacy_item(item, serialize) for item in value]
    if isinstance(value, dict):
        return {
            key: _to_legacy_item(item, serialize)
            for key, item in value.items()
        }
    return _to_legacy_item(value, serialize)


def _to_openapi_value(value: Any) -> Any:
    if isinstance(value, list):
        return [_to_openapi_value(item) for item in value]
    if isinstance(value, dict):
        return {key: _to_openapi_value(item) for key, item in value.items()}

    to_openapi_dict = _get_openapi_to_dict(value)
    if to_openapi_dict is not None:
        return to_openapi_dict(value)

    to_dict = getattr(value, "to_dict", None)
    if callable(to_dict):
        return to_dict()
    return value


class RewardBadge(BaseModel):
    """
    RewardBadge

    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """ # noqa: E501
    created_at: Optional[datetime] = Field(default=None, validation_alias=AliasChoices("createdAt", "created_at"), serialization_alias="createdAt")
    created_by: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("createdBy", "created_by"), serialization_alias="createdBy", description="A users unique ID, usually in the form of `usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469`. Legacy players can have old IDs in the form of `8JoV9XEdpo`. The ID can never be changed.", json_schema_extra={"examples": ["usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469"]})
    description: Optional[StrictStr] = None
    file_name: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("fileName", "file_name"), serialization_alias="fileName")
    hidden: Optional[StrictBool] = None
    id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["bdg_a60e514a-8cb7-4702-8f24-2786992be1a8"]})
    image_url: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("imageUrl", "image_url"), serialization_alias="imageUrl")
    is_localization_enabled: Optional[StrictBool] = Field(default=None, validation_alias=AliasChoices("isLocalizationEnabled", "is_localization_enabled"), serialization_alias="isLocalizationEnabled")
    machine_name: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("machineName", "machine_name"), serialization_alias="machineName")
    name: Optional[StrictStr] = None
    type: Optional[StrictStr] = None
    updated_at: Optional[datetime] = Field(default=None, validation_alias=AliasChoices("updatedAt", "updated_at"), serialization_alias="updatedAt")
    openapi_types: ClassVar[Dict[str, str]] = {
        "created_at": "datetime",
        "created_by": "str",
        "description": "str",
        "file_name": "str",
        "hidden": "bool",
        "id": "str",
        "image_url": "str",
        "is_localization_enabled": "bool",
        "machine_name": "str",
        "name": "str",
        "type": "str",
        "updated_at": "datetime"
    }

    attribute_map: ClassVar[Dict[str, str]] = {
        "created_at": "createdAt",
        "created_by": "createdBy",
        "description": "description",
        "file_name": "fileName",
        "hidden": "hidden",
        "id": "id",
        "image_url": "imageUrl",
        "is_localization_enabled": "isLocalizationEnabled",
        "machine_name": "machineName",
        "name": "name",
        "type": "type",
        "updated_at": "updatedAt"
    }
    __properties: ClassVar[List[str]] = ["createdAt", "createdBy", "description", "fileName", "hidden", "id", "imageUrl", "isLocalizationEnabled", "machineName", "name", "type", "updatedAt"]

    @classmethod
    def __preprocess_input_names(
        cls,
        obj: Any,
        remove_hidden_storage_names: bool = True,
    ) -> Any:
        if not isinstance(obj, _Mapping):
            return obj
        obj = dict(obj)
        if "createdAt" not in obj and "created_at" in obj:
            obj["createdAt"] = obj["created_at"]
        obj.pop("created_at", None)
        if "createdBy" not in obj and "created_by" in obj:
            obj["createdBy"] = obj["created_by"]
        obj.pop("created_by", None)
        if "fileName" not in obj and "file_name" in obj:
            obj["fileName"] = obj["file_name"]
        obj.pop("file_name", None)
        if "imageUrl" not in obj and "image_url" in obj:
            obj["imageUrl"] = obj["image_url"]
        obj.pop("image_url", None)
        if "isLocalizationEnabled" not in obj and "is_localization_enabled" in obj:
            obj["isLocalizationEnabled"] = obj["is_localization_enabled"]
        obj.pop("is_localization_enabled", None)
        if "machineName" not in obj and "machine_name" in obj:
            obj["machineName"] = obj["machine_name"]
        obj.pop("machine_name", None)
        if "updatedAt" not in obj and "updated_at" in obj:
            obj["updatedAt"] = obj["updated_at"]
        obj.pop("updated_at", None)
        return obj

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        extra="forbid",
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For print and pprint"""
        return self.to_str()

    def __eq__(self, other: object) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, RewardBadge):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other: object) -> bool:
        """Returns true if both objects are not equal"""
        if not isinstance(other, RewardBadge):
            return True

        return not (self == other)


    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        to_openapi_dict = _get_openapi_to_dict(self)
        if to_openapi_dict is not None:
            return json.dumps(to_jsonable_python(to_openapi_dict(self)))
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RewardBadge from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self, serialize: bool = False) -> Dict[str, Any]:
        """Return all declared model fields using public or wire names."""
        return {
            ("createdAt" if serialize else "created_at"): _to_legacy_value(getattr(self, "created_at", None), serialize),
            ("createdBy" if serialize else "created_by"): _to_legacy_value(getattr(self, "created_by", None), serialize),
            ("description" if serialize else "description"): _to_legacy_value(getattr(self, "description", None), serialize),
            ("fileName" if serialize else "file_name"): _to_legacy_value(getattr(self, "file_name", None), serialize),
            ("hidden" if serialize else "hidden"): _to_legacy_value(getattr(self, "hidden", None), serialize),
            ("id" if serialize else "id"): _to_legacy_value(getattr(self, "id", None), serialize),
            ("imageUrl" if serialize else "image_url"): _to_legacy_value(getattr(self, "image_url", None), serialize),
            ("isLocalizationEnabled" if serialize else "is_localization_enabled"): _to_legacy_value(getattr(self, "is_localization_enabled", None), serialize),
            ("machineName" if serialize else "machine_name"): _to_legacy_value(getattr(self, "machine_name", None), serialize),
            ("name" if serialize else "name"): _to_legacy_value(getattr(self, "name", None), serialize),
            ("type" if serialize else "type"): _to_legacy_value(getattr(self, "type", None), serialize),
            ("updatedAt" if serialize else "updated_at"): _to_legacy_value(getattr(self, "updated_at", None), serialize),
        }

    def __openapi_generator_modern_projection(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    setattr(
        to_dict,
        _OPENAPI_GENERATOR_TO_DICT,
        __openapi_generator_modern_projection,
    )
    setattr(
        __openapi_generator_modern_projection,
        _OPENAPI_GENERATOR_TO_DICT,
        to_dict,
    )
    del __openapi_generator_modern_projection

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RewardBadge from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        obj = _cast(
            Dict[str, Any],
            cls.__preprocess_input_names(
                obj,
                remove_hidden_storage_names=True,
            ),
        )

        _obj = cls.model_validate({
            "createdAt": obj.get("createdAt"),
            "createdBy": obj.get("createdBy"),
            "description": obj.get("description"),
            "fileName": obj.get("fileName"),
            "hidden": obj.get("hidden"),
            "id": obj.get("id"),
            "imageUrl": obj.get("imageUrl"),
            "isLocalizationEnabled": obj.get("isLocalizationEnabled"),
            "machineName": obj.get("machineName"),
            "name": obj.get("name"),
            "type": obj.get("type"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


