# coding: utf-8

"""
    VRChat API Documentation


    The version of the OpenAPI document: 1.20.8
    Contact: vrchatapi.lpv0t@aries.fyi
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from collections.abc import Mapping as _Mapping
from datetime import datetime
from pydantic import AliasChoices, BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, cast as _cast
from typing_extensions import Annotated
from vrchatapi.models.product_listing import ProductListing
from vrchatapi.models.store_context import StoreContext
from vrchatapi.models.store_shelf import StoreShelf
from vrchatapi.models.store_type import StoreType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


_OPENAPI_GENERATOR_TO_DICT = "_openapi_generator_to_dict"


def _get_openapi_to_dict(value: Any) -> Any:
    # Reciprocal function references preserve inherited generated methods
    # without reserving model member names. Checking both directions also
    # rejects overrides whose decorators copy function attributes.
    to_dict = getattr(value, "to_dict", None)
    type_to_dict = getattr(type(value), "to_dict", None)
    if (
        not callable(to_dict)
        or getattr(to_dict, "__func__", None) is not type_to_dict
    ):
        return None

    openapi_to_dict = getattr(
        type_to_dict, _OPENAPI_GENERATOR_TO_DICT, None
    )
    if (
        not callable(openapi_to_dict)
        or getattr(
            openapi_to_dict,
            _OPENAPI_GENERATOR_TO_DICT,
            None,
        ) is not type_to_dict
    ):
        return None
    return openapi_to_dict


def _to_legacy_item(value: Any, serialize: bool) -> Any:
    to_dict = getattr(value, "to_dict", None)
    if _get_openapi_to_dict(value) is not None and callable(to_dict):
        return to_dict(serialize=serialize)
    if callable(to_dict):
        return to_dict()
    return value


def _to_legacy_value(value: Any, serialize: bool) -> Any:
    # python-legacy converted only immediate list elements or dictionary values:
    # https://github.com/OpenAPITools/openapi-generator/blob/c84b949df1a9ec04ba75989cb49b45c940c2f694/modules/openapi-generator/src/main/resources/python-legacy/model.mustache#L203-L231
    if isinstance(value, list):
        return [_to_legacy_item(item, serialize) for item in value]
    if isinstance(value, dict):
        return {
            key: _to_legacy_item(item, serialize)
            for key, item in value.items()
        }
    return _to_legacy_item(value, serialize)


def _to_openapi_value(value: Any) -> Any:
    if isinstance(value, list):
        return [_to_openapi_value(item) for item in value]
    if isinstance(value, dict):
        return {key: _to_openapi_value(item) for key, item in value.items()}

    to_openapi_dict = _get_openapi_to_dict(value)
    if to_openapi_dict is not None:
        return to_openapi_dict(value)

    to_dict = getattr(value, "to_dict", None)
    if callable(to_dict):
        return to_dict()
    return value


class Store(BaseModel):
    """
    Store

    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """ # noqa: E501
    created: Optional[datetime] = None
    description: Optional[StrictStr] = None
    display_name: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("displayName", "display_name"), serialization_alias="displayName")
    group_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("groupId", "group_id"), serialization_alias="groupId", json_schema_extra={"examples": ["grp_71a7ff59-112c-4e78-a990-c7cc650776e5"]})
    id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["esto_713b247d-2b5d-41a0-bba3-50db28dc1498"]})
    listing_ids: Optional[List[StrictStr]] = Field(default=None, validation_alias=AliasChoices("listingIds", "listing_ids"), serialization_alias="listingIds", description="Only for store type world and group")
    listings: Optional[List[ProductListing]] = Field(default=None, description="Only for store type world and group")
    seller_display_name: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("sellerDisplayName", "seller_display_name"), serialization_alias="sellerDisplayName")
    seller_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("sellerId", "seller_id"), serialization_alias="sellerId", description="A users unique ID, usually in the form of `usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469`. Legacy players can have old IDs in the form of `8JoV9XEdpo`. The ID can never be changed.", json_schema_extra={"examples": ["usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469"]})
    shelf_ids: Optional[List[StrictStr]] = Field(default=None, validation_alias=AliasChoices("shelfIds", "shelf_ids"), serialization_alias="shelfIds", description="Only for store type house")
    shelves: Optional[List[StoreShelf]] = Field(default=None, description="Only for store type house")
    store_context: Optional[StoreContext] = Field(default=None, validation_alias=AliasChoices("storeContext", "store_context"), serialization_alias="storeContext")
    store_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("storeId", "store_id"), serialization_alias="storeId", json_schema_extra={"examples": ["esto_713b247d-2b5d-41a0-bba3-50db28dc1498"]})
    store_status: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("storeStatus", "store_status"), serialization_alias="storeStatus")
    store_type: Optional[StoreType] = Field(default=None, validation_alias=AliasChoices("storeType", "store_type"), serialization_alias="storeType")
    tags: Optional[List[Annotated[str, Field(min_length=1, strict=True)]]] = None
    updated: Optional[datetime] = None
    world_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("worldId", "world_id"), serialization_alias="worldId", description="WorldID be \"offline\" on User profiles if you are not friends with that user.", json_schema_extra={"examples": ["wrld_4432ea9b-729c-46e3-8eaf-846aa0a37fdd"]})
    openapi_types: ClassVar[Dict[str, str]] = {
        "created": "datetime",
        "description": "str",
        "display_name": "str",
        "group_id": "str",
        "id": "str",
        "listing_ids": "List[str]",
        "listings": "List[ProductListing]",
        "seller_display_name": "str",
        "seller_id": "str",
        "shelf_ids": "List[str]",
        "shelves": "List[StoreShelf]",
        "store_context": "StoreContext",
        "store_id": "str",
        "store_status": "str",
        "store_type": "StoreType",
        "tags": "List[str]",
        "updated": "datetime",
        "world_id": "str"
    }

    attribute_map: ClassVar[Dict[str, str]] = {
        "created": "created",
        "description": "description",
        "display_name": "displayName",
        "group_id": "groupId",
        "id": "id",
        "listing_ids": "listingIds",
        "listings": "listings",
        "seller_display_name": "sellerDisplayName",
        "seller_id": "sellerId",
        "shelf_ids": "shelfIds",
        "shelves": "shelves",
        "store_context": "storeContext",
        "store_id": "storeId",
        "store_status": "storeStatus",
        "store_type": "storeType",
        "tags": "tags",
        "updated": "updated",
        "world_id": "worldId"
    }
    __properties: ClassVar[List[str]] = ["created", "description", "displayName", "groupId", "id", "listingIds", "listings", "sellerDisplayName", "sellerId", "shelfIds", "shelves", "storeContext", "storeId", "storeStatus", "storeType", "tags", "updated", "worldId"]

    @classmethod
    def __preprocess_input_names(
        cls,
        obj: Any,
        remove_hidden_storage_names: bool = True,
    ) -> Any:
        if not isinstance(obj, _Mapping):
            return obj
        obj = dict(obj)
        if "displayName" not in obj and "display_name" in obj:
            obj["displayName"] = obj["display_name"]
        obj.pop("display_name", None)
        if "groupId" not in obj and "group_id" in obj:
            obj["groupId"] = obj["group_id"]
        obj.pop("group_id", None)
        if "listingIds" not in obj and "listing_ids" in obj:
            obj["listingIds"] = obj["listing_ids"]
        obj.pop("listing_ids", None)
        if "sellerDisplayName" not in obj and "seller_display_name" in obj:
            obj["sellerDisplayName"] = obj["seller_display_name"]
        obj.pop("seller_display_name", None)
        if "sellerId" not in obj and "seller_id" in obj:
            obj["sellerId"] = obj["seller_id"]
        obj.pop("seller_id", None)
        if "shelfIds" not in obj and "shelf_ids" in obj:
            obj["shelfIds"] = obj["shelf_ids"]
        obj.pop("shelf_ids", None)
        if "storeContext" not in obj and "store_context" in obj:
            obj["storeContext"] = obj["store_context"]
        obj.pop("store_context", None)
        if "storeId" not in obj and "store_id" in obj:
            obj["storeId"] = obj["store_id"]
        obj.pop("store_id", None)
        if "storeStatus" not in obj and "store_status" in obj:
            obj["storeStatus"] = obj["store_status"]
        obj.pop("store_status", None)
        if "storeType" not in obj and "store_type" in obj:
            obj["storeType"] = obj["store_type"]
        obj.pop("store_type", None)
        if "worldId" not in obj and "world_id" in obj:
            obj["worldId"] = obj["world_id"]
        obj.pop("world_id", None)
        return obj

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        extra="forbid",
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For print and pprint"""
        return self.to_str()

    def __eq__(self, other: object) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, Store):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other: object) -> bool:
        """Returns true if both objects are not equal"""
        if not isinstance(other, Store):
            return True

        return not (self == other)


    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        to_openapi_dict = _get_openapi_to_dict(self)
        if to_openapi_dict is not None:
            return json.dumps(to_jsonable_python(to_openapi_dict(self)))
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Store from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self, serialize: bool = False) -> Dict[str, Any]:
        """Return all declared model fields using public or wire names."""
        return {
            ("created" if serialize else "created"): _to_legacy_value(getattr(self, "created", None), serialize),
            ("description" if serialize else "description"): _to_legacy_value(getattr(self, "description", None), serialize),
            ("displayName" if serialize else "display_name"): _to_legacy_value(getattr(self, "display_name", None), serialize),
            ("groupId" if serialize else "group_id"): _to_legacy_value(getattr(self, "group_id", None), serialize),
            ("id" if serialize else "id"): _to_legacy_value(getattr(self, "id", None), serialize),
            ("listingIds" if serialize else "listing_ids"): _to_legacy_value(getattr(self, "listing_ids", None), serialize),
            ("listings" if serialize else "listings"): _to_legacy_value(getattr(self, "listings", None), serialize),
            ("sellerDisplayName" if serialize else "seller_display_name"): _to_legacy_value(getattr(self, "seller_display_name", None), serialize),
            ("sellerId" if serialize else "seller_id"): _to_legacy_value(getattr(self, "seller_id", None), serialize),
            ("shelfIds" if serialize else "shelf_ids"): _to_legacy_value(getattr(self, "shelf_ids", None), serialize),
            ("shelves" if serialize else "shelves"): _to_legacy_value(getattr(self, "shelves", None), serialize),
            ("storeContext" if serialize else "store_context"): _to_legacy_value(getattr(self, "store_context", None), serialize),
            ("storeId" if serialize else "store_id"): _to_legacy_value(getattr(self, "store_id", None), serialize),
            ("storeStatus" if serialize else "store_status"): _to_legacy_value(getattr(self, "store_status", None), serialize),
            ("storeType" if serialize else "store_type"): _to_legacy_value(getattr(self, "store_type", None), serialize),
            ("tags" if serialize else "tags"): _to_legacy_value(getattr(self, "tags", None), serialize),
            ("updated" if serialize else "updated"): _to_legacy_value(getattr(self, "updated", None), serialize),
            ("worldId" if serialize else "world_id"): _to_legacy_value(getattr(self, "world_id", None), serialize),
        }

    def __openapi_generator_modern_projection(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in listings (list)
        _items = []
        if self.listings:
            for _item_listings in self.listings:
                if _item_listings:
                    _items.append(_to_openapi_value(_item_listings))
            _dict['listings'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in shelves (list)
        _items = []
        if self.shelves:
            for _item_shelves in self.shelves:
                if _item_shelves:
                    _items.append(_to_openapi_value(_item_shelves))
            _dict['shelves'] = _items
        # override the default output from pydantic by calling `to_dict()` of store_context
        if self.store_context:
            _dict['storeContext'] = _to_openapi_value(self.store_context)
        return _dict

    setattr(
        to_dict,
        _OPENAPI_GENERATOR_TO_DICT,
        __openapi_generator_modern_projection,
    )
    setattr(
        __openapi_generator_modern_projection,
        _OPENAPI_GENERATOR_TO_DICT,
        to_dict,
    )
    del __openapi_generator_modern_projection

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Store from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        obj = _cast(
            Dict[str, Any],
            cls.__preprocess_input_names(
                obj,
                remove_hidden_storage_names=True,
            ),
        )

        _obj = cls.model_validate({
            "created": obj.get("created"),
            "description": obj.get("description"),
            "displayName": obj.get("displayName"),
            "groupId": obj.get("groupId"),
            "id": obj.get("id"),
            "listingIds": obj.get("listingIds"),
            "listings": [ProductListing.from_dict(_item) for _item in obj["listings"]] if obj.get("listings") is not None else None,
            "sellerDisplayName": obj.get("sellerDisplayName"),
            "sellerId": obj.get("sellerId"),
            "shelfIds": obj.get("shelfIds"),
            "shelves": [StoreShelf.from_dict(_item) for _item in obj["shelves"]] if obj.get("shelves") is not None else None,
            "storeContext": StoreContext.from_dict(obj["storeContext"]) if obj.get("storeContext") is not None else None,
            "storeId": obj.get("storeId"),
            "storeStatus": obj.get("storeStatus"),
            "storeType": obj.get("storeType") if obj.get("storeType") is not None else StoreType.GROUP,
            "tags": obj.get("tags"),
            "updated": obj.get("updated"),
            "worldId": obj.get("worldId")
        })
        return _obj


