# coding: utf-8

"""
    VRChat API Documentation


    The version of the OpenAPI document: 1.21.0
    Contact: vrchatapi.lpv0t@aries.fyi
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from collections.abc import Mapping as _Mapping
from pydantic import AliasChoices, BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, cast as _cast
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


_OPENAPI_GENERATOR_TO_DICT = "_openapi_generator_to_dict"


def _get_openapi_to_dict(value: Any) -> Any:
    # Reciprocal function references preserve inherited generated methods
    # without reserving model member names. Checking both directions also
    # rejects overrides whose decorators copy function attributes.
    to_dict = getattr(value, "to_dict", None)
    type_to_dict = getattr(type(value), "to_dict", None)
    if (
        not callable(to_dict)
        or getattr(to_dict, "__func__", None) is not type_to_dict
    ):
        return None

    openapi_to_dict = getattr(
        type_to_dict, _OPENAPI_GENERATOR_TO_DICT, None
    )
    if (
        not callable(openapi_to_dict)
        or getattr(
            openapi_to_dict,
            _OPENAPI_GENERATOR_TO_DICT,
            None,
        ) is not type_to_dict
    ):
        return None
    return openapi_to_dict


def _to_legacy_item(value: Any, serialize: bool) -> Any:
    to_dict = getattr(value, "to_dict", None)
    if _get_openapi_to_dict(value) is not None and callable(to_dict):
        return to_dict(serialize=serialize)
    if callable(to_dict):
        return to_dict()
    return value


def _to_legacy_value(value: Any, serialize: bool) -> Any:
    # python-legacy converted only immediate list elements or dictionary values:
    # https://github.com/OpenAPITools/openapi-generator/blob/c84b949df1a9ec04ba75989cb49b45c940c2f694/modules/openapi-generator/src/main/resources/python-legacy/model.mustache#L203-L231
    if isinstance(value, list):
        return [_to_legacy_item(item, serialize) for item in value]
    if isinstance(value, dict):
        return {
            key: _to_legacy_item(item, serialize)
            for key, item in value.items()
        }
    return _to_legacy_item(value, serialize)


def _to_openapi_value(value: Any) -> Any:
    if isinstance(value, list):
        return [_to_openapi_value(item) for item in value]
    if isinstance(value, dict):
        return {key: _to_openapi_value(item) for key, item in value.items()}

    to_openapi_dict = _get_openapi_to_dict(value)
    if to_openapi_dict is not None:
        return to_openapi_dict(value)

    to_dict = getattr(value, "to_dict", None)
    if callable(to_dict):
        return to_dict()
    return value


class UpdateProfileRequest(BaseModel):
    """
    UpdateProfileRequest

    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """ # noqa: E501
    background_texture_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("backgroundTextureId", "background_texture_id"), serialization_alias="backgroundTextureId")
    background_type: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("backgroundType", "background_type"), serialization_alias="backgroundType")
    banner_color: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("bannerColor", "banner_color"), serialization_alias="bannerColor", description="Hex colour without a leading `#`.")
    banner_type: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("bannerType", "banner_type"), serialization_alias="bannerType")
    bio: Optional[StrictStr] = None
    bio_links: Optional[List[StrictStr]] = Field(default=None, validation_alias=AliasChoices("bioLinks", "bio_links"), serialization_alias="bioLinks")
    icon_frame: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("iconFrame", "icon_frame"), serialization_alias="iconFrame", json_schema_extra={"examples": ["invt_b80ce14b-038b-4f56-b970-d232771d62e3"]})
    languages: Optional[List[StrictStr]] = None
    nameplate_effect: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("nameplateEffect", "nameplate_effect"), serialization_alias="nameplateEffect", json_schema_extra={"examples": ["invt_b80ce14b-038b-4f56-b970-d232771d62e3"]})
    profile_effect: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("profileEffect", "profile_effect"), serialization_alias="profileEffect", json_schema_extra={"examples": ["invt_b80ce14b-038b-4f56-b970-d232771d62e3"]})
    theme_id: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("themeId", "theme_id"), serialization_alias="themeId")
    user_icon: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("userIcon", "user_icon"), serialization_alias="userIcon")
    openapi_types: ClassVar[Dict[str, str]] = {
        "background_texture_id": "str",
        "background_type": "str",
        "banner_color": "str",
        "banner_type": "str",
        "bio": "str",
        "bio_links": "List[str]",
        "icon_frame": "str",
        "languages": "List[str]",
        "nameplate_effect": "str",
        "profile_effect": "str",
        "theme_id": "str",
        "user_icon": "str"
    }

    attribute_map: ClassVar[Dict[str, str]] = {
        "background_texture_id": "backgroundTextureId",
        "background_type": "backgroundType",
        "banner_color": "bannerColor",
        "banner_type": "bannerType",
        "bio": "bio",
        "bio_links": "bioLinks",
        "icon_frame": "iconFrame",
        "languages": "languages",
        "nameplate_effect": "nameplateEffect",
        "profile_effect": "profileEffect",
        "theme_id": "themeId",
        "user_icon": "userIcon"
    }
    __properties: ClassVar[List[str]] = ["backgroundTextureId", "backgroundType", "bannerColor", "bannerType", "bio", "bioLinks", "iconFrame", "languages", "nameplateEffect", "profileEffect", "themeId", "userIcon"]

    @field_validator('background_type')
    def background_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['default', 'gradient', 'inventory', 'texture']):
            raise ValueError("must be one of enum values ('default', 'gradient', 'inventory', 'texture')")
        return value

    @field_validator('banner_type')
    def banner_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['avatarBanner', 'color', 'customImage']):
            raise ValueError("must be one of enum values ('avatarBanner', 'color', 'customImage')")
        return value

    @classmethod
    def __preprocess_input_names(
        cls,
        obj: Any,
        remove_hidden_storage_names: bool = True,
    ) -> Any:
        if not isinstance(obj, _Mapping):
            return obj
        obj = dict(obj)
        if "backgroundTextureId" not in obj and "background_texture_id" in obj:
            obj["backgroundTextureId"] = obj["background_texture_id"]
        obj.pop("background_texture_id", None)
        if "backgroundType" not in obj and "background_type" in obj:
            obj["backgroundType"] = obj["background_type"]
        obj.pop("background_type", None)
        if "bannerColor" not in obj and "banner_color" in obj:
            obj["bannerColor"] = obj["banner_color"]
        obj.pop("banner_color", None)
        if "bannerType" not in obj and "banner_type" in obj:
            obj["bannerType"] = obj["banner_type"]
        obj.pop("banner_type", None)
        if "bioLinks" not in obj and "bio_links" in obj:
            obj["bioLinks"] = obj["bio_links"]
        obj.pop("bio_links", None)
        if "iconFrame" not in obj and "icon_frame" in obj:
            obj["iconFrame"] = obj["icon_frame"]
        obj.pop("icon_frame", None)
        if "nameplateEffect" not in obj and "nameplate_effect" in obj:
            obj["nameplateEffect"] = obj["nameplate_effect"]
        obj.pop("nameplate_effect", None)
        if "profileEffect" not in obj and "profile_effect" in obj:
            obj["profileEffect"] = obj["profile_effect"]
        obj.pop("profile_effect", None)
        if "themeId" not in obj and "theme_id" in obj:
            obj["themeId"] = obj["theme_id"]
        obj.pop("theme_id", None)
        if "userIcon" not in obj and "user_icon" in obj:
            obj["userIcon"] = obj["user_icon"]
        obj.pop("user_icon", None)
        return obj

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        extra="forbid",
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For print and pprint"""
        return self.to_str()

    def __eq__(self, other: object) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateProfileRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other: object) -> bool:
        """Returns true if both objects are not equal"""
        if not isinstance(other, UpdateProfileRequest):
            return True

        return not (self == other)


    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        to_openapi_dict = _get_openapi_to_dict(self)
        if to_openapi_dict is not None:
            return json.dumps(to_jsonable_python(to_openapi_dict(self)))
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateProfileRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self, serialize: bool = False) -> Dict[str, Any]:
        """Return all declared model fields using public or wire names."""
        return {
            ("backgroundTextureId" if serialize else "background_texture_id"): _to_legacy_value(getattr(self, "background_texture_id", None), serialize),
            ("backgroundType" if serialize else "background_type"): _to_legacy_value(getattr(self, "background_type", None), serialize),
            ("bannerColor" if serialize else "banner_color"): _to_legacy_value(getattr(self, "banner_color", None), serialize),
            ("bannerType" if serialize else "banner_type"): _to_legacy_value(getattr(self, "banner_type", None), serialize),
            ("bio" if serialize else "bio"): _to_legacy_value(getattr(self, "bio", None), serialize),
            ("bioLinks" if serialize else "bio_links"): _to_legacy_value(getattr(self, "bio_links", None), serialize),
            ("iconFrame" if serialize else "icon_frame"): _to_legacy_value(getattr(self, "icon_frame", None), serialize),
            ("languages" if serialize else "languages"): _to_legacy_value(getattr(self, "languages", None), serialize),
            ("nameplateEffect" if serialize else "nameplate_effect"): _to_legacy_value(getattr(self, "nameplate_effect", None), serialize),
            ("profileEffect" if serialize else "profile_effect"): _to_legacy_value(getattr(self, "profile_effect", None), serialize),
            ("themeId" if serialize else "theme_id"): _to_legacy_value(getattr(self, "theme_id", None), serialize),
            ("userIcon" if serialize else "user_icon"): _to_legacy_value(getattr(self, "user_icon", None), serialize),
        }

    def __openapi_generator_modern_projection(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    setattr(
        to_dict,
        _OPENAPI_GENERATOR_TO_DICT,
        __openapi_generator_modern_projection,
    )
    setattr(
        __openapi_generator_modern_projection,
        _OPENAPI_GENERATOR_TO_DICT,
        to_dict,
    )
    del __openapi_generator_modern_projection

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateProfileRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        obj = _cast(
            Dict[str, Any],
            cls.__preprocess_input_names(
                obj,
                remove_hidden_storage_names=True,
            ),
        )

        _obj = cls.model_validate({
            "backgroundTextureId": obj.get("backgroundTextureId"),
            "backgroundType": obj.get("backgroundType"),
            "bannerColor": obj.get("bannerColor"),
            "bannerType": obj.get("bannerType"),
            "bio": obj.get("bio"),
            "bioLinks": obj.get("bioLinks"),
            "iconFrame": obj.get("iconFrame"),
            "languages": obj.get("languages"),
            "nameplateEffect": obj.get("nameplateEffect"),
            "profileEffect": obj.get("profileEffect"),
            "themeId": obj.get("themeId"),
            "userIcon": obj.get("userIcon")
        })
        return _obj


