# coding: utf-8

"""
    VRChat API Documentation


    The version of the OpenAPI document: 1.20.8
    Contact: vrchatapi.lpv0t@aries.fyi
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from collections.abc import Mapping as _Mapping
from pydantic import AliasChoices, BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, cast as _cast
from typing_extensions import Annotated
from vrchatapi.models.release_status import ReleaseStatus
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


_OPENAPI_GENERATOR_TO_DICT = "_openapi_generator_to_dict"


def _get_openapi_to_dict(value: Any) -> Any:
    # Reciprocal function references preserve inherited generated methods
    # without reserving model member names. Checking both directions also
    # rejects overrides whose decorators copy function attributes.
    to_dict = getattr(value, "to_dict", None)
    type_to_dict = getattr(type(value), "to_dict", None)
    if (
        not callable(to_dict)
        or getattr(to_dict, "__func__", None) is not type_to_dict
    ):
        return None

    openapi_to_dict = getattr(
        type_to_dict, _OPENAPI_GENERATOR_TO_DICT, None
    )
    if (
        not callable(openapi_to_dict)
        or getattr(
            openapi_to_dict,
            _OPENAPI_GENERATOR_TO_DICT,
            None,
        ) is not type_to_dict
    ):
        return None
    return openapi_to_dict


def _to_legacy_item(value: Any, serialize: bool) -> Any:
    to_dict = getattr(value, "to_dict", None)
    if _get_openapi_to_dict(value) is not None and callable(to_dict):
        return to_dict(serialize=serialize)
    if callable(to_dict):
        return to_dict()
    return value


def _to_legacy_value(value: Any, serialize: bool) -> Any:
    # python-legacy converted only immediate list elements or dictionary values:
    # https://github.com/OpenAPITools/openapi-generator/blob/c84b949df1a9ec04ba75989cb49b45c940c2f694/modules/openapi-generator/src/main/resources/python-legacy/model.mustache#L203-L231
    if isinstance(value, list):
        return [_to_legacy_item(item, serialize) for item in value]
    if isinstance(value, dict):
        return {
            key: _to_legacy_item(item, serialize)
            for key, item in value.items()
        }
    return _to_legacy_item(value, serialize)


def _to_openapi_value(value: Any) -> Any:
    if isinstance(value, list):
        return [_to_openapi_value(item) for item in value]
    if isinstance(value, dict):
        return {key: _to_openapi_value(item) for key, item in value.items()}

    to_openapi_dict = _get_openapi_to_dict(value)
    if to_openapi_dict is not None:
        return to_openapi_dict(value)

    to_dict = getattr(value, "to_dict", None)
    if callable(to_dict):
        return to_dict()
    return value


class UpdateAvatarRequest(BaseModel):
    """
    UpdateAvatarRequest

    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """ # noqa: E501
    asset_url: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("assetUrl", "asset_url"), serialization_alias="assetUrl")
    description: Optional[Annotated[str, Field(min_length=1, strict=True)]] = None
    id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["avtr_912d66a4-4714-43b8-8407-7de2cafbf55b"]})
    image_url: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, validation_alias=AliasChoices("imageUrl", "image_url"), serialization_alias="imageUrl")
    name: Optional[Annotated[str, Field(min_length=1, strict=True)]] = None
    release_status: Optional[ReleaseStatus] = Field(default=ReleaseStatus.PUBLIC, validation_alias=AliasChoices("releaseStatus", "release_status"), serialization_alias="releaseStatus")
    tags: Optional[List[Annotated[str, Field(min_length=1, strict=True)]]] = Field(default=None, description=" ")
    unity_package_url: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("unityPackageUrl", "unity_package_url"), serialization_alias="unityPackageUrl")
    unity_version: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default='5.3.4p1', validation_alias=AliasChoices("unityVersion", "unity_version"), serialization_alias="unityVersion", json_schema_extra={"examples": ["2022.3.6f1"]})
    version: Optional[Annotated[int, Field(strict=True, ge=0)]] = 1
    openapi_types: ClassVar[Dict[str, str]] = {
        "asset_url": "str",
        "description": "str",
        "id": "str",
        "image_url": "str",
        "name": "str",
        "release_status": "ReleaseStatus",
        "tags": "List[str]",
        "unity_package_url": "str",
        "unity_version": "str",
        "version": "int"
    }

    attribute_map: ClassVar[Dict[str, str]] = {
        "asset_url": "assetUrl",
        "description": "description",
        "id": "id",
        "image_url": "imageUrl",
        "name": "name",
        "release_status": "releaseStatus",
        "tags": "tags",
        "unity_package_url": "unityPackageUrl",
        "unity_version": "unityVersion",
        "version": "version"
    }
    __properties: ClassVar[List[str]] = ["assetUrl", "description", "id", "imageUrl", "name", "releaseStatus", "tags", "unityPackageUrl", "unityVersion", "version"]

    @classmethod
    def __preprocess_input_names(
        cls,
        obj: Any,
        remove_hidden_storage_names: bool = True,
    ) -> Any:
        if not isinstance(obj, _Mapping):
            return obj
        obj = dict(obj)
        if "assetUrl" not in obj and "asset_url" in obj:
            obj["assetUrl"] = obj["asset_url"]
        obj.pop("asset_url", None)
        if "imageUrl" not in obj and "image_url" in obj:
            obj["imageUrl"] = obj["image_url"]
        obj.pop("image_url", None)
        if "releaseStatus" not in obj and "release_status" in obj:
            obj["releaseStatus"] = obj["release_status"]
        obj.pop("release_status", None)
        if "unityPackageUrl" not in obj and "unity_package_url" in obj:
            obj["unityPackageUrl"] = obj["unity_package_url"]
        obj.pop("unity_package_url", None)
        if "unityVersion" not in obj and "unity_version" in obj:
            obj["unityVersion"] = obj["unity_version"]
        obj.pop("unity_version", None)
        return obj

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        extra="forbid",
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For print and pprint"""
        return self.to_str()

    def __eq__(self, other: object) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateAvatarRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other: object) -> bool:
        """Returns true if both objects are not equal"""
        if not isinstance(other, UpdateAvatarRequest):
            return True

        return not (self == other)


    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        to_openapi_dict = _get_openapi_to_dict(self)
        if to_openapi_dict is not None:
            return json.dumps(to_jsonable_python(to_openapi_dict(self)))
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateAvatarRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self, serialize: bool = False) -> Dict[str, Any]:
        """Return all declared model fields using public or wire names."""
        return {
            ("assetUrl" if serialize else "asset_url"): _to_legacy_value(getattr(self, "asset_url", None), serialize),
            ("description" if serialize else "description"): _to_legacy_value(getattr(self, "description", None), serialize),
            ("id" if serialize else "id"): _to_legacy_value(getattr(self, "id", None), serialize),
            ("imageUrl" if serialize else "image_url"): _to_legacy_value(getattr(self, "image_url", None), serialize),
            ("name" if serialize else "name"): _to_legacy_value(getattr(self, "name", None), serialize),
            ("releaseStatus" if serialize else "release_status"): _to_legacy_value(getattr(self, "release_status", None), serialize),
            ("tags" if serialize else "tags"): _to_legacy_value(getattr(self, "tags", None), serialize),
            ("unityPackageUrl" if serialize else "unity_package_url"): _to_legacy_value(getattr(self, "unity_package_url", None), serialize),
            ("unityVersion" if serialize else "unity_version"): _to_legacy_value(getattr(self, "unity_version", None), serialize),
            ("version" if serialize else "version"): _to_legacy_value(getattr(self, "version", None), serialize),
        }

    def __openapi_generator_modern_projection(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    setattr(
        to_dict,
        _OPENAPI_GENERATOR_TO_DICT,
        __openapi_generator_modern_projection,
    )
    setattr(
        __openapi_generator_modern_projection,
        _OPENAPI_GENERATOR_TO_DICT,
        to_dict,
    )
    del __openapi_generator_modern_projection

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateAvatarRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        obj = _cast(
            Dict[str, Any],
            cls.__preprocess_input_names(
                obj,
                remove_hidden_storage_names=True,
            ),
        )

        _obj = cls.model_validate({
            "assetUrl": obj.get("assetUrl"),
            "description": obj.get("description"),
            "id": obj.get("id"),
            "imageUrl": obj.get("imageUrl"),
            "name": obj.get("name"),
            "releaseStatus": obj.get("releaseStatus") if obj.get("releaseStatus") is not None else ReleaseStatus.PUBLIC,
            "tags": obj.get("tags"),
            "unityPackageUrl": obj.get("unityPackageUrl"),
            "unityVersion": obj.get("unityVersion") if obj.get("unityVersion") is not None else '5.3.4p1',
            "version": obj.get("version") if obj.get("version") is not None else 1
        })
        return _obj


